// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activities.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActivityLogsByProjectID = `-- name: CountActivityLogsByProjectID :one
SELECT COUNT(*) AS count
FROM activity_logs
WHERE project_id = $1
`

func (q *Queries) CountActivityLogsByProjectID(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityLogsByProjectID, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActivityLogsByUserID = `-- name: CountActivityLogsByUserID :one
SELECT COUNT(*) AS count
FROM activity_logs
WHERE user_id = $1
`

func (q *Queries) CountActivityLogsByUserID(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityLogsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityLog = `-- name: CreateActivityLog :one
INSERT INTO activity_logs (
    id,
    project_id,
    user_id,
    action,
    entity_type,
    entity_id
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, user_id, action, entity_type, entity_id, created_at
`

type CreateActivityLogParams struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	UserID     pgtype.UUID
	Action     string
	EntityType pgtype.Text
	EntityID   pgtype.UUID
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, createActivityLog,
		arg.ID,
		arg.ProjectID,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteActivityLogByID = `-- name: DeleteActivityLogByID :exec
DELETE
FROM activity_logs
WHERE id = $1
`

func (q *Queries) DeleteActivityLogByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteActivityLogByID, id)
	return err
}

const deleteActivityLogsByProjectID = `-- name: DeleteActivityLogsByProjectID :exec
DELETE
FROM activity_logs
WHERE project_id = $1
`

func (q *Queries) DeleteActivityLogsByProjectID(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteActivityLogsByProjectID, projectID)
	return err
}

const getActivityLogByID = `-- name: GetActivityLogByID :one
SELECT id, project_id, user_id, action, entity_type, entity_id, created_at
FROM activity_logs
WHERE id = $1
`

func (q *Queries) GetActivityLogByID(ctx context.Context, id pgtype.UUID) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, getActivityLogByID, id)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.CreatedAt,
	)
	return i, err
}

const getActivityLogsByAction = `-- name: GetActivityLogsByAction :many
SELECT id, project_id, user_id, action, entity_type, entity_id, created_at
FROM activity_logs
WHERE action = $1
ORDER BY created_at DESC
`

func (q *Queries) GetActivityLogsByAction(ctx context.Context, action string) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, getActivityLogsByAction, action)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivityLogsByEntity = `-- name: GetActivityLogsByEntity :many
SELECT id, project_id, user_id, action, entity_type, entity_id, created_at
FROM activity_logs
WHERE entity_type = $1
  AND entity_id = $2
ORDER BY created_at DESC
`

type GetActivityLogsByEntityParams struct {
	EntityType pgtype.Text
	EntityID   pgtype.UUID
}

func (q *Queries) GetActivityLogsByEntity(ctx context.Context, arg GetActivityLogsByEntityParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, getActivityLogsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivityLogsByProjectAndAction = `-- name: GetActivityLogsByProjectAndAction :many
SELECT id, project_id, user_id, action, entity_type, entity_id, created_at
FROM activity_logs
WHERE project_id = $1
  AND action = $2
ORDER BY created_at DESC
`

type GetActivityLogsByProjectAndActionParams struct {
	ProjectID pgtype.UUID
	Action    string
}

func (q *Queries) GetActivityLogsByProjectAndAction(ctx context.Context, arg GetActivityLogsByProjectAndActionParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, getActivityLogsByProjectAndAction, arg.ProjectID, arg.Action)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivityLogsByProjectAndUser = `-- name: GetActivityLogsByProjectAndUser :many
SELECT id, project_id, user_id, action, entity_type, entity_id, created_at
FROM activity_logs
WHERE project_id = $1
  AND user_id = $2
ORDER BY created_at DESC
`

type GetActivityLogsByProjectAndUserParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) GetActivityLogsByProjectAndUser(ctx context.Context, arg GetActivityLogsByProjectAndUserParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, getActivityLogsByProjectAndUser, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivityLogsByProjectID = `-- name: GetActivityLogsByProjectID :many
SELECT id, project_id, user_id, action, entity_type, entity_id, created_at
FROM activity_logs
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetActivityLogsByProjectID(ctx context.Context, projectID pgtype.UUID) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, getActivityLogsByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivityLogsByProjectUserAndAction = `-- name: GetActivityLogsByProjectUserAndAction :many
SELECT id, project_id, user_id, action, entity_type, entity_id, created_at
FROM activity_logs
WHERE project_id = $1
  AND user_id = $2
  AND action = $3
ORDER BY created_at DESC
`

type GetActivityLogsByProjectUserAndActionParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
	Action    string
}

func (q *Queries) GetActivityLogsByProjectUserAndAction(ctx context.Context, arg GetActivityLogsByProjectUserAndActionParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, getActivityLogsByProjectUserAndAction, arg.ProjectID, arg.UserID, arg.Action)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivityLogsByUserAndAction = `-- name: GetActivityLogsByUserAndAction :many
SELECT id, project_id, user_id, action, entity_type, entity_id, created_at
FROM activity_logs
WHERE user_id = $1
  AND action = $2
ORDER BY created_at DESC
`

type GetActivityLogsByUserAndActionParams struct {
	UserID pgtype.UUID
	Action string
}

func (q *Queries) GetActivityLogsByUserAndAction(ctx context.Context, arg GetActivityLogsByUserAndActionParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, getActivityLogsByUserAndAction, arg.UserID, arg.Action)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActivityLogsByUserID = `-- name: GetActivityLogsByUserID :many
SELECT id, project_id, user_id, action, entity_type, entity_id, created_at
FROM activity_logs
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetActivityLogsByUserID(ctx context.Context, userID pgtype.UUID) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, getActivityLogsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentActivityLogs = `-- name: GetRecentActivityLogs :many
SELECT id, project_id, user_id, action, entity_type, entity_id, created_at
FROM activity_logs
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetRecentActivityLogs(ctx context.Context, limit int32) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, getRecentActivityLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
