// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats (
    id,
    project_id,
    title,
    type
)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, title, type, last_activity_at, status, created_at, updated_at
`

type CreateChatParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	Title     pgtype.Text
	Type      ChatType
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, createChat,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Type,
	)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Type,
		&i.LastActivityAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createChatAIMetadata = `-- name: CreateChatAIMetadata :one
INSERT INTO chat_ai_metadata (
    message_id,
    embedding_model,
    embedding_synced,
    indexed_at
)
VALUES ($1, $2, $3, $4)
RETURNING message_id, embedding_model, embedding_synced, indexed_at
`

type CreateChatAIMetadataParams struct {
	MessageID       pgtype.UUID
	EmbeddingModel  pgtype.Text
	EmbeddingSynced pgtype.Bool
	IndexedAt       pgtype.Timestamptz
}

func (q *Queries) CreateChatAIMetadata(ctx context.Context, arg CreateChatAIMetadataParams) (ChatAiMetadatum, error) {
	row := q.db.QueryRow(ctx, createChatAIMetadata,
		arg.MessageID,
		arg.EmbeddingModel,
		arg.EmbeddingSynced,
		arg.IndexedAt,
	)
	var i ChatAiMetadatum
	err := row.Scan(
		&i.MessageID,
		&i.EmbeddingModel,
		&i.EmbeddingSynced,
		&i.IndexedAt,
	)
	return i, err
}

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (
    id,
    chat_id,
    sender_id,
    role,
    content
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, chat_id, sender_id, role, content, created_at, updated_at
`

type CreateChatMessageParams struct {
	ID       pgtype.UUID
	ChatID   pgtype.UUID
	SenderID pgtype.UUID
	Role     MessageRole
	Content  string
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, createChatMessage,
		arg.ID,
		arg.ChatID,
		arg.SenderID,
		arg.Role,
		arg.Content,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChat = `-- name: DeleteChat :exec
DELETE
FROM chats
WHERE id = $1
`

func (q *Queries) DeleteChat(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChat, id)
	return err
}

const deleteChatAIMetadata = `-- name: DeleteChatAIMetadata :exec
DELETE
FROM chat_ai_metadata
WHERE message_id = $1
`

func (q *Queries) DeleteChatAIMetadata(ctx context.Context, messageID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChatAIMetadata, messageID)
	return err
}

const deleteChatMessage = `-- name: DeleteChatMessage :exec
DELETE
FROM chat_messages
WHERE id = $1
`

func (q *Queries) DeleteChatMessage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChatMessage, id)
	return err
}

const generatingChats = `-- name: GeneratingChats :many
SELECT id, project_id, title, type, last_activity_at, status, created_at, updated_at
FROM chats
WHERE project_id = $1
    AND status = 'GENERATING'
`

func (q *Queries) GeneratingChats(ctx context.Context, projectID pgtype.UUID) ([]Chat, error) {
	rows, err := q.db.Query(ctx, generatingChats, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Type,
			&i.LastActivityAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveChats = `-- name: GetActiveChats :many
SELECT id, project_id, title, type, last_activity_at, status, created_at, updated_at
FROM chats
WHERE project_id = $1
    AND status = 'ACTIVE'
ORDER BY last_activity_at DESC
`

func (q *Queries) GetActiveChats(ctx context.Context, projectID pgtype.UUID) ([]Chat, error) {
	rows, err := q.db.Query(ctx, getActiveChats, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Type,
			&i.LastActivityAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivedChatMessages = `-- name: GetArchivedChatMessages :many
SELECT cm.id, cm.chat_id, cm.sender_id, cm.role, cm.content, cm.created_at, cm.updated_at
FROM chat_messages cm
JOIN chats c
ON cm.chat_id = c.id
WHERE cm.chat_id = $1
    AND c.status = 'ARCHIVED'
ORDER BY cm.created_at ASC
`

func (q *Queries) GetArchivedChatMessages(ctx context.Context, chatID pgtype.UUID) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, getArchivedChatMessages, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivedChats = `-- name: GetArchivedChats :many
SELECT id, project_id, title, type, last_activity_at, status, created_at, updated_at
FROM chats
WHERE project_id = $1
    AND status = 'ARCHIVED'
ORDER BY last_activity_at DESC
`

func (q *Queries) GetArchivedChats(ctx context.Context, projectID pgtype.UUID) ([]Chat, error) {
	rows, err := q.db.Query(ctx, getArchivedChats, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Type,
			&i.LastActivityAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatAIMetadata = `-- name: GetChatAIMetadata :one
SELECT message_id, embedding_model, embedding_synced, indexed_at
FROM chat_ai_metadata
WHERE message_id = $1
`

func (q *Queries) GetChatAIMetadata(ctx context.Context, messageID pgtype.UUID) (ChatAiMetadatum, error) {
	row := q.db.QueryRow(ctx, getChatAIMetadata, messageID)
	var i ChatAiMetadatum
	err := row.Scan(
		&i.MessageID,
		&i.EmbeddingModel,
		&i.EmbeddingSynced,
		&i.IndexedAt,
	)
	return i, err
}

const getChatByID = `-- name: GetChatByID :one
SELECT id, project_id, title, type, last_activity_at, status, created_at, updated_at
FROM chats
WHERE id = $1
`

func (q *Queries) GetChatByID(ctx context.Context, id pgtype.UUID) (Chat, error) {
	row := q.db.QueryRow(ctx, getChatByID, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Type,
		&i.LastActivityAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatMessageByID = `-- name: GetChatMessageByID :one
SELECT id, chat_id, sender_id, role, content, created_at, updated_at
FROM chat_messages
WHERE id = $1
`

func (q *Queries) GetChatMessageByID(ctx context.Context, id pgtype.UUID) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, getChatMessageByID, id)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatMessagesByChatID = `-- name: GetChatMessagesByChatID :many
SELECT id, chat_id, sender_id, role, content, created_at, updated_at
FROM chat_messages
WHERE chat_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetChatMessagesByChatID(ctx context.Context, chatID pgtype.UUID) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, getChatMessagesByChatID, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMessagesByIDs = `-- name: GetChatMessagesByIDs :many
SELECT id, chat_id, sender_id, role, content, created_at, updated_at
FROM chat_messages
WHERE id = ANY($1::UUID[])
ORDER BY created_at ASC
`

func (q *Queries) GetChatMessagesByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, getChatMessagesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMessagesByRole = `-- name: GetChatMessagesByRole :many
SELECT id, chat_id, sender_id, role, content, created_at, updated_at
FROM chat_messages
WHERE chat_id = $1
  AND role = $2
ORDER BY created_at ASC
`

type GetChatMessagesByRoleParams struct {
	ChatID pgtype.UUID
	Role   MessageRole
}

func (q *Queries) GetChatMessagesByRole(ctx context.Context, arg GetChatMessagesByRoleParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, getChatMessagesByRole, arg.ChatID, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMessagesBySender = `-- name: GetChatMessagesBySender :many
SELECT id, chat_id, sender_id, role, content, created_at, updated_at
FROM chat_messages
WHERE chat_id = $1
  AND sender_id = $2
ORDER BY created_at ASC
`

type GetChatMessagesBySenderParams struct {
	ChatID   pgtype.UUID
	SenderID pgtype.UUID
}

func (q *Queries) GetChatMessagesBySender(ctx context.Context, arg GetChatMessagesBySenderParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, getChatMessagesBySender, arg.ChatID, arg.SenderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMessagesWithSender = `-- name: GetChatMessagesWithSender :many
SELECT
    cm.id, cm.chat_id, cm.sender_id, cm.role, cm.content, cm.created_at, cm.updated_at,
    u.username
FROM chat_messages cm
LEFT JOIN users u
ON cm.sender_id = u.id
WHERE cm.chat_id = $1
ORDER BY cm.created_at ASC
`

type GetChatMessagesWithSenderRow struct {
	ID        pgtype.UUID
	ChatID    pgtype.UUID
	SenderID  pgtype.UUID
	Role      MessageRole
	Content   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Username  pgtype.Text
}

func (q *Queries) GetChatMessagesWithSender(ctx context.Context, chatID pgtype.UUID) ([]GetChatMessagesWithSenderRow, error) {
	rows, err := q.db.Query(ctx, getChatMessagesWithSender, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChatMessagesWithSenderRow
	for rows.Next() {
		var i GetChatMessagesWithSenderRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatsByProjectAndType = `-- name: GetChatsByProjectAndType :many
SELECT id, project_id, title, type, last_activity_at, status, created_at, updated_at
FROM chats
WHERE project_id = $1
  AND type = $2
ORDER BY last_activity_at DESC
`

type GetChatsByProjectAndTypeParams struct {
	ProjectID pgtype.UUID
	Type      ChatType
}

func (q *Queries) GetChatsByProjectAndType(ctx context.Context, arg GetChatsByProjectAndTypeParams) ([]Chat, error) {
	rows, err := q.db.Query(ctx, getChatsByProjectAndType, arg.ProjectID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Type,
			&i.LastActivityAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatsByProjectID = `-- name: GetChatsByProjectID :many
SELECT id, project_id, title, type, last_activity_at, status, created_at, updated_at
FROM chats
WHERE project_id = $1
ORDER BY last_activity_at DESC
`

func (q *Queries) GetChatsByProjectID(ctx context.Context, projectID pgtype.UUID) ([]Chat, error) {
	rows, err := q.db.Query(ctx, getChatsByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Type,
			&i.LastActivityAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestChatMessage = `-- name: GetLatestChatMessage :one
SELECT id, chat_id, sender_id, role, content, created_at, updated_at
FROM chat_messages
WHERE chat_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestChatMessage(ctx context.Context, chatID pgtype.UUID) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, getLatestChatMessage, chatID)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const renameChat = `-- name: RenameChat :one
UPDATE chats
SET
    title = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, title, type, last_activity_at, status, created_at, updated_at
`

type RenameChatParams struct {
	ID    pgtype.UUID
	Title pgtype.Text
}

func (q *Queries) RenameChat(ctx context.Context, arg RenameChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, renameChat, arg.ID, arg.Title)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Type,
		&i.LastActivityAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchChatMessages = `-- name: SearchChatMessages :many
SELECT cm.id, cm.chat_id, cm.sender_id, cm.role, cm.content, cm.created_at, cm.updated_at
FROM chat_messages cm
JOIN chats c
ON cm.chat_id = c.id
WHERE c.project_id = $1
  AND cm.content ILIKE '%' || $2 || '%'
ORDER BY cm.created_at DESC
`

type SearchChatMessagesParams struct {
	ProjectID pgtype.UUID
	Column2   pgtype.Text
}

func (q *Queries) SearchChatMessages(ctx context.Context, arg SearchChatMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, searchChatMessages, arg.ProjectID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchChatsByTitle = `-- name: SearchChatsByTitle :many
SELECT id, project_id, title, type, last_activity_at, status, created_at, updated_at
FROM chats
WHERE project_id = $1
  AND title ILIKE '%' || $2 || '%'
ORDER BY last_activity_at DESC
`

type SearchChatsByTitleParams struct {
	ProjectID pgtype.UUID
	Column2   pgtype.Text
}

func (q *Queries) SearchChatsByTitle(ctx context.Context, arg SearchChatsByTitleParams) ([]Chat, error) {
	rows, err := q.db.Query(ctx, searchChatsByTitle, arg.ProjectID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Type,
			&i.LastActivityAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChatAIMetadata = `-- name: UpdateChatAIMetadata :one
UPDATE chat_ai_metadata
SET
    embedding_model = $2,
    embedding_synced = $3,
    indexed_at = $4
WHERE message_id = $1
RETURNING message_id, embedding_model, embedding_synced, indexed_at
`

type UpdateChatAIMetadataParams struct {
	MessageID       pgtype.UUID
	EmbeddingModel  pgtype.Text
	EmbeddingSynced pgtype.Bool
	IndexedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateChatAIMetadata(ctx context.Context, arg UpdateChatAIMetadataParams) (ChatAiMetadatum, error) {
	row := q.db.QueryRow(ctx, updateChatAIMetadata,
		arg.MessageID,
		arg.EmbeddingModel,
		arg.EmbeddingSynced,
		arg.IndexedAt,
	)
	var i ChatAiMetadatum
	err := row.Scan(
		&i.MessageID,
		&i.EmbeddingModel,
		&i.EmbeddingSynced,
		&i.IndexedAt,
	)
	return i, err
}

const updateChatActivity = `-- name: UpdateChatActivity :exec
UPDATE chats
SET
    last_activity_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateChatActivity(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateChatActivity, id)
	return err
}

const updateChatMessage = `-- name: UpdateChatMessage :one
UPDATE chat_messages
SET
    content = $2
WHERE id = $1
RETURNING id, chat_id, sender_id, role, content, created_at, updated_at
`

type UpdateChatMessageParams struct {
	ID      pgtype.UUID
	Content string
}

func (q *Queries) UpdateChatMessage(ctx context.Context, arg UpdateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, updateChatMessage, arg.ID, arg.Content)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChatStatus = `-- name: UpdateChatStatus :one
UPDATE chats
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, title, type, last_activity_at, status, created_at, updated_at
`

type UpdateChatStatusParams struct {
	ID     pgtype.UUID
	Status ChatStatus
}

func (q *Queries) UpdateChatStatus(ctx context.Context, arg UpdateChatStatusParams) (Chat, error) {
	row := q.db.QueryRow(ctx, updateChatStatus, arg.ID, arg.Status)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Type,
		&i.LastActivityAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChatType = `-- name: UpdateChatType :one
UPDATE chats
SET
    type = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, title, type, last_activity_at, status, created_at, updated_at
`

type UpdateChatTypeParams struct {
	ID   pgtype.UUID
	Type ChatType
}

func (q *Queries) UpdateChatType(ctx context.Context, arg UpdateChatTypeParams) (Chat, error) {
	row := q.db.QueryRow(ctx, updateChatType, arg.ID, arg.Type)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Type,
		&i.LastActivityAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
