// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkFileNameExists = `-- name: CheckFileNameExists :one
SELECT EXISTS (
    SELECT 1
    FROM files
    WHERE folder_id IS NOT DISTINCT FROM $1
      AND name = $2
)
`

type CheckFileNameExistsParams struct {
	FolderID pgtype.UUID
	Name     string
}

func (q *Queries) CheckFileNameExists(ctx context.Context, arg CheckFileNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkFileNameExists, arg.FolderID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkFolderNameExists = `-- name: CheckFolderNameExists :one
SELECT EXISTS (
    SELECT 1
    FROM folders
    WHERE project_id = $1
      AND parent_folder_id IS NOT DISTINCT FROM $2
      AND name = $3
)
`

type CheckFolderNameExistsParams struct {
	ProjectID      pgtype.UUID
	ParentFolderID pgtype.UUID
	Name           string
}

func (q *Queries) CheckFolderNameExists(ctx context.Context, arg CheckFolderNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkFolderNameExists, arg.ProjectID, arg.ParentFolderID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkProjectContainsFile = `-- name: CheckProjectContainsFile :one
SELECT EXISTS (
    SELECT 1
    FROM files
    WHERE project_id = $1
      AND id = $2
)
`

type CheckProjectContainsFileParams struct {
	ProjectID pgtype.UUID
	ID        pgtype.UUID
}

func (q *Queries) CheckProjectContainsFile(ctx context.Context, arg CheckProjectContainsFileParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkProjectContainsFile, arg.ProjectID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkProjectFileNameExists = `-- name: CheckProjectFileNameExists :one
SELECT EXISTS (
    SELECT 1
    FROM files f
    WHERE f.project_id = $1
      AND f.folder_id IS NOT DISTINCT FROM $2
      AND f.name = $3
)
`

type CheckProjectFileNameExistsParams struct {
	ProjectID pgtype.UUID
	FolderID  pgtype.UUID
	Name      string
}

func (q *Queries) CheckProjectFileNameExists(ctx context.Context, arg CheckProjectFileNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkProjectFileNameExists, arg.ProjectID, arg.FolderID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countProjectFiles = `-- name: CountProjectFiles :one
SELECT COUNT(*) AS count
FROM files
WHERE project_id = $1
`

func (q *Queries) CountProjectFiles(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectFiles, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (
    folder_id,
    project_id,
    name,
    size
)
VALUES ($1, $2, $3,$4)
RETURNING id, folder_id, project_id, name, size, created_at, updated_at
`

type CreateFileParams struct {
	FolderID  pgtype.UUID
	ProjectID pgtype.UUID
	Name      string
	Size      int64
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.FolderID,
		arg.ProjectID,
		arg.Name,
		arg.Size,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.ProjectID,
		&i.Name,
		&i.Size,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFileAIMetadata = `-- name: CreateFileAIMetadata :one
INSERT INTO file_ai_metadata (
    file_id,
    extracted_text,
    embedding_model,
    embedding_synced,
    indexed_at
)
VALUES ($1, $2, $3, $4, $5)
RETURNING file_id, extracted_text, embedding_model, embedding_synced, indexed_at, created_at, updated_at
`

type CreateFileAIMetadataParams struct {
	FileID          pgtype.UUID
	ExtractedText   pgtype.Text
	EmbeddingModel  pgtype.Text
	EmbeddingSynced pgtype.Bool
	IndexedAt       pgtype.Timestamptz
}

func (q *Queries) CreateFileAIMetadata(ctx context.Context, arg CreateFileAIMetadataParams) (FileAiMetadatum, error) {
	row := q.db.QueryRow(ctx, createFileAIMetadata,
		arg.FileID,
		arg.ExtractedText,
		arg.EmbeddingModel,
		arg.EmbeddingSynced,
		arg.IndexedAt,
	)
	var i FileAiMetadatum
	err := row.Scan(
		&i.FileID,
		&i.ExtractedText,
		&i.EmbeddingModel,
		&i.EmbeddingSynced,
		&i.IndexedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFileProperties = `-- name: CreateFileProperties :one
INSERT INTO file_properties (
    file_id,
    original_name,
    is_indexed,
    deleted_at
)
VALUES ($1, $2, $3, $4)
RETURNING file_id, original_name, is_indexed, created_at, updated_at, deleted_at
`

type CreateFilePropertiesParams struct {
	FileID       pgtype.UUID
	OriginalName pgtype.Text
	IsIndexed    bool
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) CreateFileProperties(ctx context.Context, arg CreateFilePropertiesParams) (FileProperty, error) {
	row := q.db.QueryRow(ctx, createFileProperties,
		arg.FileID,
		arg.OriginalName,
		arg.IsIndexed,
		arg.DeletedAt,
	)
	var i FileProperty
	err := row.Scan(
		&i.FileID,
		&i.OriginalName,
		&i.IsIndexed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createFileStorage = `-- name: CreateFileStorage :one
INSERT INTO file_storage (
    file_id,
    bucket_name,
    object_key,
    etag,
    version_id,
    checksum,
    mime_type,
    uploaded_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING file_id, bucket_name, object_key, etag, version_id, checksum, mime_type, created_at, updated_at, uploaded_by
`

type CreateFileStorageParams struct {
	FileID     pgtype.UUID
	BucketName string
	ObjectKey  string
	Etag       pgtype.Text
	VersionID  pgtype.Text
	Checksum   pgtype.Text
	MimeType   string
	UploadedBy pgtype.UUID
}

func (q *Queries) CreateFileStorage(ctx context.Context, arg CreateFileStorageParams) (FileStorage, error) {
	row := q.db.QueryRow(ctx, createFileStorage,
		arg.FileID,
		arg.BucketName,
		arg.ObjectKey,
		arg.Etag,
		arg.VersionID,
		arg.Checksum,
		arg.MimeType,
		arg.UploadedBy,
	)
	var i FileStorage
	err := row.Scan(
		&i.FileID,
		&i.BucketName,
		&i.ObjectKey,
		&i.Etag,
		&i.VersionID,
		&i.Checksum,
		&i.MimeType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UploadedBy,
	)
	return i, err
}

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (
    project_id,
    parent_folder_id,
    name
)
VALUES ($1, $2, $3)
RETURNING id, project_id, parent_folder_id, name, created_at, updated_at
`

type CreateFolderParams struct {
	ProjectID      pgtype.UUID
	ParentFolderID pgtype.UUID
	Name           string
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder, arg.ProjectID, arg.ParentFolderID, arg.Name)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentFolderID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessageFileReference = `-- name: CreateMessageFileReference :one
INSERT INTO message_file_references (
    message_id,
    file_id
)
VALUES ($1, $2)
RETURNING message_id, file_id, created_at
`

type CreateMessageFileReferenceParams struct {
	MessageID pgtype.UUID
	FileID    pgtype.UUID
}

func (q *Queries) CreateMessageFileReference(ctx context.Context, arg CreateMessageFileReferenceParams) (MessageFileReference, error) {
	row := q.db.QueryRow(ctx, createMessageFileReference, arg.MessageID, arg.FileID)
	var i MessageFileReference
	err := row.Scan(&i.MessageID, &i.FileID, &i.CreatedAt)
	return i, err
}

const createProjectFile = `-- name: CreateProjectFile :one
INSERT INTO project_files (
    project_id,
    file_id,
    folder_id
)
VALUES ($1, $2, $3)
RETURNING project_id, file_id, folder_id, created_at
`

type CreateProjectFileParams struct {
	ProjectID pgtype.UUID
	FileID    pgtype.UUID
	FolderID  pgtype.UUID
}

func (q *Queries) CreateProjectFile(ctx context.Context, arg CreateProjectFileParams) (ProjectFile, error) {
	row := q.db.QueryRow(ctx, createProjectFile, arg.ProjectID, arg.FileID, arg.FolderID)
	var i ProjectFile
	err := row.Scan(
		&i.ProjectID,
		&i.FileID,
		&i.FolderID,
		&i.CreatedAt,
	)
	return i, err
}

const createUserFilePreference = `-- name: CreateUserFilePreference :one
INSERT INTO user_file_preferences (
    user_id,
    file_id,
    is_favorite
)
VALUES ($1, $2, $3)
RETURNING user_id, file_id, is_favorite, created_at, updated_at
`

type CreateUserFilePreferenceParams struct {
	UserID     pgtype.UUID
	FileID     pgtype.UUID
	IsFavorite bool
}

func (q *Queries) CreateUserFilePreference(ctx context.Context, arg CreateUserFilePreferenceParams) (UserFilePreference, error) {
	row := q.db.QueryRow(ctx, createUserFilePreference, arg.UserID, arg.FileID, arg.IsFavorite)
	var i UserFilePreference
	err := row.Scan(
		&i.UserID,
		&i.FileID,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE
FROM files
WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const deleteFileAIMetadata = `-- name: DeleteFileAIMetadata :exec
DELETE
FROM file_ai_metadata
WHERE file_id = $1
`

func (q *Queries) DeleteFileAIMetadata(ctx context.Context, fileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFileAIMetadata, fileID)
	return err
}

const deleteFileProperties = `-- name: DeleteFileProperties :exec
DELETE
FROM file_properties
WHERE file_id = $1
`

func (q *Queries) DeleteFileProperties(ctx context.Context, fileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFileProperties, fileID)
	return err
}

const deleteFileShare = `-- name: DeleteFileShare :exec
DELETE
FROM file_shares
WHERE id = $1
`

func (q *Queries) DeleteFileShare(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFileShare, id)
	return err
}

const deleteFileStorage = `-- name: DeleteFileStorage :exec
DELETE
FROM file_storage
WHERE file_id = $1
`

func (q *Queries) DeleteFileStorage(ctx context.Context, fileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFileStorage, fileID)
	return err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE
FROM folders
WHERE id = $1
`

func (q *Queries) DeleteFolder(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFolder, id)
	return err
}

const deleteMessageFileReferences = `-- name: DeleteMessageFileReferences :exec
DELETE
FROM message_file_references
WHERE message_id = $1
`

func (q *Queries) DeleteMessageFileReferences(ctx context.Context, messageID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessageFileReferences, messageID)
	return err
}

const deleteUserFilePreference = `-- name: DeleteUserFilePreference :exec
DELETE
FROM user_file_preferences
WHERE user_id = $1
  AND file_id = $2
`

type DeleteUserFilePreferenceParams struct {
	UserID pgtype.UUID
	FileID pgtype.UUID
}

func (q *Queries) DeleteUserFilePreference(ctx context.Context, arg DeleteUserFilePreferenceParams) error {
	_, err := q.db.Exec(ctx, deleteUserFilePreference, arg.UserID, arg.FileID)
	return err
}

const fileNameExistsInFolder = `-- name: FileNameExistsInFolder :one
SELECT EXISTS (
    SELECT 1
    FROM files
    WHERE project_id = $1
      AND folder_id IS NOT DISTINCT FROM $2
      AND name = $3
)
`

type FileNameExistsInFolderParams struct {
	ProjectID pgtype.UUID
	FolderID  pgtype.UUID
	Name      string
}

func (q *Queries) FileNameExistsInFolder(ctx context.Context, arg FileNameExistsInFolderParams) (bool, error) {
	row := q.db.QueryRow(ctx, fileNameExistsInFolder, arg.ProjectID, arg.FolderID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const fileShare = `-- name: FileShare :one
INSERT INTO file_shares (
    file_id,
    shared_by,
    shared_with,
    permission
)
VALUES ($1, $2, $3, $4)
RETURNING id, file_id, shared_by, shared_with, permission, created_at
`

type FileShareParams struct {
	FileID     pgtype.UUID
	SharedBy   pgtype.UUID
	SharedWith pgtype.UUID
	Permission FilePermission
}

func (q *Queries) FileShare(ctx context.Context, arg FileShareParams) (FileShare, error) {
	row := q.db.QueryRow(ctx, fileShare,
		arg.FileID,
		arg.SharedBy,
		arg.SharedWith,
		arg.Permission,
	)
	var i FileShare
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.SharedBy,
		&i.SharedWith,
		&i.Permission,
		&i.CreatedAt,
	)
	return i, err
}

const folderNameExists = `-- name: FolderNameExists :one
SELECT EXISTS (
    SELECT 1
    FROM folders
    WHERE name = $1
      AND parent_folder_id IS NOT DISTINCT FROM $2
      AND project_id IS NOT DISTINCT FROM $3
)
`

type FolderNameExistsParams struct {
	Name           string
	ParentFolderID pgtype.UUID
	ProjectID      pgtype.UUID
}

func (q *Queries) FolderNameExists(ctx context.Context, arg FolderNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, folderNameExists, arg.Name, arg.ParentFolderID, arg.ProjectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getChildFolders = `-- name: GetChildFolders :many
SELECT id, project_id, parent_folder_id, name, created_at, updated_at
FROM folders
WHERE parent_folder_id IS NOT DISTINCT FROM $1
ORDER BY name
`

func (q *Queries) GetChildFolders(ctx context.Context, parentFolderID pgtype.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, getChildFolders, parentFolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentFolderID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeletedFiles = `-- name: GetDeletedFiles :many
SELECT f.id, f.folder_id, f.project_id, f.name, f.size, f.created_at, f.updated_at
FROM files f
JOIN file_properties fp
ON f.id = fp.file_id
WHERE fp.deleted_at IS NOT NULL
  AND f.project_id = $1
ORDER BY fp.deleted_at DESC
`

func (q *Queries) GetDeletedFiles(ctx context.Context, projectID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, getDeletedFiles, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.ProjectID,
			&i.Name,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFavoritesFiles = `-- name: GetFavoritesFiles :many
SELECT f.id, f.folder_id, f.project_id, f.name, f.size, f.created_at, f.updated_at
FROM files f
JOIN user_file_preferences ufp
ON f.id = ufp.file_id
WHERE ufp.user_id = $1
  AND ufp.is_favorite = TRUE
  AND f.project_id = $2
`

type GetFavoritesFilesParams struct {
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
}

func (q *Queries) GetFavoritesFiles(ctx context.Context, arg GetFavoritesFilesParams) ([]File, error) {
	rows, err := q.db.Query(ctx, getFavoritesFiles, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.ProjectID,
			&i.Name,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileAIMetadata = `-- name: GetFileAIMetadata :one
SELECT file_id, extracted_text, embedding_model, embedding_synced, indexed_at, created_at, updated_at
FROM file_ai_metadata
WHERE file_id = $1
`

func (q *Queries) GetFileAIMetadata(ctx context.Context, fileID pgtype.UUID) (FileAiMetadatum, error) {
	row := q.db.QueryRow(ctx, getFileAIMetadata, fileID)
	var i FileAiMetadatum
	err := row.Scan(
		&i.FileID,
		&i.ExtractedText,
		&i.EmbeddingModel,
		&i.EmbeddingSynced,
		&i.IndexedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileByFolderAndName = `-- name: GetFileByFolderAndName :one
SELECT id, folder_id, project_id, name, size, created_at, updated_at
FROM files
WHERE folder_id IS NOT DISTINCT FROM $1
  AND name = $2
`

type GetFileByFolderAndNameParams struct {
	FolderID pgtype.UUID
	Name     string
}

func (q *Queries) GetFileByFolderAndName(ctx context.Context, arg GetFileByFolderAndNameParams) (File, error) {
	row := q.db.QueryRow(ctx, getFileByFolderAndName, arg.FolderID, arg.Name)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.ProjectID,
		&i.Name,
		&i.Size,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, folder_id, project_id, name, size, created_at, updated_at
FROM files
WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id pgtype.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.ProjectID,
		&i.Name,
		&i.Size,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileProperties = `-- name: GetFileProperties :one
SELECT file_id, original_name, is_indexed, created_at, updated_at, deleted_at
FROM file_properties
WHERE file_id = $1
`

func (q *Queries) GetFileProperties(ctx context.Context, fileID pgtype.UUID) (FileProperty, error) {
	row := q.db.QueryRow(ctx, getFileProperties, fileID)
	var i FileProperty
	err := row.Scan(
		&i.FileID,
		&i.OriginalName,
		&i.IsIndexed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFileShareByFileAndSharedWith = `-- name: GetFileShareByFileAndSharedWith :one
SELECT id, file_id, shared_by, shared_with, permission, created_at
FROM file_shares
WHERE file_id = $1
  AND shared_with = $2
`

type GetFileShareByFileAndSharedWithParams struct {
	FileID     pgtype.UUID
	SharedWith pgtype.UUID
}

func (q *Queries) GetFileShareByFileAndSharedWith(ctx context.Context, arg GetFileShareByFileAndSharedWithParams) (FileShare, error) {
	row := q.db.QueryRow(ctx, getFileShareByFileAndSharedWith, arg.FileID, arg.SharedWith)
	var i FileShare
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.SharedBy,
		&i.SharedWith,
		&i.Permission,
		&i.CreatedAt,
	)
	return i, err
}

const getFileShareByID = `-- name: GetFileShareByID :one
SELECT id, file_id, shared_by, shared_with, permission, created_at
FROM file_shares
WHERE id = $1
`

func (q *Queries) GetFileShareByID(ctx context.Context, id pgtype.UUID) (FileShare, error) {
	row := q.db.QueryRow(ctx, getFileShareByID, id)
	var i FileShare
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.SharedBy,
		&i.SharedWith,
		&i.Permission,
		&i.CreatedAt,
	)
	return i, err
}

const getFileSharesByFileID = `-- name: GetFileSharesByFileID :many
SELECT id, file_id, shared_by, shared_with, permission, created_at
FROM file_shares
WHERE file_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetFileSharesByFileID(ctx context.Context, fileID pgtype.UUID) ([]FileShare, error) {
	rows, err := q.db.Query(ctx, getFileSharesByFileID, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileShare
	for rows.Next() {
		var i FileShare
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.SharedBy,
			&i.SharedWith,
			&i.Permission,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileSharesBySharedWith = `-- name: GetFileSharesBySharedWith :many
SELECT id, file_id, shared_by, shared_with, permission, created_at
FROM file_shares
WHERE shared_with = $1
ORDER BY created_at DESC
`

func (q *Queries) GetFileSharesBySharedWith(ctx context.Context, sharedWith pgtype.UUID) ([]FileShare, error) {
	rows, err := q.db.Query(ctx, getFileSharesBySharedWith, sharedWith)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileShare
	for rows.Next() {
		var i FileShare
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.SharedBy,
			&i.SharedWith,
			&i.Permission,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileStorage = `-- name: GetFileStorage :one
SELECT file_id, bucket_name, object_key, etag, version_id, checksum, mime_type, created_at, updated_at, uploaded_by
FROM file_storage
WHERE file_id = $1
`

func (q *Queries) GetFileStorage(ctx context.Context, fileID pgtype.UUID) (FileStorage, error) {
	row := q.db.QueryRow(ctx, getFileStorage, fileID)
	var i FileStorage
	err := row.Scan(
		&i.FileID,
		&i.BucketName,
		&i.ObjectKey,
		&i.Etag,
		&i.VersionID,
		&i.Checksum,
		&i.MimeType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UploadedBy,
	)
	return i, err
}

const getFilesByFolderID = `-- name: GetFilesByFolderID :many
SELECT id, folder_id, project_id, name, size, created_at, updated_at
FROM files
WHERE folder_id IS NOT DISTINCT FROM $1
ORDER BY name
`

func (q *Queries) GetFilesByFolderID(ctx context.Context, folderID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesByFolderID, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.ProjectID,
			&i.Name,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByIDs = `-- name: GetFilesByIDs :many
SELECT id, folder_id, project_id, name, size, created_at, updated_at
FROM files
WHERE id = ANY($1::UUID[])
ORDER BY name
`

func (q *Queries) GetFilesByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.ProjectID,
			&i.Name,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByProjectID = `-- name: GetFilesByProjectID :many
SELECT f.id, f.folder_id, f.project_id, f.name, f.size, f.created_at, f.updated_at
FROM files f
WHERE f.project_id = $1
ORDER BY f.name
`

func (q *Queries) GetFilesByProjectID(ctx context.Context, projectID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.ProjectID,
			&i.Name,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesPendingEmbedding = `-- name: GetFilesPendingEmbedding :many
SELECT f.id, f.folder_id, f.project_id, f.name, f.size, f.created_at, f.updated_at
FROM files f
JOIN file_ai_metadata fam
ON f.id = fam.file_id
WHERE fam.embedding_synced = FALSE
ORDER BY f.created_at ASC
`

func (q *Queries) GetFilesPendingEmbedding(ctx context.Context) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesPendingEmbedding)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.ProjectID,
			&i.Name,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesSharedByUser = `-- name: GetFilesSharedByUser :many
SELECT id, file_id, shared_by, shared_with, permission, created_at
FROM file_shares
WHERE shared_by = $1
ORDER BY created_at DESC
`

func (q *Queries) GetFilesSharedByUser(ctx context.Context, sharedBy pgtype.UUID) ([]FileShare, error) {
	rows, err := q.db.Query(ctx, getFilesSharedByUser, sharedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileShare
	for rows.Next() {
		var i FileShare
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.SharedBy,
			&i.SharedWith,
			&i.Permission,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, project_id, parent_folder_id, name, created_at, updated_at
FROM folders
WHERE id = $1
`

func (q *Queries) GetFolderByID(ctx context.Context, id pgtype.UUID) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentFolderID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolderContents = `-- name: GetFolderContents :many
SELECT
    f.id,
    f.name,
    'folder' AS item_type,
    f.created_at
FROM folders f
WHERE f.parent_folder_id IS NOT DISTINCT FROM $1
UNION ALL
SELECT
    fi.id,
    fi.name,
    'file' AS item_type,
    fi.created_at
FROM files fi
WHERE fi.folder_id IS NOT DISTINCT FROM $1
ORDER BY item_type, name
`

type GetFolderContentsRow struct {
	ID        pgtype.UUID
	Name      string
	ItemType  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetFolderContents(ctx context.Context, parentFolderID pgtype.UUID) ([]GetFolderContentsRow, error) {
	rows, err := q.db.Query(ctx, getFolderContents, parentFolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFolderContentsRow
	for rows.Next() {
		var i GetFolderContentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ItemType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFoldersByProjectID = `-- name: GetFoldersByProjectID :many
SELECT id, project_id, parent_folder_id, name, created_at, updated_at
FROM folders
WHERE project_id = $1
ORDER BY name
`

func (q *Queries) GetFoldersByProjectID(ctx context.Context, projectID pgtype.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, getFoldersByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentFolderID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIndexedFiles = `-- name: GetIndexedFiles :many
SELECT f.id, f.folder_id, f.project_id, f.name, f.size, f.created_at, f.updated_at
FROM files f
JOIN file_properties fp
ON f.id = fp.file_id
WHERE fp.is_indexed = TRUE
  AND f.project_id = $1
`

func (q *Queries) GetIndexedFiles(ctx context.Context, projectID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, getIndexedFiles, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.ProjectID,
			&i.Name,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageFileReferences = `-- name: GetMessageFileReferences :many
SELECT f.id, f.folder_id, f.project_id, f.name, f.size, f.created_at, f.updated_at
FROM files f
JOIN message_file_references mfr
ON f.id = mfr.file_id
WHERE mfr.message_id = $1
ORDER BY f.name
`

func (q *Queries) GetMessageFileReferences(ctx context.Context, messageID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, getMessageFileReferences, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.ProjectID,
			&i.Name,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesReferencingFile = `-- name: GetMessagesReferencingFile :many
SELECT cm.id, cm.chat_id, cm.sender_id, cm.role, cm.content, cm.created_at, cm.updated_at
FROM chat_messages cm
JOIN message_file_references mfr
ON cm.id = mfr.message_id
WHERE mfr.file_id = $1
ORDER BY cm.created_at ASC
`

func (q *Queries) GetMessagesReferencingFile(ctx context.Context, fileID pgtype.UUID) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, getMessagesReferencingFile, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectFile = `-- name: GetProjectFile :one
SELECT project_id, file_id, folder_id, created_at
FROM project_files
WHERE project_id = $1
  AND file_id = $2
`

type GetProjectFileParams struct {
	ProjectID pgtype.UUID
	FileID    pgtype.UUID
}

func (q *Queries) GetProjectFile(ctx context.Context, arg GetProjectFileParams) (ProjectFile, error) {
	row := q.db.QueryRow(ctx, getProjectFile, arg.ProjectID, arg.FileID)
	var i ProjectFile
	err := row.Scan(
		&i.ProjectID,
		&i.FileID,
		&i.FolderID,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectFileByFolderAndName = `-- name: GetProjectFileByFolderAndName :one
SELECT f.id, f.folder_id, f.project_id, f.name, f.size, f.created_at, f.updated_at
FROM files f
WHERE f.project_id = $1
  AND f.folder_id IS NOT DISTINCT FROM $2
  AND f.name = $3
`

type GetProjectFileByFolderAndNameParams struct {
	ProjectID pgtype.UUID
	FolderID  pgtype.UUID
	Name      string
}

func (q *Queries) GetProjectFileByFolderAndName(ctx context.Context, arg GetProjectFileByFolderAndNameParams) (File, error) {
	row := q.db.QueryRow(ctx, getProjectFileByFolderAndName, arg.ProjectID, arg.FolderID, arg.Name)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.ProjectID,
		&i.Name,
		&i.Size,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectFileByID = `-- name: GetProjectFileByID :one
SELECT f.id, f.folder_id, f.project_id, f.name, f.size, f.created_at, f.updated_at
FROM files f
WHERE f.id = $1
  AND f.project_id = $2
`

type GetProjectFileByIDParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
}

func (q *Queries) GetProjectFileByID(ctx context.Context, arg GetProjectFileByIDParams) (File, error) {
	row := q.db.QueryRow(ctx, getProjectFileByID, arg.ID, arg.ProjectID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.ProjectID,
		&i.Name,
		&i.Size,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectFilesByFolderID = `-- name: GetProjectFilesByFolderID :many
SELECT f.id, f.folder_id, f.project_id, f.name, f.size, f.created_at, f.updated_at
FROM files f
WHERE f.project_id = $1
  AND f.folder_id IS NOT DISTINCT FROM $2
ORDER BY f.name
`

type GetProjectFilesByFolderIDParams struct {
	ProjectID pgtype.UUID
	FolderID  pgtype.UUID
}

func (q *Queries) GetProjectFilesByFolderID(ctx context.Context, arg GetProjectFilesByFolderIDParams) ([]File, error) {
	rows, err := q.db.Query(ctx, getProjectFilesByFolderID, arg.ProjectID, arg.FolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.ProjectID,
			&i.Name,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectFolderByID = `-- name: GetProjectFolderByID :one
SELECT id, project_id, parent_folder_id, name, created_at, updated_at
FROM folders
WHERE id = $1
  AND project_id = $2
`

type GetProjectFolderByIDParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
}

func (q *Queries) GetProjectFolderByID(ctx context.Context, arg GetProjectFolderByIDParams) (Folder, error) {
	row := q.db.QueryRow(ctx, getProjectFolderByID, arg.ID, arg.ProjectID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentFolderID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectFolderContents = `-- name: GetProjectFolderContents :many
SELECT
    f.id,
    f.name,
    'folder' AS item_type,
    f.created_at
FROM folders f
WHERE f.project_id = $1
  AND f.parent_folder_id IS NOT DISTINCT FROM $2
UNION ALL
SELECT
    fi.id,
    fi.name,
    'file' AS item_type,
    fi.created_at
FROM files fi
WHERE fi.project_id = $1
  AND fi.folder_id IS NOT DISTINCT FROM $2
ORDER BY item_type, name
`

type GetProjectFolderContentsParams struct {
	ProjectID      pgtype.UUID
	ParentFolderID pgtype.UUID
}

type GetProjectFolderContentsRow struct {
	ID        pgtype.UUID
	Name      string
	ItemType  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetProjectFolderContents(ctx context.Context, arg GetProjectFolderContentsParams) ([]GetProjectFolderContentsRow, error) {
	rows, err := q.db.Query(ctx, getProjectFolderContents, arg.ProjectID, arg.ParentFolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectFolderContentsRow
	for rows.Next() {
		var i GetProjectFolderContentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ItemType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRootFiles = `-- name: GetRootFiles :many
SELECT f.id, f.folder_id, f.project_id, f.name, f.size, f.created_at, f.updated_at
FROM files f
WHERE f.project_id = $1
  AND f.folder_id IS NULL
ORDER BY f.name
`

func (q *Queries) GetRootFiles(ctx context.Context, projectID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, getRootFiles, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.ProjectID,
			&i.Name,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRootFolders = `-- name: GetRootFolders :many
SELECT id, project_id, parent_folder_id, name, created_at, updated_at
FROM folders
WHERE project_id = $1
  AND parent_folder_id IS NULL
ORDER BY name
`

func (q *Queries) GetRootFolders(ctx context.Context, projectID pgtype.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, getRootFolders, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentFolderID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStandaloneRootFolders = `-- name: GetStandaloneRootFolders :many
SELECT id, project_id, parent_folder_id, name, created_at, updated_at
FROM folders
WHERE project_id IS NULL
  AND parent_folder_id IS NULL
ORDER BY name
`

func (q *Queries) GetStandaloneRootFolders(ctx context.Context) ([]Folder, error) {
	rows, err := q.db.Query(ctx, getStandaloneRootFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentFolderID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFilePreference = `-- name: GetUserFilePreference :one
SELECT user_id, file_id, is_favorite, created_at, updated_at
FROM user_file_preferences
WHERE user_id = $1
  AND file_id = $2
`

type GetUserFilePreferenceParams struct {
	UserID pgtype.UUID
	FileID pgtype.UUID
}

func (q *Queries) GetUserFilePreference(ctx context.Context, arg GetUserFilePreferenceParams) (UserFilePreference, error) {
	row := q.db.QueryRow(ctx, getUserFilePreference, arg.UserID, arg.FileID)
	var i UserFilePreference
	err := row.Scan(
		&i.UserID,
		&i.FileID,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFileEmbeddingSynced = `-- name: MarkFileEmbeddingSynced :one
UPDATE file_ai_metadata
SET
    embedding_synced = $2,
    indexed_at = $3,
    updated_at = NOW()
WHERE file_id = $1
RETURNING file_id, extracted_text, embedding_model, embedding_synced, indexed_at, created_at, updated_at
`

type MarkFileEmbeddingSyncedParams struct {
	FileID          pgtype.UUID
	EmbeddingSynced pgtype.Bool
	IndexedAt       pgtype.Timestamptz
}

func (q *Queries) MarkFileEmbeddingSynced(ctx context.Context, arg MarkFileEmbeddingSyncedParams) (FileAiMetadatum, error) {
	row := q.db.QueryRow(ctx, markFileEmbeddingSynced, arg.FileID, arg.EmbeddingSynced, arg.IndexedAt)
	var i FileAiMetadatum
	err := row.Scan(
		&i.FileID,
		&i.ExtractedText,
		&i.EmbeddingModel,
		&i.EmbeddingSynced,
		&i.IndexedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFileIndexed = `-- name: MarkFileIndexed :exec
UPDATE file_properties
SET
    is_indexed = $2,
    updated_at = NOW()
WHERE file_id = $1
`

type MarkFileIndexedParams struct {
	FileID    pgtype.UUID
	IsIndexed bool
}

func (q *Queries) MarkFileIndexed(ctx context.Context, arg MarkFileIndexedParams) error {
	_, err := q.db.Exec(ctx, markFileIndexed, arg.FileID, arg.IsIndexed)
	return err
}

const moveFile = `-- name: MoveFile :one
UPDATE files
SET
    folder_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, folder_id, project_id, name, size, created_at, updated_at
`

type MoveFileParams struct {
	ID       pgtype.UUID
	FolderID pgtype.UUID
}

func (q *Queries) MoveFile(ctx context.Context, arg MoveFileParams) (File, error) {
	row := q.db.QueryRow(ctx, moveFile, arg.ID, arg.FolderID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.ProjectID,
		&i.Name,
		&i.Size,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const moveFolder = `-- name: MoveFolder :one
UPDATE folders
SET
    parent_folder_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, parent_folder_id, name, created_at, updated_at
`

type MoveFolderParams struct {
	ID             pgtype.UUID
	ParentFolderID pgtype.UUID
}

func (q *Queries) MoveFolder(ctx context.Context, arg MoveFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, moveFolder, arg.ID, arg.ParentFolderID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentFolderID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const moveProjectFile = `-- name: MoveProjectFile :one
UPDATE project_files
SET
    folder_id = $3
WHERE project_id = $1
  AND file_id = $2
RETURNING project_id, file_id, folder_id, created_at
`

type MoveProjectFileParams struct {
	ProjectID pgtype.UUID
	FileID    pgtype.UUID
	FolderID  pgtype.UUID
}

func (q *Queries) MoveProjectFile(ctx context.Context, arg MoveProjectFileParams) (ProjectFile, error) {
	row := q.db.QueryRow(ctx, moveProjectFile, arg.ProjectID, arg.FileID, arg.FolderID)
	var i ProjectFile
	err := row.Scan(
		&i.ProjectID,
		&i.FileID,
		&i.FolderID,
		&i.CreatedAt,
	)
	return i, err
}

const removeProjectFile = `-- name: RemoveProjectFile :exec
DELETE
FROM project_files
WHERE project_id = $1
  AND file_id = $2
`

type RemoveProjectFileParams struct {
	ProjectID pgtype.UUID
	FileID    pgtype.UUID
}

func (q *Queries) RemoveProjectFile(ctx context.Context, arg RemoveProjectFileParams) error {
	_, err := q.db.Exec(ctx, removeProjectFile, arg.ProjectID, arg.FileID)
	return err
}

const renameFile = `-- name: RenameFile :one
UPDATE files
SET
    name = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, folder_id, project_id, name, size, created_at, updated_at
`

type RenameFileParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) RenameFile(ctx context.Context, arg RenameFileParams) (File, error) {
	row := q.db.QueryRow(ctx, renameFile, arg.ID, arg.Name)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.ProjectID,
		&i.Name,
		&i.Size,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const renameFolder = `-- name: RenameFolder :one
UPDATE folders
SET
    name = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, parent_folder_id, name, created_at, updated_at
`

type RenameFolderParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) RenameFolder(ctx context.Context, arg RenameFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, renameFolder, arg.ID, arg.Name)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentFolderID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const restoreFile = `-- name: RestoreFile :exec
UPDATE file_properties
SET
    deleted_at = NULL,
    updated_at = NOW()
WHERE file_id = $1
`

func (q *Queries) RestoreFile(ctx context.Context, fileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restoreFile, fileID)
	return err
}

const searchFiles = `-- name: SearchFiles :many
SELECT f.id, f.folder_id, f.project_id, f.name, f.size, f.created_at, f.updated_at
FROM files f
WHERE f.project_id = $1
  AND f.name ILIKE '%' || $2 || '%'
ORDER BY f.name
`

type SearchFilesParams struct {
	ProjectID pgtype.UUID
	Column2   pgtype.Text
}

func (q *Queries) SearchFiles(ctx context.Context, arg SearchFilesParams) ([]File, error) {
	rows, err := q.db.Query(ctx, searchFiles, arg.ProjectID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.ProjectID,
			&i.Name,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFolders = `-- name: SearchFolders :many
SELECT id, project_id, parent_folder_id, name, created_at, updated_at
FROM folders
WHERE project_id = $1
  AND name ILIKE '%' || $2 || '%'
ORDER BY name
`

type SearchFoldersParams struct {
	ProjectID pgtype.UUID
	Column2   pgtype.Text
}

func (q *Queries) SearchFolders(ctx context.Context, arg SearchFoldersParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, searchFolders, arg.ProjectID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentFolderID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchStandaloneFolders = `-- name: SearchStandaloneFolders :many
SELECT id, project_id, parent_folder_id, name, created_at, updated_at
FROM folders
WHERE project_id IS NULL
  AND name ILIKE '%' || $1 || '%'
ORDER BY name
`

func (q *Queries) SearchStandaloneFolders(ctx context.Context, dollar_1 pgtype.Text) ([]Folder, error) {
	rows, err := q.db.Query(ctx, searchStandaloneFolders, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentFolderID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFavorite = `-- name: SetFavorite :one
INSERT INTO user_file_preferences (
    user_id,
    file_id,
    is_favorite
)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, file_id)
DO UPDATE SET
    is_favorite = EXCLUDED.is_favorite,
    updated_at = NOW()
RETURNING user_id, file_id, is_favorite, created_at, updated_at
`

type SetFavoriteParams struct {
	UserID     pgtype.UUID
	FileID     pgtype.UUID
	IsFavorite bool
}

func (q *Queries) SetFavorite(ctx context.Context, arg SetFavoriteParams) (UserFilePreference, error) {
	row := q.db.QueryRow(ctx, setFavorite, arg.UserID, arg.FileID, arg.IsFavorite)
	var i UserFilePreference
	err := row.Scan(
		&i.UserID,
		&i.FileID,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteFile = `-- name: SoftDeleteFile :exec
UPDATE file_properties
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE file_id = $1
`

func (q *Queries) SoftDeleteFile(ctx context.Context, fileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteFile, fileID)
	return err
}

const updateFileAIMetadata = `-- name: UpdateFileAIMetadata :one
UPDATE file_ai_metadata
SET
    extracted_text = $2,
    embedding_model = $3,
    embedding_synced = $4,
    indexed_at = $5,
    updated_at = NOW()
WHERE file_id = $1
RETURNING file_id, extracted_text, embedding_model, embedding_synced, indexed_at, created_at, updated_at
`

type UpdateFileAIMetadataParams struct {
	FileID          pgtype.UUID
	ExtractedText   pgtype.Text
	EmbeddingModel  pgtype.Text
	EmbeddingSynced pgtype.Bool
	IndexedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateFileAIMetadata(ctx context.Context, arg UpdateFileAIMetadataParams) (FileAiMetadatum, error) {
	row := q.db.QueryRow(ctx, updateFileAIMetadata,
		arg.FileID,
		arg.ExtractedText,
		arg.EmbeddingModel,
		arg.EmbeddingSynced,
		arg.IndexedAt,
	)
	var i FileAiMetadatum
	err := row.Scan(
		&i.FileID,
		&i.ExtractedText,
		&i.EmbeddingModel,
		&i.EmbeddingSynced,
		&i.IndexedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFileProperties = `-- name: UpdateFileProperties :one
UPDATE file_properties
SET
    original_name = $2,
    is_indexed = $3,
    deleted_at = $4,
    updated_at = NOW()
WHERE file_id = $1
RETURNING file_id, original_name, is_indexed, created_at, updated_at, deleted_at
`

type UpdateFilePropertiesParams struct {
	FileID       pgtype.UUID
	OriginalName pgtype.Text
	IsIndexed    bool
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateFileProperties(ctx context.Context, arg UpdateFilePropertiesParams) (FileProperty, error) {
	row := q.db.QueryRow(ctx, updateFileProperties,
		arg.FileID,
		arg.OriginalName,
		arg.IsIndexed,
		arg.DeletedAt,
	)
	var i FileProperty
	err := row.Scan(
		&i.FileID,
		&i.OriginalName,
		&i.IsIndexed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateFilePropertiesOriginalName = `-- name: UpdateFilePropertiesOriginalName :one
UPDATE file_properties
SET
    original_name = $2,
    updated_at = NOW()
WHERE file_id = $1
RETURNING file_id, original_name, is_indexed, created_at, updated_at, deleted_at
`

type UpdateFilePropertiesOriginalNameParams struct {
	FileID       pgtype.UUID
	OriginalName pgtype.Text
}

func (q *Queries) UpdateFilePropertiesOriginalName(ctx context.Context, arg UpdateFilePropertiesOriginalNameParams) (FileProperty, error) {
	row := q.db.QueryRow(ctx, updateFilePropertiesOriginalName, arg.FileID, arg.OriginalName)
	var i FileProperty
	err := row.Scan(
		&i.FileID,
		&i.OriginalName,
		&i.IsIndexed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateFileSharePermission = `-- name: UpdateFileSharePermission :one
UPDATE file_shares
SET
    permission = $2
WHERE id = $1
RETURNING id, file_id, shared_by, shared_with, permission, created_at
`

type UpdateFileSharePermissionParams struct {
	ID         pgtype.UUID
	Permission FilePermission
}

func (q *Queries) UpdateFileSharePermission(ctx context.Context, arg UpdateFileSharePermissionParams) (FileShare, error) {
	row := q.db.QueryRow(ctx, updateFileSharePermission, arg.ID, arg.Permission)
	var i FileShare
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.SharedBy,
		&i.SharedWith,
		&i.Permission,
		&i.CreatedAt,
	)
	return i, err
}

const updateFileSize = `-- name: UpdateFileSize :one
UPDATE files
SET
    size = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, folder_id, project_id, name, size, created_at, updated_at
`

type UpdateFileSizeParams struct {
	ID   pgtype.UUID
	Size int64
}

func (q *Queries) UpdateFileSize(ctx context.Context, arg UpdateFileSizeParams) (File, error) {
	row := q.db.QueryRow(ctx, updateFileSize, arg.ID, arg.Size)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FolderID,
		&i.ProjectID,
		&i.Name,
		&i.Size,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFileStorage = `-- name: UpdateFileStorage :one
UPDATE file_storage
SET
    bucket_name = $2,
    object_key = $3,
    etag = $4,
    version_id = $5,
    checksum = $6,
    mime_type = $7,
    uploaded_by = $8,
    updated_at = NOW()
WHERE file_id = $1
RETURNING file_id, bucket_name, object_key, etag, version_id, checksum, mime_type, created_at, updated_at, uploaded_by
`

type UpdateFileStorageParams struct {
	FileID     pgtype.UUID
	BucketName string
	ObjectKey  string
	Etag       pgtype.Text
	VersionID  pgtype.Text
	Checksum   pgtype.Text
	MimeType   string
	UploadedBy pgtype.UUID
}

func (q *Queries) UpdateFileStorage(ctx context.Context, arg UpdateFileStorageParams) (FileStorage, error) {
	row := q.db.QueryRow(ctx, updateFileStorage,
		arg.FileID,
		arg.BucketName,
		arg.ObjectKey,
		arg.Etag,
		arg.VersionID,
		arg.Checksum,
		arg.MimeType,
		arg.UploadedBy,
	)
	var i FileStorage
	err := row.Scan(
		&i.FileID,
		&i.BucketName,
		&i.ObjectKey,
		&i.Etag,
		&i.VersionID,
		&i.Checksum,
		&i.MimeType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UploadedBy,
	)
	return i, err
}
