// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkFileNameExists = `-- name: CheckFileNameExists :one
SELECT EXISTS (
    SELECT 1
    FROM files
    WHERE project_id = $1
      AND folder_id IS NOT DISTINCT FROM $2
      AND name = $3
)
`

type CheckFileNameExistsParams struct {
	ProjectID pgtype.UUID
	FolderID  pgtype.UUID
	Name      string
}

func (q *Queries) CheckFileNameExists(ctx context.Context, arg CheckFileNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkFileNameExists, arg.ProjectID, arg.FolderID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkFolderNameExists = `-- name: CheckFolderNameExists :one
SELECT EXISTS (
    SELECT 1
    FROM folders
    WHERE project_id = $1
      AND parent_folder_id IS NOT DISTINCT FROM $2
      AND name = $3
)
`

type CheckFolderNameExistsParams struct {
	ProjectID      pgtype.UUID
	ParentFolderID pgtype.UUID
	Name           string
}

func (q *Queries) CheckFolderNameExists(ctx context.Context, arg CheckFolderNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkFolderNameExists, arg.ProjectID, arg.ParentFolderID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (
    id,
    project_id,
    folder_id,
    name,
    size
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, folder_id, name, size, created_at, updated_at
`

type CreateFileParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	FolderID  pgtype.UUID
	Name      string
	Size      int64
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.ID,
		arg.ProjectID,
		arg.FolderID,
		arg.Name,
		arg.Size,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Name,
		&i.Size,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFileAIMetadata = `-- name: CreateFileAIMetadata :one
INSERT INTO file_ai_metadata (
    file_id,
    extracted_text,
    embedding_model,
    embedding_synced,
    indexed_at
)
VALUES ($1, $2, $3, $4, $5)
RETURNING file_id, extracted_text, embedding_model, embedding_synced, indexed_at, created_at, updated_at
`

type CreateFileAIMetadataParams struct {
	FileID          pgtype.UUID
	ExtractedText   pgtype.Text
	EmbeddingModel  pgtype.Text
	EmbeddingSynced pgtype.Bool
	IndexedAt       pgtype.Timestamptz
}

func (q *Queries) CreateFileAIMetadata(ctx context.Context, arg CreateFileAIMetadataParams) (FileAiMetadatum, error) {
	row := q.db.QueryRow(ctx, createFileAIMetadata,
		arg.FileID,
		arg.ExtractedText,
		arg.EmbeddingModel,
		arg.EmbeddingSynced,
		arg.IndexedAt,
	)
	var i FileAiMetadatum
	err := row.Scan(
		&i.FileID,
		&i.ExtractedText,
		&i.EmbeddingModel,
		&i.EmbeddingSynced,
		&i.IndexedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFileProperties = `-- name: CreateFileProperties :one
INSERT INTO file_properties (
    file_id,
    original_name,
    is_indexed,
    is_favorite,
    deleted_at
)
VALUES ($1, $2, $3, $4, $5)
RETURNING file_id, original_name, is_indexed, is_favorite, created_at, updated_at, deleted_at
`

type CreateFilePropertiesParams struct {
	FileID       pgtype.UUID
	OriginalName pgtype.Text
	IsIndexed    bool
	IsFavorite   pgtype.Bool
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) CreateFileProperties(ctx context.Context, arg CreateFilePropertiesParams) (FileProperty, error) {
	row := q.db.QueryRow(ctx, createFileProperties,
		arg.FileID,
		arg.OriginalName,
		arg.IsIndexed,
		arg.IsFavorite,
		arg.DeletedAt,
	)
	var i FileProperty
	err := row.Scan(
		&i.FileID,
		&i.OriginalName,
		&i.IsIndexed,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createFileStorage = `-- name: CreateFileStorage :one
INSERT INTO file_storage (
    file_id,
    bucket_name,
    object_key,
    etag,
    version_id,
    checksum,
    mime_type,
    uploaded_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING file_id, bucket_name, object_key, etag, version_id, checksum, mime_type, created_at, updated_at, uploaded_by
`

type CreateFileStorageParams struct {
	FileID     pgtype.UUID
	BucketName string
	ObjectKey  string
	Etag       pgtype.Text
	VersionID  pgtype.Text
	Checksum   pgtype.Text
	MimeType   string
	UploadedBy pgtype.UUID
}

func (q *Queries) CreateFileStorage(ctx context.Context, arg CreateFileStorageParams) (FileStorage, error) {
	row := q.db.QueryRow(ctx, createFileStorage,
		arg.FileID,
		arg.BucketName,
		arg.ObjectKey,
		arg.Etag,
		arg.VersionID,
		arg.Checksum,
		arg.MimeType,
		arg.UploadedBy,
	)
	var i FileStorage
	err := row.Scan(
		&i.FileID,
		&i.BucketName,
		&i.ObjectKey,
		&i.Etag,
		&i.VersionID,
		&i.Checksum,
		&i.MimeType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UploadedBy,
	)
	return i, err
}

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (
    id,
    project_id,
    parent_folder_id,
    name
)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, parent_folder_id, name, created_at, updated_at
`

type CreateFolderParams struct {
	ID             pgtype.UUID
	ProjectID      pgtype.UUID
	ParentFolderID pgtype.UUID
	Name           string
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder,
		arg.ID,
		arg.ProjectID,
		arg.ParentFolderID,
		arg.Name,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentFolderID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE
FROM files
WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const deleteFileAIMetadata = `-- name: DeleteFileAIMetadata :exec
DELETE
FROM file_ai_metadata
WHERE file_id = $1
`

func (q *Queries) DeleteFileAIMetadata(ctx context.Context, fileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFileAIMetadata, fileID)
	return err
}

const deleteFileProperties = `-- name: DeleteFileProperties :exec
DELETE
FROM file_properties
WHERE file_id = $1
`

func (q *Queries) DeleteFileProperties(ctx context.Context, fileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFileProperties, fileID)
	return err
}

const deleteFileShare = `-- name: DeleteFileShare :exec
DELETE
FROM file_shares
WHERE id = $1
`

func (q *Queries) DeleteFileShare(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFileShare, id)
	return err
}

const deleteFileStorage = `-- name: DeleteFileStorage :exec
DELETE
FROM file_storage
WHERE file_id = $1
`

func (q *Queries) DeleteFileStorage(ctx context.Context, fileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFileStorage, fileID)
	return err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE
FROM folders
WHERE id = $1
`

func (q *Queries) DeleteFolder(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFolder, id)
	return err
}

const fileShare = `-- name: FileShare :one
INSERT INTO file_shares (
    id,
    file_id,
    shared_by,
    shared_with,
    permission
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, file_id, shared_by, shared_with, permission, created_at
`

type FileShareParams struct {
	ID         pgtype.UUID
	FileID     pgtype.UUID
	SharedBy   pgtype.UUID
	SharedWith pgtype.UUID
	Permission FilePermission
}

func (q *Queries) FileShare(ctx context.Context, arg FileShareParams) (FileShare, error) {
	row := q.db.QueryRow(ctx, fileShare,
		arg.ID,
		arg.FileID,
		arg.SharedBy,
		arg.SharedWith,
		arg.Permission,
	)
	var i FileShare
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.SharedBy,
		&i.SharedWith,
		&i.Permission,
		&i.CreatedAt,
	)
	return i, err
}

const getChildFolders = `-- name: GetChildFolders :many
SELECT id, project_id, parent_folder_id, name, created_at, updated_at
FROM folders
WHERE parent_folder_id IS NOT DISTINCT FROM $1
ORDER BY name
`

func (q *Queries) GetChildFolders(ctx context.Context, parentFolderID pgtype.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, getChildFolders, parentFolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentFolderID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeletedFiles = `-- name: GetDeletedFiles :many
SELECT f.id, f.project_id, f.folder_id, f.name, f.size, f.created_at, f.updated_at
FROM files f
JOIN file_properties fp
ON f.id = fp.file_id
WHERE fp.deleted_at IS NOT NULL
  AND f.project_id = $1
ORDER BY fp.deleted_at DESC
`

func (q *Queries) GetDeletedFiles(ctx context.Context, projectID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, getDeletedFiles, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FolderID,
			&i.Name,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFavoritesFiles = `-- name: GetFavoritesFiles :many
SELECT f.id, f.project_id, f.folder_id, f.name, f.size, f.created_at, f.updated_at
FROM files f
JOIN file_properties fp
ON f.id = fp.file_id
WHERE fp.is_favorite = TRUE
    AND f.project_id = $1
`

func (q *Queries) GetFavoritesFiles(ctx context.Context, projectID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, getFavoritesFiles, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FolderID,
			&i.Name,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileAIMetadata = `-- name: GetFileAIMetadata :one
SELECT file_id, extracted_text, embedding_model, embedding_synced, indexed_at, created_at, updated_at
FROM file_ai_metadata
WHERE file_id = $1
`

func (q *Queries) GetFileAIMetadata(ctx context.Context, fileID pgtype.UUID) (FileAiMetadatum, error) {
	row := q.db.QueryRow(ctx, getFileAIMetadata, fileID)
	var i FileAiMetadatum
	err := row.Scan(
		&i.FileID,
		&i.ExtractedText,
		&i.EmbeddingModel,
		&i.EmbeddingSynced,
		&i.IndexedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileByFolderAndName = `-- name: GetFileByFolderAndName :one
SELECT id, project_id, folder_id, name, size, created_at, updated_at
FROM files
WHERE project_id = $1
  AND folder_id IS NOT DISTINCT FROM $2
  AND name = $3
`

type GetFileByFolderAndNameParams struct {
	ProjectID pgtype.UUID
	FolderID  pgtype.UUID
	Name      string
}

func (q *Queries) GetFileByFolderAndName(ctx context.Context, arg GetFileByFolderAndNameParams) (File, error) {
	row := q.db.QueryRow(ctx, getFileByFolderAndName, arg.ProjectID, arg.FolderID, arg.Name)
	var i File
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Name,
		&i.Size,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, project_id, folder_id, name, size, created_at, updated_at
FROM files
WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id pgtype.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Name,
		&i.Size,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileProperties = `-- name: GetFileProperties :one
SELECT file_id, original_name, is_indexed, is_favorite, created_at, updated_at, deleted_at
FROM file_properties
WHERE file_id = $1
`

func (q *Queries) GetFileProperties(ctx context.Context, fileID pgtype.UUID) (FileProperty, error) {
	row := q.db.QueryRow(ctx, getFileProperties, fileID)
	var i FileProperty
	err := row.Scan(
		&i.FileID,
		&i.OriginalName,
		&i.IsIndexed,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFileShareByFileAndSharedWith = `-- name: GetFileShareByFileAndSharedWith :one
SELECT id, file_id, shared_by, shared_with, permission, created_at
FROM file_shares
WHERE file_id = $1
  AND shared_with = $2
`

type GetFileShareByFileAndSharedWithParams struct {
	FileID     pgtype.UUID
	SharedWith pgtype.UUID
}

func (q *Queries) GetFileShareByFileAndSharedWith(ctx context.Context, arg GetFileShareByFileAndSharedWithParams) (FileShare, error) {
	row := q.db.QueryRow(ctx, getFileShareByFileAndSharedWith, arg.FileID, arg.SharedWith)
	var i FileShare
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.SharedBy,
		&i.SharedWith,
		&i.Permission,
		&i.CreatedAt,
	)
	return i, err
}

const getFileShareByID = `-- name: GetFileShareByID :one
SELECT id, file_id, shared_by, shared_with, permission, created_at
FROM file_shares
WHERE id = $1
`

func (q *Queries) GetFileShareByID(ctx context.Context, id pgtype.UUID) (FileShare, error) {
	row := q.db.QueryRow(ctx, getFileShareByID, id)
	var i FileShare
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.SharedBy,
		&i.SharedWith,
		&i.Permission,
		&i.CreatedAt,
	)
	return i, err
}

const getFileSharesByFileID = `-- name: GetFileSharesByFileID :many
SELECT id, file_id, shared_by, shared_with, permission, created_at
FROM file_shares
WHERE file_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetFileSharesByFileID(ctx context.Context, fileID pgtype.UUID) ([]FileShare, error) {
	rows, err := q.db.Query(ctx, getFileSharesByFileID, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileShare
	for rows.Next() {
		var i FileShare
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.SharedBy,
			&i.SharedWith,
			&i.Permission,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileSharesBySharedWith = `-- name: GetFileSharesBySharedWith :many
SELECT id, file_id, shared_by, shared_with, permission, created_at
FROM file_shares
WHERE shared_with = $1
ORDER BY created_at DESC
`

func (q *Queries) GetFileSharesBySharedWith(ctx context.Context, sharedWith pgtype.UUID) ([]FileShare, error) {
	rows, err := q.db.Query(ctx, getFileSharesBySharedWith, sharedWith)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileShare
	for rows.Next() {
		var i FileShare
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.SharedBy,
			&i.SharedWith,
			&i.Permission,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileStorage = `-- name: GetFileStorage :one
SELECT file_id, bucket_name, object_key, etag, version_id, checksum, mime_type, created_at, updated_at, uploaded_by
FROM file_storage
WHERE file_id = $1
`

func (q *Queries) GetFileStorage(ctx context.Context, fileID pgtype.UUID) (FileStorage, error) {
	row := q.db.QueryRow(ctx, getFileStorage, fileID)
	var i FileStorage
	err := row.Scan(
		&i.FileID,
		&i.BucketName,
		&i.ObjectKey,
		&i.Etag,
		&i.VersionID,
		&i.Checksum,
		&i.MimeType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UploadedBy,
	)
	return i, err
}

const getFilesByFolderID = `-- name: GetFilesByFolderID :many
SELECT id, project_id, folder_id, name, size, created_at, updated_at
FROM files
WHERE folder_id IS NOT DISTINCT FROM $1
ORDER BY name
`

func (q *Queries) GetFilesByFolderID(ctx context.Context, folderID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesByFolderID, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FolderID,
			&i.Name,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByIDs = `-- name: GetFilesByIDs :many
SELECT id, project_id, folder_id, name, size, created_at, updated_at
FROM files
WHERE id = ANY($1::UUID[])
ORDER BY name
`

func (q *Queries) GetFilesByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FolderID,
			&i.Name,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByProjectID = `-- name: GetFilesByProjectID :many
SELECT id, project_id, folder_id, name, size, created_at, updated_at
FROM files
WHERE project_id = $1
ORDER BY name
`

func (q *Queries) GetFilesByProjectID(ctx context.Context, projectID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FolderID,
			&i.Name,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, project_id, parent_folder_id, name, created_at, updated_at
FROM folders
WHERE id = $1
`

func (q *Queries) GetFolderByID(ctx context.Context, id pgtype.UUID) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentFolderID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolderContents = `-- name: GetFolderContents :many
SELECT
    id,
    name,
    'folder' AS item_type,
    created_at
FROM folders
WHERE parent_folder_id IS NOT DISTINCT FROM $1
UNION ALL
SELECT
    id,
    name,
    'file' AS item_type,
    created_at
FROM files
WHERE folder_id IS NOT DISTINCT FROM $1
ORDER BY item_type, name
`

type GetFolderContentsRow struct {
	ID        pgtype.UUID
	Name      string
	ItemType  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetFolderContents(ctx context.Context, parentFolderID pgtype.UUID) ([]GetFolderContentsRow, error) {
	rows, err := q.db.Query(ctx, getFolderContents, parentFolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFolderContentsRow
	for rows.Next() {
		var i GetFolderContentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ItemType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFoldersByProjectID = `-- name: GetFoldersByProjectID :many
SELECT id, project_id, parent_folder_id, name, created_at, updated_at
FROM folders
WHERE project_id = $1
ORDER BY name
`

func (q *Queries) GetFoldersByProjectID(ctx context.Context, projectID pgtype.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, getFoldersByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentFolderID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIndexedFiles = `-- name: GetIndexedFiles :many
SELECT f.id, f.project_id, f.folder_id, f.name, f.size, f.created_at, f.updated_at
FROM files f
JOIN file_properties fp
ON f.id = fp.file_id
WHERE fp.is_indexed = TRUE
    AND f.project_id = $1
`

func (q *Queries) GetIndexedFiles(ctx context.Context, projectID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, getIndexedFiles, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FolderID,
			&i.Name,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectFileByID = `-- name: GetProjectFileByID :one
SELECT id, project_id, folder_id, name, size, created_at, updated_at
FROM files
WHERE id = $1
  AND project_id = $2
`

type GetProjectFileByIDParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
}

func (q *Queries) GetProjectFileByID(ctx context.Context, arg GetProjectFileByIDParams) (File, error) {
	row := q.db.QueryRow(ctx, getProjectFileByID, arg.ID, arg.ProjectID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Name,
		&i.Size,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectFolderByID = `-- name: GetProjectFolderByID :one
SELECT id, project_id, parent_folder_id, name, created_at, updated_at
FROM folders
WHERE id = $1
  AND project_id = $2
`

type GetProjectFolderByIDParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
}

func (q *Queries) GetProjectFolderByID(ctx context.Context, arg GetProjectFolderByIDParams) (Folder, error) {
	row := q.db.QueryRow(ctx, getProjectFolderByID, arg.ID, arg.ProjectID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentFolderID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRootFiles = `-- name: GetRootFiles :many
SELECT id, project_id, folder_id, name, size, created_at, updated_at
FROM files
WHERE project_id = $1
  AND folder_id IS NULL
ORDER BY name
`

func (q *Queries) GetRootFiles(ctx context.Context, projectID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, getRootFiles, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FolderID,
			&i.Name,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRootFolders = `-- name: GetRootFolders :many
SELECT id, project_id, parent_folder_id, name, created_at, updated_at
FROM folders
WHERE project_id = $1
  AND parent_folder_id IS NULL
ORDER BY name
`

func (q *Queries) GetRootFolders(ctx context.Context, projectID pgtype.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, getRootFolders, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentFolderID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFileIndexed = `-- name: MarkFileIndexed :exec
UPDATE file_properties
SET
    is_indexed = $2,
    updated_at = NOW()
WHERE file_id = $1
`

type MarkFileIndexedParams struct {
	FileID    pgtype.UUID
	IsIndexed bool
}

func (q *Queries) MarkFileIndexed(ctx context.Context, arg MarkFileIndexedParams) error {
	_, err := q.db.Exec(ctx, markFileIndexed, arg.FileID, arg.IsIndexed)
	return err
}

const moveFile = `-- name: MoveFile :one
UPDATE files
SET
    folder_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, folder_id, name, size, created_at, updated_at
`

type MoveFileParams struct {
	ID       pgtype.UUID
	FolderID pgtype.UUID
}

func (q *Queries) MoveFile(ctx context.Context, arg MoveFileParams) (File, error) {
	row := q.db.QueryRow(ctx, moveFile, arg.ID, arg.FolderID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Name,
		&i.Size,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const moveFolder = `-- name: MoveFolder :one
UPDATE folders
SET
    parent_folder_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, parent_folder_id, name, created_at, updated_at
`

type MoveFolderParams struct {
	ID             pgtype.UUID
	ParentFolderID pgtype.UUID
}

func (q *Queries) MoveFolder(ctx context.Context, arg MoveFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, moveFolder, arg.ID, arg.ParentFolderID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentFolderID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const renameFile = `-- name: RenameFile :one
UPDATE files
SET
    name = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, folder_id, name, size, created_at, updated_at
`

type RenameFileParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) RenameFile(ctx context.Context, arg RenameFileParams) (File, error) {
	row := q.db.QueryRow(ctx, renameFile, arg.ID, arg.Name)
	var i File
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Name,
		&i.Size,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const renameFolder = `-- name: RenameFolder :one
UPDATE folders
SET
    name = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, parent_folder_id, name, created_at, updated_at
`

type RenameFolderParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) RenameFolder(ctx context.Context, arg RenameFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, renameFolder, arg.ID, arg.Name)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentFolderID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const restoreFile = `-- name: RestoreFile :exec
UPDATE file_properties
SET
    deleted_at = NULL,
    updated_at = NOW()
WHERE file_id = $1
`

func (q *Queries) RestoreFile(ctx context.Context, fileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restoreFile, fileID)
	return err
}

const searchFiles = `-- name: SearchFiles :many
SELECT id, project_id, folder_id, name, size, created_at, updated_at
FROM files
WHERE project_id = $1
  AND name ILIKE '%' || $2 || '%'
ORDER BY name
`

type SearchFilesParams struct {
	ProjectID pgtype.UUID
	Column2   pgtype.Text
}

func (q *Queries) SearchFiles(ctx context.Context, arg SearchFilesParams) ([]File, error) {
	rows, err := q.db.Query(ctx, searchFiles, arg.ProjectID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FolderID,
			&i.Name,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFolders = `-- name: SearchFolders :many
SELECT id, project_id, parent_folder_id, name, created_at, updated_at
FROM folders
WHERE project_id = $1
  AND name ILIKE '%' || $2 || '%'
ORDER BY name
`

type SearchFoldersParams struct {
	ProjectID pgtype.UUID
	Column2   pgtype.Text
}

func (q *Queries) SearchFolders(ctx context.Context, arg SearchFoldersParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, searchFolders, arg.ProjectID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentFolderID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFavorite = `-- name: SetFavorite :exec
UPDATE file_properties
SET
    is_favorite = $2,
    updated_at = NOW()
WHERE file_id = $1
`

type SetFavoriteParams struct {
	FileID     pgtype.UUID
	IsFavorite pgtype.Bool
}

func (q *Queries) SetFavorite(ctx context.Context, arg SetFavoriteParams) error {
	_, err := q.db.Exec(ctx, setFavorite, arg.FileID, arg.IsFavorite)
	return err
}

const softDeleteFile = `-- name: SoftDeleteFile :exec
UPDATE file_properties
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE file_id = $1
`

func (q *Queries) SoftDeleteFile(ctx context.Context, fileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteFile, fileID)
	return err
}

const updateFileAIMetadata = `-- name: UpdateFileAIMetadata :one
UPDATE file_ai_metadata
SET
    extracted_text = $2,
    embedding_model = $3,
    embedding_synced = $4,
    indexed_at = $5,
    updated_at = NOW()
WHERE file_id = $1
RETURNING file_id, extracted_text, embedding_model, embedding_synced, indexed_at, created_at, updated_at
`

type UpdateFileAIMetadataParams struct {
	FileID          pgtype.UUID
	ExtractedText   pgtype.Text
	EmbeddingModel  pgtype.Text
	EmbeddingSynced pgtype.Bool
	IndexedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateFileAIMetadata(ctx context.Context, arg UpdateFileAIMetadataParams) (FileAiMetadatum, error) {
	row := q.db.QueryRow(ctx, updateFileAIMetadata,
		arg.FileID,
		arg.ExtractedText,
		arg.EmbeddingModel,
		arg.EmbeddingSynced,
		arg.IndexedAt,
	)
	var i FileAiMetadatum
	err := row.Scan(
		&i.FileID,
		&i.ExtractedText,
		&i.EmbeddingModel,
		&i.EmbeddingSynced,
		&i.IndexedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFileProperties = `-- name: UpdateFileProperties :one
UPDATE file_properties
SET
    original_name = $2,
    is_indexed = $3,
    is_favorite = $4,
    deleted_at = $5,
    updated_at = NOW()
WHERE file_id = $1
RETURNING file_id, original_name, is_indexed, is_favorite, created_at, updated_at, deleted_at
`

type UpdateFilePropertiesParams struct {
	FileID       pgtype.UUID
	OriginalName pgtype.Text
	IsIndexed    bool
	IsFavorite   pgtype.Bool
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateFileProperties(ctx context.Context, arg UpdateFilePropertiesParams) (FileProperty, error) {
	row := q.db.QueryRow(ctx, updateFileProperties,
		arg.FileID,
		arg.OriginalName,
		arg.IsIndexed,
		arg.IsFavorite,
		arg.DeletedAt,
	)
	var i FileProperty
	err := row.Scan(
		&i.FileID,
		&i.OriginalName,
		&i.IsIndexed,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateFilePropertiesOriginalName = `-- name: UpdateFilePropertiesOriginalName :one
UPDATE file_properties
SET
    original_name = $2,
    updated_at = NOW()
WHERE file_id = $1
RETURNING file_id, original_name, is_indexed, is_favorite, created_at, updated_at, deleted_at
`

type UpdateFilePropertiesOriginalNameParams struct {
	FileID       pgtype.UUID
	OriginalName pgtype.Text
}

func (q *Queries) UpdateFilePropertiesOriginalName(ctx context.Context, arg UpdateFilePropertiesOriginalNameParams) (FileProperty, error) {
	row := q.db.QueryRow(ctx, updateFilePropertiesOriginalName, arg.FileID, arg.OriginalName)
	var i FileProperty
	err := row.Scan(
		&i.FileID,
		&i.OriginalName,
		&i.IsIndexed,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateFileSharePermission = `-- name: UpdateFileSharePermission :one
UPDATE file_shares
SET
    permission = $2
WHERE id = $1
RETURNING id, file_id, shared_by, shared_with, permission, created_at
`

type UpdateFileSharePermissionParams struct {
	ID         pgtype.UUID
	Permission FilePermission
}

func (q *Queries) UpdateFileSharePermission(ctx context.Context, arg UpdateFileSharePermissionParams) (FileShare, error) {
	row := q.db.QueryRow(ctx, updateFileSharePermission, arg.ID, arg.Permission)
	var i FileShare
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.SharedBy,
		&i.SharedWith,
		&i.Permission,
		&i.CreatedAt,
	)
	return i, err
}

const updateFileSize = `-- name: UpdateFileSize :one
UPDATE files
SET
    size = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, folder_id, name, size, created_at, updated_at
`

type UpdateFileSizeParams struct {
	ID   pgtype.UUID
	Size int64
}

func (q *Queries) UpdateFileSize(ctx context.Context, arg UpdateFileSizeParams) (File, error) {
	row := q.db.QueryRow(ctx, updateFileSize, arg.ID, arg.Size)
	var i File
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Name,
		&i.Size,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFileStorage = `-- name: UpdateFileStorage :one
UPDATE file_storage
SET
    bucket_name = $2,
    object_key = $3,
    etag = $4,
    version_id = $5,
    checksum = $6,
    mime_type = $7,
    uploaded_by = $8,
    updated_at = NOW()
WHERE file_id = $1
RETURNING file_id, bucket_name, object_key, etag, version_id, checksum, mime_type, created_at, updated_at, uploaded_by
`

type UpdateFileStorageParams struct {
	FileID     pgtype.UUID
	BucketName string
	ObjectKey  string
	Etag       pgtype.Text
	VersionID  pgtype.Text
	Checksum   pgtype.Text
	MimeType   string
	UploadedBy pgtype.UUID
}

func (q *Queries) UpdateFileStorage(ctx context.Context, arg UpdateFileStorageParams) (FileStorage, error) {
	row := q.db.QueryRow(ctx, updateFileStorage,
		arg.FileID,
		arg.BucketName,
		arg.ObjectKey,
		arg.Etag,
		arg.VersionID,
		arg.Checksum,
		arg.MimeType,
		arg.UploadedBy,
	)
	var i FileStorage
	err := row.Scan(
		&i.FileID,
		&i.BucketName,
		&i.ObjectKey,
		&i.Etag,
		&i.VersionID,
		&i.Checksum,
		&i.MimeType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UploadedBy,
	)
	return i, err
}
