// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: flowcharts.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFlowchart = `-- name: CreateFlowchart :one
INSERT INTO flowcharts (
    project_id,
    name,
    data,
    generated_by,
    generated_by_ai,
    status,
    source_chat_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, name, data, generated_by, generated_by_ai, status, source_chat_id, created_at, updated_at
`

type CreateFlowchartParams struct {
	ProjectID     pgtype.UUID
	Name          string
	Data          []byte
	GeneratedBy   pgtype.UUID
	GeneratedByAi pgtype.Bool
	Status        FlowchartStatus
	SourceChatID  pgtype.UUID
}

func (q *Queries) CreateFlowchart(ctx context.Context, arg CreateFlowchartParams) (Flowchart, error) {
	row := q.db.QueryRow(ctx, createFlowchart,
		arg.ProjectID,
		arg.Name,
		arg.Data,
		arg.GeneratedBy,
		arg.GeneratedByAi,
		arg.Status,
		arg.SourceChatID,
	)
	var i Flowchart
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Data,
		&i.GeneratedBy,
		&i.GeneratedByAi,
		&i.Status,
		&i.SourceChatID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFlowchart = `-- name: DeleteFlowchart :exec
DELETE
FROM flowcharts
WHERE id = $1
`

func (q *Queries) DeleteFlowchart(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFlowchart, id)
	return err
}

const getAIFlowCharts = `-- name: GetAIFlowCharts :many
SELECT id, project_id, name, data, generated_by, generated_by_ai, status, source_chat_id, created_at, updated_at
FROM flowcharts
WHERE generated_by_ai = TRUE
ORDER BY created_at DESC
`

func (q *Queries) GetAIFlowCharts(ctx context.Context) ([]Flowchart, error) {
	rows, err := q.db.Query(ctx, getAIFlowCharts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flowchart
	for rows.Next() {
		var i Flowchart
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Data,
			&i.GeneratedBy,
			&i.GeneratedByAi,
			&i.Status,
			&i.SourceChatID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowchartByID = `-- name: GetFlowchartByID :one
SELECT id, project_id, name, data, generated_by, generated_by_ai, status, source_chat_id, created_at, updated_at
FROM flowcharts
WHERE id = $1
`

func (q *Queries) GetFlowchartByID(ctx context.Context, id pgtype.UUID) (Flowchart, error) {
	row := q.db.QueryRow(ctx, getFlowchartByID, id)
	var i Flowchart
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Data,
		&i.GeneratedBy,
		&i.GeneratedByAi,
		&i.Status,
		&i.SourceChatID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlowchartWithProject = `-- name: GetFlowchartWithProject :one
SELECT
    f.id, f.project_id, f.name, f.data, f.generated_by, f.generated_by_ai, f.status, f.source_chat_id, f.created_at, f.updated_at,
    p.name AS project_name,
    p.owner_id,
    p.visibility
FROM flowcharts f
JOIN projects p
ON f.project_id = p.id
WHERE f.id = $1
`

type GetFlowchartWithProjectRow struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Name          string
	Data          []byte
	GeneratedBy   pgtype.UUID
	GeneratedByAi pgtype.Bool
	Status        FlowchartStatus
	SourceChatID  pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	ProjectName   string
	OwnerID       pgtype.UUID
	Visibility    ProjectVisibility
}

func (q *Queries) GetFlowchartWithProject(ctx context.Context, id pgtype.UUID) (GetFlowchartWithProjectRow, error) {
	row := q.db.QueryRow(ctx, getFlowchartWithProject, id)
	var i GetFlowchartWithProjectRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Data,
		&i.GeneratedBy,
		&i.GeneratedByAi,
		&i.Status,
		&i.SourceChatID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectName,
		&i.OwnerID,
		&i.Visibility,
	)
	return i, err
}

const getFlowchartsByChatID = `-- name: GetFlowchartsByChatID :many
SELECT id, project_id, name, data, generated_by, generated_by_ai, status, source_chat_id, created_at, updated_at
FROM flowcharts
WHERE source_chat_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetFlowchartsByChatID(ctx context.Context, sourceChatID pgtype.UUID) ([]Flowchart, error) {
	rows, err := q.db.Query(ctx, getFlowchartsByChatID, sourceChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flowchart
	for rows.Next() {
		var i Flowchart
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Data,
			&i.GeneratedBy,
			&i.GeneratedByAi,
			&i.Status,
			&i.SourceChatID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowchartsByGenerator = `-- name: GetFlowchartsByGenerator :many
SELECT id, project_id, name, data, generated_by, generated_by_ai, status, source_chat_id, created_at, updated_at
FROM flowcharts
WHERE generated_by = $1
ORDER BY created_at DESC
`

func (q *Queries) GetFlowchartsByGenerator(ctx context.Context, generatedBy pgtype.UUID) ([]Flowchart, error) {
	rows, err := q.db.Query(ctx, getFlowchartsByGenerator, generatedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flowchart
	for rows.Next() {
		var i Flowchart
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Data,
			&i.GeneratedBy,
			&i.GeneratedByAi,
			&i.Status,
			&i.SourceChatID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowchartsByProjectAndStatus = `-- name: GetFlowchartsByProjectAndStatus :many
SELECT id, project_id, name, data, generated_by, generated_by_ai, status, source_chat_id, created_at, updated_at
FROM flowcharts
WHERE project_id = $1
    AND status = $2
ORDER BY created_at DESC
`

type GetFlowchartsByProjectAndStatusParams struct {
	ProjectID pgtype.UUID
	Status    FlowchartStatus
}

func (q *Queries) GetFlowchartsByProjectAndStatus(ctx context.Context, arg GetFlowchartsByProjectAndStatusParams) ([]Flowchart, error) {
	rows, err := q.db.Query(ctx, getFlowchartsByProjectAndStatus, arg.ProjectID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flowchart
	for rows.Next() {
		var i Flowchart
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Data,
			&i.GeneratedBy,
			&i.GeneratedByAi,
			&i.Status,
			&i.SourceChatID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowchartsByProjectID = `-- name: GetFlowchartsByProjectID :many
SELECT id, project_id, name, data, generated_by, generated_by_ai, status, source_chat_id, created_at, updated_at
FROM flowcharts
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetFlowchartsByProjectID(ctx context.Context, projectID pgtype.UUID) ([]Flowchart, error) {
	rows, err := q.db.Query(ctx, getFlowchartsByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flowchart
	for rows.Next() {
		var i Flowchart
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Data,
			&i.GeneratedBy,
			&i.GeneratedByAi,
			&i.Status,
			&i.SourceChatID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowchartsByProjectIDs = `-- name: GetFlowchartsByProjectIDs :many
SELECT id, project_id, name, data, generated_by, generated_by_ai, status, source_chat_id, created_at, updated_at
FROM flowcharts
WHERE project_id = ANY($1::uuid[])
ORDER BY project_id, created_at DESC
`

// Batched form of GetFlowchartsByProjectID, used by the Project.flowcharts dataloader.
func (q *Queries) GetFlowchartsByProjectIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Flowchart, error) {
	rows, err := q.db.Query(ctx, getFlowchartsByProjectIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flowchart
	for rows.Next() {
		var i Flowchart
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Data,
			&i.GeneratedBy,
			&i.GeneratedByAi,
			&i.Status,
			&i.SourceChatID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowchartsByStatus = `-- name: GetFlowchartsByStatus :many
SELECT id, project_id, name, data, generated_by, generated_by_ai, status, source_chat_id, created_at, updated_at
FROM flowcharts
WHERE status = $1
ORDER BY created_at DESC
`

func (q *Queries) GetFlowchartsByStatus(ctx context.Context, status FlowchartStatus) ([]Flowchart, error) {
	rows, err := q.db.Query(ctx, getFlowchartsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flowchart
	for rows.Next() {
		var i Flowchart
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Data,
			&i.GeneratedBy,
			&i.GeneratedByAi,
			&i.Status,
			&i.SourceChatID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestFlowchart = `-- name: GetLatestFlowchart :one
SELECT id, project_id, name, data, generated_by, generated_by_ai, status, source_chat_id, created_at, updated_at
FROM flowcharts
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestFlowchart(ctx context.Context, projectID pgtype.UUID) (Flowchart, error) {
	row := q.db.QueryRow(ctx, getLatestFlowchart, projectID)
	var i Flowchart
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Data,
		&i.GeneratedBy,
		&i.GeneratedByAi,
		&i.Status,
		&i.SourceChatID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const renameFlowchart = `-- name: RenameFlowchart :one
UPDATE flowcharts
SET
    name = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, name, data, generated_by, generated_by_ai, status, source_chat_id, created_at, updated_at
`

type RenameFlowchartParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) RenameFlowchart(ctx context.Context, arg RenameFlowchartParams) (Flowchart, error) {
	row := q.db.QueryRow(ctx, renameFlowchart, arg.ID, arg.Name)
	var i Flowchart
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Data,
		&i.GeneratedBy,
		&i.GeneratedByAi,
		&i.Status,
		&i.SourceChatID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFlowchart = `-- name: UpdateFlowchart :one
UPDATE flowcharts
SET
    name = $2,
    data = $3,
    generated_by = $4,
    generated_by_ai = $5,
    status = $6,
    source_chat_id = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, name, data, generated_by, generated_by_ai, status, source_chat_id, created_at, updated_at
`

type UpdateFlowchartParams struct {
	ID            pgtype.UUID
	Name          string
	Data          []byte
	GeneratedBy   pgtype.UUID
	GeneratedByAi pgtype.Bool
	Status        FlowchartStatus
	SourceChatID  pgtype.UUID
}

func (q *Queries) UpdateFlowchart(ctx context.Context, arg UpdateFlowchartParams) (Flowchart, error) {
	row := q.db.QueryRow(ctx, updateFlowchart,
		arg.ID,
		arg.Name,
		arg.Data,
		arg.GeneratedBy,
		arg.GeneratedByAi,
		arg.Status,
		arg.SourceChatID,
	)
	var i Flowchart
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Data,
		&i.GeneratedBy,
		&i.GeneratedByAi,
		&i.Status,
		&i.SourceChatID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFlowchartStatus = `-- name: UpdateFlowchartStatus :one
UPDATE flowcharts
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, name, data, generated_by, generated_by_ai, status, source_chat_id, created_at, updated_at
`

type UpdateFlowchartStatusParams struct {
	ID     pgtype.UUID
	Status FlowchartStatus
}

func (q *Queries) UpdateFlowchartStatus(ctx context.Context, arg UpdateFlowchartStatusParams) (Flowchart, error) {
	row := q.db.QueryRow(ctx, updateFlowchartStatus, arg.ID, arg.Status)
	var i Flowchart
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Data,
		&i.GeneratedBy,
		&i.GeneratedByAi,
		&i.Status,
		&i.SourceChatID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
