// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ChatStatus string

const (
	ChatStatusACTIVE     ChatStatus = "ACTIVE"
	ChatStatusGENERATING ChatStatus = "GENERATING"
	ChatStatusARCHIVED   ChatStatus = "ARCHIVED"
)

func (e *ChatStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatStatus(s)
	case string:
		*e = ChatStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatStatus: %T", src)
	}
	return nil
}

type NullChatStatus struct {
	ChatStatus ChatStatus
	Valid      bool // Valid is true if ChatStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ChatStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatStatus), nil
}

type ChatType string

const (
	ChatTypeGENERAL     ChatType = "GENERAL"
	ChatTypeAIASSISTANT ChatType = "AI_ASSISTANT"
)

func (e *ChatType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatType(s)
	case string:
		*e = ChatType(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatType: %T", src)
	}
	return nil
}

type NullChatType struct {
	ChatType ChatType
	Valid    bool // Valid is true if ChatType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatType) Scan(value interface{}) error {
	if value == nil {
		ns.ChatType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatType), nil
}

type FilePermission string

const (
	FilePermissionREAD  FilePermission = "READ"
	FilePermissionWRITE FilePermission = "WRITE"
)

func (e *FilePermission) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FilePermission(s)
	case string:
		*e = FilePermission(s)
	default:
		return fmt.Errorf("unsupported scan type for FilePermission: %T", src)
	}
	return nil
}

type NullFilePermission struct {
	FilePermission FilePermission
	Valid          bool // Valid is true if FilePermission is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFilePermission) Scan(value interface{}) error {
	if value == nil {
		ns.FilePermission, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FilePermission.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFilePermission) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FilePermission), nil
}

type FileProcessingStatus string

const (
	FileProcessingStatusPENDING    FileProcessingStatus = "PENDING"
	FileProcessingStatusPROCESSING FileProcessingStatus = "PROCESSING"
	FileProcessingStatusCOMPLETED  FileProcessingStatus = "COMPLETED"
	FileProcessingStatusFAILED     FileProcessingStatus = "FAILED"
)

func (e *FileProcessingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FileProcessingStatus(s)
	case string:
		*e = FileProcessingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FileProcessingStatus: %T", src)
	}
	return nil
}

type NullFileProcessingStatus struct {
	FileProcessingStatus FileProcessingStatus
	Valid                bool // Valid is true if FileProcessingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFileProcessingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FileProcessingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FileProcessingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFileProcessingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FileProcessingStatus), nil
}

type FlowchartStatus string

const (
	FlowchartStatusDRAFT      FlowchartStatus = "DRAFT"
	FlowchartStatusGENERATING FlowchartStatus = "GENERATING"
	FlowchartStatusREADY      FlowchartStatus = "READY"
	FlowchartStatusFAILED     FlowchartStatus = "FAILED"
)

func (e *FlowchartStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FlowchartStatus(s)
	case string:
		*e = FlowchartStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FlowchartStatus: %T", src)
	}
	return nil
}

type NullFlowchartStatus struct {
	FlowchartStatus FlowchartStatus
	Valid           bool // Valid is true if FlowchartStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFlowchartStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FlowchartStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FlowchartStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFlowchartStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FlowchartStatus), nil
}

type MessageRole string

const (
	MessageRoleUSER   MessageRole = "USER"
	MessageRoleAI     MessageRole = "AI"
	MessageRoleSYSTEM MessageRole = "SYSTEM"
)

func (e *MessageRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageRole(s)
	case string:
		*e = MessageRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageRole: %T", src)
	}
	return nil
}

type NullMessageRole struct {
	MessageRole MessageRole
	Valid       bool // Valid is true if MessageRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageRole) Scan(value interface{}) error {
	if value == nil {
		ns.MessageRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageRole), nil
}

type OauthProvider string

const (
	OauthProviderGOOGLE OauthProvider = "GOOGLE"
	OauthProviderGITHUB OauthProvider = "GITHUB"
)

func (e *OauthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OauthProvider(s)
	case string:
		*e = OauthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for OauthProvider: %T", src)
	}
	return nil
}

type NullOauthProvider struct {
	OauthProvider OauthProvider
	Valid         bool // Valid is true if OauthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOauthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.OauthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OauthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOauthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OauthProvider), nil
}

type ProjectRole string

const (
	ProjectRoleOWNER  ProjectRole = "OWNER"
	ProjectRoleADMIN  ProjectRole = "ADMIN"
	ProjectRoleEDITOR ProjectRole = "EDITOR"
	ProjectRoleVIEWER ProjectRole = "VIEWER"
)

func (e *ProjectRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectRole(s)
	case string:
		*e = ProjectRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectRole: %T", src)
	}
	return nil
}

type NullProjectRole struct {
	ProjectRole ProjectRole
	Valid       bool // Valid is true if ProjectRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectRole) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectRole), nil
}

type ProjectVisibility string

const (
	ProjectVisibilityPRIVATE ProjectVisibility = "PRIVATE"
	ProjectVisibilityTEAM    ProjectVisibility = "TEAM"
)

func (e *ProjectVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectVisibility(s)
	case string:
		*e = ProjectVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectVisibility: %T", src)
	}
	return nil
}

type NullProjectVisibility struct {
	ProjectVisibility ProjectVisibility
	Valid             bool // Valid is true if ProjectVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectVisibility), nil
}

type ReportFormat string

const (
	ReportFormatMARKDOWN ReportFormat = "MARKDOWN"
	ReportFormatPDF      ReportFormat = "PDF"
	ReportFormatDOCX     ReportFormat = "DOCX"
)

func (e *ReportFormat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportFormat(s)
	case string:
		*e = ReportFormat(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportFormat: %T", src)
	}
	return nil
}

type NullReportFormat struct {
	ReportFormat ReportFormat
	Valid        bool // Valid is true if ReportFormat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportFormat) Scan(value interface{}) error {
	if value == nil {
		ns.ReportFormat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportFormat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportFormat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportFormat), nil
}

type ReportStatus string

const (
	ReportStatusDRAFT      ReportStatus = "DRAFT"
	ReportStatusGENERATING ReportStatus = "GENERATING"
	ReportStatusREADY      ReportStatus = "READY"
	ReportStatusFAILED     ReportStatus = "FAILED"
)

func (e *ReportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportStatus(s)
	case string:
		*e = ReportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportStatus: %T", src)
	}
	return nil
}

type NullReportStatus struct {
	ReportStatus ReportStatus
	Valid        bool // Valid is true if ReportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportStatus), nil
}

type ActivityLog struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	UserID     pgtype.UUID
	Action     string
	EntityType pgtype.Text
	EntityID   pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

type Chat struct {
	ID             pgtype.UUID
	ProjectID      pgtype.UUID
	Title          pgtype.Text
	Type           ChatType
	LastActivityAt pgtype.Timestamptz
	Status         ChatStatus
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type ChatAiMetadatum struct {
	MessageID       pgtype.UUID
	EmbeddingModel  pgtype.Text
	EmbeddingSynced pgtype.Bool
	IndexedAt       pgtype.Timestamptz
}

type ChatMessage struct {
	ID        pgtype.UUID
	ChatID    pgtype.UUID
	SenderID  pgtype.UUID
	Role      MessageRole
	Content   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ChatParticipant struct {
	ChatID   pgtype.UUID
	UserID   pgtype.UUID
	JoinedAt pgtype.Timestamptz
}

type File struct {
	ID        pgtype.UUID
	FolderID  pgtype.UUID
	ProjectID pgtype.UUID
	Name      string
	Size      int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type FileAiMetadatum struct {
	FileID           pgtype.UUID
	ExtractedText    pgtype.Text
	EmbeddingModel   pgtype.Text
	EmbeddingSynced  pgtype.Bool
	IndexedAt        pgtype.Timestamptz
	ProcessingStatus FileProcessingStatus
	Summary          pgtype.Text
	ErrorMessage     pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type FileProperty struct {
	FileID       pgtype.UUID
	OriginalName pgtype.Text
	IsIndexed    bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type FileShare struct {
	ID         pgtype.UUID
	FileID     pgtype.UUID
	SharedBy   pgtype.UUID
	SharedWith pgtype.UUID
	Permission FilePermission
	CreatedAt  pgtype.Timestamptz
}

type FileStorage struct {
	FileID     pgtype.UUID
	BucketName string
	ObjectKey  string
	Etag       pgtype.Text
	VersionID  pgtype.Text
	Checksum   pgtype.Text
	MimeType   string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	UploadedBy pgtype.UUID
}

type Flowchart struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Name          string
	Data          []byte
	GeneratedBy   pgtype.UUID
	GeneratedByAi pgtype.Bool
	Status        FlowchartStatus
	SourceChatID  pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Folder struct {
	ID             pgtype.UUID
	ProjectID      pgtype.UUID
	ParentFolderID pgtype.UUID
	Name           string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type MessageFileReference struct {
	MessageID pgtype.UUID
	FileID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type MessageMention struct {
	MessageID       pgtype.UUID
	MentionedUserID pgtype.UUID
	CreatedAt       pgtype.Timestamptz
}

type OauthAccount struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Provider       string
	ProviderUserID string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Project struct {
	ID          pgtype.UUID
	OwnerID     pgtype.UUID
	Name        string
	Description pgtype.Text
	Visibility  ProjectVisibility
	ArchivedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ProjectFile struct {
	ProjectID pgtype.UUID
	FileID    pgtype.UUID
	FolderID  pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type ProjectMember struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
	Role      ProjectRole
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Report struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	Title     string
	Content   string
	Format    ReportFormat
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ReportProperty struct {
	ReportID      pgtype.UUID
	GeneratedBy   pgtype.UUID
	GeneratedByAi pgtype.Bool
	Status        ReportStatus
	SourceChatID  pgtype.UUID
}

type Session struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Username  string
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type UserFilePreference struct {
	UserID     pgtype.UUID
	FileID     pgtype.UUID
	IsFavorite bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type UserProfile struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	FirstName string
	LastName  string
	Bio       pgtype.Text
	AvatarUrl pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
