// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO oauth_accounts (
    user_id,
    provider,
    provider_user_id
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING
    id,
    user_id,
    provider,
    provider_user_id,
    created_at,
    updated_at
`

type CreateOAuthAccountParams struct {
	UserID         pgtype.UUID
	Provider       string
	ProviderUserID string
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount, arg.UserID, arg.Provider, arg.ProviderUserID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOAuthAccount = `-- name: DeleteOAuthAccount :exec
DELETE FROM oauth_accounts
WHERE id = $1
`

func (q *Queries) DeleteOAuthAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOAuthAccount, id)
	return err
}

const deleteOAuthAccountByUserAndProvider = `-- name: DeleteOAuthAccountByUserAndProvider :exec
DELETE FROM oauth_accounts
WHERE user_id = $1
  AND provider = $2
`

type DeleteOAuthAccountByUserAndProviderParams struct {
	UserID   pgtype.UUID
	Provider string
}

func (q *Queries) DeleteOAuthAccountByUserAndProvider(ctx context.Context, arg DeleteOAuthAccountByUserAndProviderParams) error {
	_, err := q.db.Exec(ctx, deleteOAuthAccountByUserAndProvider, arg.UserID, arg.Provider)
	return err
}

const getOAuthAccount = `-- name: GetOAuthAccount :one

SELECT
    id,
    user_id,
    provider,
    provider_user_id,
    created_at,
    updated_at
FROM oauth_accounts
WHERE provider = $1
  AND provider_user_id = $2
LIMIT 1
`

type GetOAuthAccountParams struct {
	Provider       string
	ProviderUserID string
}

// ============================================================
// OAuth Accounts
// ============================================================
func (q *Queries) GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccount, arg.Provider, arg.ProviderUserID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthAccountByUserAndProvider = `-- name: GetOAuthAccountByUserAndProvider :one
SELECT
    id,
    user_id,
    provider,
    provider_user_id,
    created_at,
    updated_at
FROM oauth_accounts
WHERE user_id = $1
  AND provider = $2
LIMIT 1
`

type GetOAuthAccountByUserAndProviderParams struct {
	UserID   pgtype.UUID
	Provider string
}

func (q *Queries) GetOAuthAccountByUserAndProvider(ctx context.Context, arg GetOAuthAccountByUserAndProviderParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccountByUserAndProvider, arg.UserID, arg.Provider)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthAccountsByUserID = `-- name: GetOAuthAccountsByUserID :many
SELECT
    id,
    user_id,
    provider,
    provider_user_id,
    created_at,
    updated_at
FROM oauth_accounts
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetOAuthAccountsByUserID(ctx context.Context, userID pgtype.UUID) ([]OauthAccount, error) {
	rows, err := q.db.Query(ctx, getOAuthAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthAccount
	for rows.Next() {
		var i OauthAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
