// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectMember = `-- name: AddProjectMember :one
INSERT INTO project_members (
    project_id,
    user_id,
    role
)
VALUES ($1, $2, $3)
RETURNING id, project_id, user_id, role, created_at, updated_at
`

type AddProjectMemberParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
	Role      ProjectRole
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, addProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const archiveProject = `-- name: ArchiveProject :exec
UPDATE projects
SET
    archived_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ArchiveProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveProject, id)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    owner_id,
    name,
    description,
    visibility
)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, name, description, visibility, archived_at, created_at, updated_at
`

type CreateProjectParams struct {
	OwnerID     pgtype.UUID
	Name        string
	Description pgtype.Text
	Visibility  ProjectVisibility
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Visibility,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE
FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getArchivedProjectsByOwner = `-- name: GetArchivedProjectsByOwner :many
SELECT id, owner_id, name, description, visibility, archived_at, created_at, updated_at
FROM projects
WHERE owner_id = $1
  AND archived_at IS NOT NULL
`

func (q *Queries) GetArchivedProjectsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, getArchivedProjectsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivedProjectsForUser = `-- name: GetArchivedProjectsForUser :many
SELECT DISTINCT p.id, p.owner_id, p.name, p.description, p.visibility, p.archived_at, p.created_at, p.updated_at
FROM projects p
LEFT JOIN project_members pm
    ON p.id = pm.project_id
WHERE p.archived_at IS NOT NULL
  AND (
      p.owner_id = $1
      OR pm.user_id = $1
  )
`

func (q *Queries) GetArchivedProjectsForUser(ctx context.Context, ownerID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, getArchivedProjectsForUser, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, owner_id, name, description, visibility, archived_at, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, owner_id, name, description, visibility, archived_at, created_at, updated_at
FROM projects
WHERE name = $1 AND owner_id = $2
`

type GetProjectByNameParams struct {
	Name    string
	OwnerID pgtype.UUID
}

func (q *Queries) GetProjectByName(ctx context.Context, arg GetProjectByNameParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByName, arg.Name, arg.OwnerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT id, project_id, user_id, role, created_at, updated_at
FROM project_members
WHERE project_id = $1
  AND user_id = $2
`

type GetProjectMemberParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, getProjectMember, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectMembers = `-- name: GetProjectMembers :many
SELECT id, project_id, user_id, role, created_at, updated_at
FROM project_members
WHERE project_id = $1
ORDER BY created_at
`

func (q *Queries) GetProjectMembers(ctx context.Context, projectID pgtype.UUID) ([]ProjectMember, error) {
	rows, err := q.db.Query(ctx, getProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectMember
	for rows.Next() {
		var i ProjectMember
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectMembersByProjectIDs = `-- name: GetProjectMembersByProjectIDs :many
SELECT id, project_id, user_id, role, created_at, updated_at
FROM project_members
WHERE project_id = ANY($1::uuid[])
ORDER BY project_id, created_at
`

// Batched form of GetProjectMembers, used by the Project.members dataloader.
func (q *Queries) GetProjectMembersByProjectIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ProjectMember, error) {
	rows, err := q.db.Query(ctx, getProjectMembersByProjectIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectMember
	for rows.Next() {
		var i ProjectMember
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectMembersByUserIDs = `-- name: GetProjectMembersByUserIDs :many
SELECT id, project_id, user_id, role, created_at, updated_at
FROM project_members
WHERE user_id = ANY($1::uuid[])
ORDER BY user_id, created_at
`

// Every membership row of many users, used by the User.projectMemberships
// dataloader. (This replaces "list each user's projects, then look up the
// membership row per project": a membership row is exactly what that produced.)
func (q *Queries) GetProjectMembersByUserIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ProjectMember, error) {
	rows, err := q.db.Query(ctx, getProjectMembersByUserIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectMember
	for rows.Next() {
		var i ProjectMember
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectsByIDs = `-- name: GetProjectsByIDs :many
SELECT id, owner_id, name, description, visibility, archived_at, created_at, updated_at
FROM projects
WHERE id = ANY($1::uuid[])
`

// Batched project lookup, used by the Project scalar-field dataloader that
// fills in "stub" projects (an object that only carries an ID).
func (q *Queries) GetProjectsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectsByOwnerID = `-- name: GetProjectsByOwnerID :many
SELECT id, owner_id, name, description, visibility, archived_at, created_at, updated_at
FROM projects
WHERE owner_id = $1
  AND archived_at IS NULL
`

func (q *Queries) GetProjectsByOwnerID(ctx context.Context, ownerID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsByOwnerID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectsByOwnerIDs = `-- name: GetProjectsByOwnerIDs :many
SELECT id, owner_id, name, description, visibility, archived_at, created_at, updated_at
FROM projects
WHERE owner_id = ANY($1::uuid[])
  AND archived_at IS NULL
ORDER BY owner_id, created_at
`

// Batched form of GetProjectsByOwnerID, used by the User.ownedProjects dataloader.
func (q *Queries) GetProjectsByOwnerIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsByOwnerIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectsForUser = `-- name: GetProjectsForUser :many
SELECT DISTINCT p.id, p.owner_id, p.name, p.description, p.visibility, p.archived_at, p.created_at, p.updated_at
FROM projects p
LEFT JOIN project_members pm
    ON p.id = pm.project_id
WHERE p.archived_at IS NULL
  AND (
      p.owner_id = $1
      OR pm.user_id = $1
  )
`

// Active projects only: archived ones are served by GetArchivedProjectsForUser
// (the owner-scoped GetProjectsByOwnerID already excludes them the same way).
func (q *Queries) GetProjectsForUser(ctx context.Context, ownerID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsForUser, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE
FROM project_members
WHERE project_id = $1
  AND user_id = $2
`

type RemoveProjectMemberParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error {
	_, err := q.db.Exec(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const restoreProject = `-- name: RestoreProject :exec
UPDATE projects
SET
    archived_at = NULL,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RestoreProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restoreProject, id)
	return err
}

const transferOwnership = `-- name: TransferOwnership :one
UPDATE projects
SET
    owner_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, name, description, visibility, archived_at, created_at, updated_at
`

type TransferOwnershipParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) TransferOwnership(ctx context.Context, arg TransferOwnershipParams) (Project, error) {
	row := q.db.QueryRow(ctx, transferOwnership, arg.ID, arg.OwnerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    name = $2,
    description = $3,
    visibility = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, name, description, visibility, archived_at, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	Visibility  ProjectVisibility
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Visibility,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectMemberRole = `-- name: UpdateProjectMemberRole :one
UPDATE project_members
SET
    role = $3,
    updated_at = NOW()
WHERE project_id = $1
  AND user_id = $2
RETURNING id, project_id, user_id, role, created_at, updated_at
`

type UpdateProjectMemberRoleParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
	Role      ProjectRole
}

func (q *Queries) UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, updateProjectMemberRole, arg.ProjectID, arg.UserID, arg.Role)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
