// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
    id,
    project_id,
    title,
    content,
    generated_by,
    generated_by_ai,
    status,
    source_chat_id,
    format
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, title, content, generated_by, generated_by_ai, status, source_chat_id, format, created_at, updated_at
`

type CreateReportParams struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Title         string
	Content       string
	GeneratedBy   pgtype.UUID
	GeneratedByAi pgtype.Bool
	Status        ReportStatus
	SourceChatID  pgtype.UUID
	Format        ReportFormat
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Content,
		arg.GeneratedBy,
		arg.GeneratedByAi,
		arg.Status,
		arg.SourceChatID,
		arg.Format,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.GeneratedBy,
		&i.GeneratedByAi,
		&i.Status,
		&i.SourceChatID,
		&i.Format,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReport = `-- name: DeleteReport :exec
DELETE
FROM reports
WHERE id = $1
`

func (q *Queries) DeleteReport(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReport, id)
	return err
}

const getAIReports = `-- name: GetAIReports :many
SELECT id, project_id, title, content, generated_by, generated_by_ai, status, source_chat_id, format, created_at, updated_at
FROM reports
WHERE project_id = $1
  AND generated_by_ai = TRUE
ORDER BY created_at DESC
`

func (q *Queries) GetAIReports(ctx context.Context, projectID pgtype.UUID) ([]Report, error) {
	rows, err := q.db.Query(ctx, getAIReports, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.GeneratedBy,
			&i.GeneratedByAi,
			&i.Status,
			&i.SourceChatID,
			&i.Format,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, project_id, title, content, generated_by, generated_by_ai, status, source_chat_id, format, created_at, updated_at
FROM reports
WHERE id = $1
`

func (q *Queries) GetReportByID(ctx context.Context, id pgtype.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.GeneratedBy,
		&i.GeneratedByAi,
		&i.Status,
		&i.SourceChatID,
		&i.Format,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReportWithProject = `-- name: GetReportWithProject :one
SELECT
    r.id, r.project_id, r.title, r.content, r.generated_by, r.generated_by_ai, r.status, r.source_chat_id, r.format, r.created_at, r.updated_at,
    p.name AS project_name,
    p.owner_id,
    p.visibility
FROM reports r
JOIN projects p
ON r.project_id = p.id
WHERE r.id = $1
`

type GetReportWithProjectRow struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Title         string
	Content       string
	GeneratedBy   pgtype.UUID
	GeneratedByAi pgtype.Bool
	Status        ReportStatus
	SourceChatID  pgtype.UUID
	Format        ReportFormat
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	ProjectName   string
	OwnerID       pgtype.UUID
	Visibility    ProjectVisibility
}

func (q *Queries) GetReportWithProject(ctx context.Context, id pgtype.UUID) (GetReportWithProjectRow, error) {
	row := q.db.QueryRow(ctx, getReportWithProject, id)
	var i GetReportWithProjectRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.GeneratedBy,
		&i.GeneratedByAi,
		&i.Status,
		&i.SourceChatID,
		&i.Format,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectName,
		&i.OwnerID,
		&i.Visibility,
	)
	return i, err
}

const getReportsByChatID = `-- name: GetReportsByChatID :many
SELECT id, project_id, title, content, generated_by, generated_by_ai, status, source_chat_id, format, created_at, updated_at
FROM reports
WHERE source_chat_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetReportsByChatID(ctx context.Context, sourceChatID pgtype.UUID) ([]Report, error) {
	rows, err := q.db.Query(ctx, getReportsByChatID, sourceChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.GeneratedBy,
			&i.GeneratedByAi,
			&i.Status,
			&i.SourceChatID,
			&i.Format,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportsByFormat = `-- name: GetReportsByFormat :many
SELECT id, project_id, title, content, generated_by, generated_by_ai, status, source_chat_id, format, created_at, updated_at
FROM reports
WHERE project_id = $1
  AND format = $2
ORDER BY created_at DESC
`

type GetReportsByFormatParams struct {
	ProjectID pgtype.UUID
	Format    ReportFormat
}

func (q *Queries) GetReportsByFormat(ctx context.Context, arg GetReportsByFormatParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, getReportsByFormat, arg.ProjectID, arg.Format)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.GeneratedBy,
			&i.GeneratedByAi,
			&i.Status,
			&i.SourceChatID,
			&i.Format,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportsByGenerator = `-- name: GetReportsByGenerator :many
SELECT id, project_id, title, content, generated_by, generated_by_ai, status, source_chat_id, format, created_at, updated_at
FROM reports
WHERE generated_by = $1
ORDER BY created_at DESC
`

func (q *Queries) GetReportsByGenerator(ctx context.Context, generatedBy pgtype.UUID) ([]Report, error) {
	rows, err := q.db.Query(ctx, getReportsByGenerator, generatedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.GeneratedBy,
			&i.GeneratedByAi,
			&i.Status,
			&i.SourceChatID,
			&i.Format,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportsByProjectID = `-- name: GetReportsByProjectID :many
SELECT id, project_id, title, content, generated_by, generated_by_ai, status, source_chat_id, format, created_at, updated_at
FROM reports
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetReportsByProjectID(ctx context.Context, projectID pgtype.UUID) ([]Report, error) {
	rows, err := q.db.Query(ctx, getReportsByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.GeneratedBy,
			&i.GeneratedByAi,
			&i.Status,
			&i.SourceChatID,
			&i.Format,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportsByStatus = `-- name: GetReportsByStatus :many
SELECT id, project_id, title, content, generated_by, generated_by_ai, status, source_chat_id, format, created_at, updated_at
FROM reports
WHERE project_id = $1
  AND status = $2
ORDER BY created_at DESC
`

type GetReportsByStatusParams struct {
	ProjectID pgtype.UUID
	Status    ReportStatus
}

func (q *Queries) GetReportsByStatus(ctx context.Context, arg GetReportsByStatusParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, getReportsByStatus, arg.ProjectID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.GeneratedBy,
			&i.GeneratedByAi,
			&i.Status,
			&i.SourceChatID,
			&i.Format,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReport = `-- name: UpdateReport :one
UPDATE reports
SET
    title = $2,
    content = $3,
    format = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, title, content, generated_by, generated_by_ai, status, source_chat_id, format, created_at, updated_at
`

type UpdateReportParams struct {
	ID      pgtype.UUID
	Title   string
	Content string
	Format  ReportFormat
}

func (q *Queries) UpdateReport(ctx context.Context, arg UpdateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, updateReport,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Format,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.GeneratedBy,
		&i.GeneratedByAi,
		&i.Status,
		&i.SourceChatID,
		&i.Format,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReportStatus = `-- name: UpdateReportStatus :one
UPDATE reports
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, title, content, generated_by, generated_by_ai, status, source_chat_id, format, created_at, updated_at
`

type UpdateReportStatusParams struct {
	ID     pgtype.UUID
	Status ReportStatus
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) (Report, error) {
	row := q.db.QueryRow(ctx, updateReportStatus, arg.ID, arg.Status)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.GeneratedBy,
		&i.GeneratedByAi,
		&i.Status,
		&i.SourceChatID,
		&i.Format,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
