// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one
WITH new_report AS (
    INSERT INTO reports (
        id,
        project_id,
        title,
        content,
        format
    )
    VALUES ($1, $2, $3, $4, $5)
    RETURNING id, project_id, title, content, format, created_at, updated_at
),
new_properties AS (
    INSERT INTO report_properties (
        report_id,
        generated_by,
        generated_by_ai,
        status,
        source_chat_id
    )
    VALUES ($1, $6, $7, $8, $9)
    RETURNING report_id, generated_by, generated_by_ai, status, source_chat_id
)
SELECT
    r.id,
    r.project_id,
    r.title,
    r.content,
    r.format,
    r.created_at,
    r.updated_at,
    rp.generated_by,
    rp.generated_by_ai,
    rp.status,
    rp.source_chat_id
FROM new_report r
JOIN new_properties rp
ON r.id = rp.report_id
`

type CreateReportParams struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Title         string
	Content       string
	Format        ReportFormat
	GeneratedBy   pgtype.UUID
	GeneratedByAi pgtype.Bool
	Status        ReportStatus
	SourceChatID  pgtype.UUID
}

type CreateReportRow struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Title         string
	Content       string
	Format        ReportFormat
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	GeneratedBy   pgtype.UUID
	GeneratedByAi pgtype.Bool
	Status        ReportStatus
	SourceChatID  pgtype.UUID
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (CreateReportRow, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Content,
		arg.Format,
		arg.GeneratedBy,
		arg.GeneratedByAi,
		arg.Status,
		arg.SourceChatID,
	)
	var i CreateReportRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Format,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GeneratedBy,
		&i.GeneratedByAi,
		&i.Status,
		&i.SourceChatID,
	)
	return i, err
}

const deleteReport = `-- name: DeleteReport :exec
DELETE
FROM reports
WHERE id = $1
`

func (q *Queries) DeleteReport(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReport, id)
	return err
}

const getAIReports = `-- name: GetAIReports :many
SELECT
    r.id,
    r.project_id,
    r.title,
    r.content,
    r.format,
    r.created_at,
    r.updated_at,
    rp.generated_by,
    rp.generated_by_ai,
    rp.status,
    rp.source_chat_id
FROM reports r
JOIN report_properties rp
ON r.id = rp.report_id
WHERE r.project_id = $1
  AND rp.generated_by_ai = TRUE
ORDER BY r.created_at DESC
`

type GetAIReportsRow struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Title         string
	Content       string
	Format        ReportFormat
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	GeneratedBy   pgtype.UUID
	GeneratedByAi pgtype.Bool
	Status        ReportStatus
	SourceChatID  pgtype.UUID
}

func (q *Queries) GetAIReports(ctx context.Context, projectID pgtype.UUID) ([]GetAIReportsRow, error) {
	rows, err := q.db.Query(ctx, getAIReports, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAIReportsRow
	for rows.Next() {
		var i GetAIReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.Format,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GeneratedBy,
			&i.GeneratedByAi,
			&i.Status,
			&i.SourceChatID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportByID = `-- name: GetReportByID :one
SELECT
    r.id,
    r.project_id,
    r.title,
    r.content,
    r.format,
    r.created_at,
    r.updated_at,
    rp.generated_by,
    rp.generated_by_ai,
    rp.status,
    rp.source_chat_id
FROM reports r
JOIN report_properties rp
ON r.id = rp.report_id
WHERE r.id = $1
`

type GetReportByIDRow struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Title         string
	Content       string
	Format        ReportFormat
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	GeneratedBy   pgtype.UUID
	GeneratedByAi pgtype.Bool
	Status        ReportStatus
	SourceChatID  pgtype.UUID
}

func (q *Queries) GetReportByID(ctx context.Context, id pgtype.UUID) (GetReportByIDRow, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i GetReportByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Format,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GeneratedBy,
		&i.GeneratedByAi,
		&i.Status,
		&i.SourceChatID,
	)
	return i, err
}

const getReportWithProject = `-- name: GetReportWithProject :one
SELECT
    r.id,
    r.project_id,
    r.title,
    r.content,
    r.format,
    r.created_at,
    r.updated_at,
    rp.generated_by,
    rp.generated_by_ai,
    rp.status,
    rp.source_chat_id,
    p.name AS project_name,
    p.owner_id,
    p.visibility
FROM reports r
JOIN report_properties rp
ON r.id = rp.report_id
JOIN projects p
ON r.project_id = p.id
WHERE r.id = $1
`

type GetReportWithProjectRow struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Title         string
	Content       string
	Format        ReportFormat
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	GeneratedBy   pgtype.UUID
	GeneratedByAi pgtype.Bool
	Status        ReportStatus
	SourceChatID  pgtype.UUID
	ProjectName   string
	OwnerID       pgtype.UUID
	Visibility    ProjectVisibility
}

func (q *Queries) GetReportWithProject(ctx context.Context, id pgtype.UUID) (GetReportWithProjectRow, error) {
	row := q.db.QueryRow(ctx, getReportWithProject, id)
	var i GetReportWithProjectRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Format,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GeneratedBy,
		&i.GeneratedByAi,
		&i.Status,
		&i.SourceChatID,
		&i.ProjectName,
		&i.OwnerID,
		&i.Visibility,
	)
	return i, err
}

const getReportsByChatID = `-- name: GetReportsByChatID :many
SELECT
    r.id,
    r.project_id,
    r.title,
    r.content,
    r.format,
    r.created_at,
    r.updated_at,
    rp.generated_by,
    rp.generated_by_ai,
    rp.status,
    rp.source_chat_id
FROM reports r
JOIN report_properties rp
ON r.id = rp.report_id
WHERE rp.source_chat_id = $1
ORDER BY r.created_at DESC
`

type GetReportsByChatIDRow struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Title         string
	Content       string
	Format        ReportFormat
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	GeneratedBy   pgtype.UUID
	GeneratedByAi pgtype.Bool
	Status        ReportStatus
	SourceChatID  pgtype.UUID
}

func (q *Queries) GetReportsByChatID(ctx context.Context, sourceChatID pgtype.UUID) ([]GetReportsByChatIDRow, error) {
	rows, err := q.db.Query(ctx, getReportsByChatID, sourceChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportsByChatIDRow
	for rows.Next() {
		var i GetReportsByChatIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.Format,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GeneratedBy,
			&i.GeneratedByAi,
			&i.Status,
			&i.SourceChatID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportsByFormat = `-- name: GetReportsByFormat :many
SELECT
    r.id,
    r.project_id,
    r.title,
    r.content,
    r.format,
    r.created_at,
    r.updated_at,
    rp.generated_by,
    rp.generated_by_ai,
    rp.status,
    rp.source_chat_id
FROM reports r
JOIN report_properties rp
ON r.id = rp.report_id
WHERE r.project_id = $1
  AND r.format = $2
ORDER BY r.created_at DESC
`

type GetReportsByFormatParams struct {
	ProjectID pgtype.UUID
	Format    ReportFormat
}

type GetReportsByFormatRow struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Title         string
	Content       string
	Format        ReportFormat
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	GeneratedBy   pgtype.UUID
	GeneratedByAi pgtype.Bool
	Status        ReportStatus
	SourceChatID  pgtype.UUID
}

func (q *Queries) GetReportsByFormat(ctx context.Context, arg GetReportsByFormatParams) ([]GetReportsByFormatRow, error) {
	rows, err := q.db.Query(ctx, getReportsByFormat, arg.ProjectID, arg.Format)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportsByFormatRow
	for rows.Next() {
		var i GetReportsByFormatRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.Format,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GeneratedBy,
			&i.GeneratedByAi,
			&i.Status,
			&i.SourceChatID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportsByGenerator = `-- name: GetReportsByGenerator :many
SELECT
    r.id,
    r.project_id,
    r.title,
    r.content,
    r.format,
    r.created_at,
    r.updated_at,
    rp.generated_by,
    rp.generated_by_ai,
    rp.status,
    rp.source_chat_id
FROM reports r
JOIN report_properties rp
ON r.id = rp.report_id
WHERE rp.generated_by = $1
ORDER BY r.created_at DESC
`

type GetReportsByGeneratorRow struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Title         string
	Content       string
	Format        ReportFormat
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	GeneratedBy   pgtype.UUID
	GeneratedByAi pgtype.Bool
	Status        ReportStatus
	SourceChatID  pgtype.UUID
}

func (q *Queries) GetReportsByGenerator(ctx context.Context, generatedBy pgtype.UUID) ([]GetReportsByGeneratorRow, error) {
	rows, err := q.db.Query(ctx, getReportsByGenerator, generatedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportsByGeneratorRow
	for rows.Next() {
		var i GetReportsByGeneratorRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.Format,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GeneratedBy,
			&i.GeneratedByAi,
			&i.Status,
			&i.SourceChatID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportsByProjectID = `-- name: GetReportsByProjectID :many
SELECT
    r.id,
    r.project_id,
    r.title,
    r.content,
    r.format,
    r.created_at,
    r.updated_at,
    rp.generated_by,
    rp.generated_by_ai,
    rp.status,
    rp.source_chat_id
FROM reports r
JOIN report_properties rp
ON r.id = rp.report_id
WHERE r.project_id = $1
ORDER BY r.created_at DESC
`

type GetReportsByProjectIDRow struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Title         string
	Content       string
	Format        ReportFormat
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	GeneratedBy   pgtype.UUID
	GeneratedByAi pgtype.Bool
	Status        ReportStatus
	SourceChatID  pgtype.UUID
}

func (q *Queries) GetReportsByProjectID(ctx context.Context, projectID pgtype.UUID) ([]GetReportsByProjectIDRow, error) {
	rows, err := q.db.Query(ctx, getReportsByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportsByProjectIDRow
	for rows.Next() {
		var i GetReportsByProjectIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.Format,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GeneratedBy,
			&i.GeneratedByAi,
			&i.Status,
			&i.SourceChatID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportsByStatus = `-- name: GetReportsByStatus :many
SELECT
    r.id,
    r.project_id,
    r.title,
    r.content,
    r.format,
    r.created_at,
    r.updated_at,
    rp.generated_by,
    rp.generated_by_ai,
    rp.status,
    rp.source_chat_id
FROM reports r
JOIN report_properties rp
ON r.id = rp.report_id
WHERE r.project_id = $1
  AND rp.status = $2
ORDER BY r.created_at DESC
`

type GetReportsByStatusParams struct {
	ProjectID pgtype.UUID
	Status    ReportStatus
}

type GetReportsByStatusRow struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Title         string
	Content       string
	Format        ReportFormat
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	GeneratedBy   pgtype.UUID
	GeneratedByAi pgtype.Bool
	Status        ReportStatus
	SourceChatID  pgtype.UUID
}

func (q *Queries) GetReportsByStatus(ctx context.Context, arg GetReportsByStatusParams) ([]GetReportsByStatusRow, error) {
	rows, err := q.db.Query(ctx, getReportsByStatus, arg.ProjectID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportsByStatusRow
	for rows.Next() {
		var i GetReportsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.Format,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GeneratedBy,
			&i.GeneratedByAi,
			&i.Status,
			&i.SourceChatID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReport = `-- name: UpdateReport :one
WITH updated_report AS (
    UPDATE reports
    SET
        title = $2,
        content = $3,
        format = $4,
        updated_at = NOW()
    WHERE id = $1
    RETURNING id, project_id, title, content, format, created_at, updated_at
)
SELECT
    r.id,
    r.project_id,
    r.title,
    r.content,
    r.format,
    r.created_at,
    r.updated_at,
    rp.generated_by,
    rp.generated_by_ai,
    rp.status,
    rp.source_chat_id
FROM updated_report r
JOIN report_properties rp
ON r.id = rp.report_id
`

type UpdateReportParams struct {
	ID      pgtype.UUID
	Title   string
	Content string
	Format  ReportFormat
}

type UpdateReportRow struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Title         string
	Content       string
	Format        ReportFormat
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	GeneratedBy   pgtype.UUID
	GeneratedByAi pgtype.Bool
	Status        ReportStatus
	SourceChatID  pgtype.UUID
}

func (q *Queries) UpdateReport(ctx context.Context, arg UpdateReportParams) (UpdateReportRow, error) {
	row := q.db.QueryRow(ctx, updateReport,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Format,
	)
	var i UpdateReportRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Format,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GeneratedBy,
		&i.GeneratedByAi,
		&i.Status,
		&i.SourceChatID,
	)
	return i, err
}

const updateReportStatus = `-- name: UpdateReportStatus :one
WITH updated_properties AS (
    UPDATE report_properties
    SET
        status = $2
    WHERE report_id = $1
    RETURNING report_id, generated_by, generated_by_ai, status, source_chat_id
)
SELECT
    r.id,
    r.project_id,
    r.title,
    r.content,
    r.format,
    r.created_at,
    r.updated_at,
    rp.generated_by,
    rp.generated_by_ai,
    rp.status,
    rp.source_chat_id
FROM reports r
JOIN updated_properties rp
ON r.id = rp.report_id
WHERE r.id = $1
`

type UpdateReportStatusParams struct {
	ID     pgtype.UUID
	Status ReportStatus
}

type UpdateReportStatusRow struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Title         string
	Content       string
	Format        ReportFormat
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	GeneratedBy   pgtype.UUID
	GeneratedByAi pgtype.Bool
	Status        ReportStatus
	SourceChatID  pgtype.UUID
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) (UpdateReportStatusRow, error) {
	row := q.db.QueryRow(ctx, updateReportStatus, arg.ID, arg.Status)
	var i UpdateReportStatusRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Format,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GeneratedBy,
		&i.GeneratedByAi,
		&i.Status,
		&i.SourceChatID,
	)
	return i, err
}
