type Report {
  id: ID!
  project: Project!
  title: String!
  content: String!
  format: ReportFormat!
  properties: ReportProperties!
  createdAt: Time!
  updatedAt: Time!
}

type ReportProperties {
  report: Report!
  generatedBy: User!
  generatedByAI: Boolean!
  status: ReportStatus!
  sourceChat: Chat
}

extend type Query {
  report(id: ID!): Report
  reports(projectId: ID!): [Report!]!
  reportsByChat(sourceChatId: ID!): [Report!]!
  reportsByGenerator(projectId: ID!, generatedById: ID!): [Report!]!
  reportsByFormat(
    projectId: ID!
    format: ReportFormat!
  ): [Report!]!
  reportsByStatus(
    projectId: ID!
    status: ReportStatus!
  ): [Report!]!
  aiReports(projectId: ID!): [Report!]!
}

extend type Mutation {
  createReport(input: CreateReportInput!): Report!
  updateReport(id: ID!, input: UpdateReportInput!): Report!
  deleteReport(id: ID!): Boolean!
}

input CreateReportInput {
  projectId: ID!
  title: String!
  content: String!
  format: ReportFormat!
  generatedBy: ID
  generatedByAi: Boolean
  status: ReportStatus
  sourceChatId: ID
}

input UpdateReportInput {
  title: String
  content: String
  format: ReportFormat
}
