package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"example/hello/graph/model"
	"fmt"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	return r.UsersData.CreateUser(ctx, &input)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, name *string, password *string, email *string) (*model.User, error) {
	return r.UsersData.UpdateUser(ctx, id, name, password, email)
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (string, error) {
	return r.UsersData.DeleteUser(ctx, id)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	return r.UsersData.Login(ctx, email, password)
}

// GetUsers is the resolver for the getUsers field.
func (r *queryResolver) GetUsers(ctx context.Context) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: GetUsers - getUsers"))
}

// GetUserByID is the resolver for the getUserByID field.
func (r *queryResolver) GetUserByID(ctx context.Context, id string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: GetUserByID - getUserByID"))
}

// GetUserByEmail is the resolver for the getUserByEmail field.
func (r *queryResolver) GetUserByEmail(ctx context.Context, email string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: GetUserByEmail - getUserByEmail"))
}

// GetUserByName is the resolver for the getUserByName field.
func (r *queryResolver) GetUserByName(ctx context.Context, name string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: GetUserByName - getUserByName"))
}

// CurrentUser returns the authenticated user based on JWT in request context
func (r *queryResolver) CurrentUser(ctx context.Context) (*model.User, error) {
	userID, ok := GetUserIDFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthenticated")
	}
	return r.UsersData.GetUserByID(userID)
}

func (r *queryResolver) GetFiles(ctx context.Context) ([]*model.File, error) {
	panic(fmt.Errorf("not implemented: GetFiles - getFiles"))
}

// GetFolders is the resolver for the getFolders field.
func (r *queryResolver) GetFolders(ctx context.Context) ([]*model.Folder, error) {
	panic(fmt.Errorf("not implemented: GetFolders - getFolders"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
