// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type FolderItem interface {
	IsFolderItem()
}

type ActivityLog struct {
	ID         string    `json:"id"`
	Project    *Project  `json:"project,omitempty"`
	User       *User     `json:"user,omitempty"`
	Action     string    `json:"action"`
	EntityType *string   `json:"entityType,omitempty"`
	EntityID   *string   `json:"entityId,omitempty"`
	CreatedAt  time.Time `json:"createdAt"`
}

type AddChatParticipantInput struct {
	ChatID string `json:"chatId"`
	UserID string `json:"userId"`
}

type AddProjectMemberInput struct {
	ProjectID string      `json:"projectId"`
	UserID    string      `json:"userId"`
	Role      ProjectRole `json:"role"`
}

type Chat struct {
	ID             string             `json:"id"`
	Project        *Project           `json:"project"`
	Title          *string            `json:"title,omitempty"`
	Type           ChatType           `json:"type"`
	Status         ChatStatus         `json:"status"`
	LastActivityAt time.Time          `json:"lastActivityAt"`
	Participants   []*ChatParticipant `json:"participants"`
	Messages       []*ChatMessage     `json:"messages"`
	CreatedAt      time.Time          `json:"createdAt"`
	UpdatedAt      time.Time          `json:"updatedAt"`
}

type ChatAIMetadata struct {
	Message         *ChatMessage `json:"message"`
	EmbeddingModel  *string      `json:"embeddingModel,omitempty"`
	EmbeddingSynced bool         `json:"embeddingSynced"`
	IndexedAt       *time.Time   `json:"indexedAt,omitempty"`
}

type ChatMessage struct {
	ID              string          `json:"id"`
	Chat            *Chat           `json:"chat"`
	Sender          *User           `json:"sender,omitempty"`
	Role            MessageRole     `json:"role"`
	Content         string          `json:"content"`
	AiMetadata      *ChatAIMetadata `json:"aiMetadata,omitempty"`
	MentionedUsers  []*User         `json:"mentionedUsers"`
	ReferencedFiles []*File         `json:"referencedFiles"`
	CreatedAt       time.Time       `json:"createdAt"`
	UpdatedAt       time.Time       `json:"updatedAt"`
}

type ChatParticipant struct {
	User     *User     `json:"user"`
	JoinedAt time.Time `json:"joinedAt"`
}

type CreateChatInput struct {
	ProjectID      string   `json:"projectId"`
	Title          *string  `json:"title,omitempty"`
	Type           ChatType `json:"type"`
	ParticipantIds []string `json:"participantIds"`
}

type CreateFileInput struct {
	ProjectID *string `json:"projectId,omitempty"`
	FolderID  *string `json:"folderId,omitempty"`
	Name      string  `json:"name"`
	Size      int     `json:"size"`
}

type CreateFlowchartInput struct {
	ProjectID     string  `json:"projectId"`
	Name          string  `json:"name"`
	Data          string  `json:"data"`
	GeneratedByAi bool    `json:"generatedByAI"`
	SourceChatID  *string `json:"sourceChatId,omitempty"`
}

type CreateFolderInput struct {
	ProjectID      *string `json:"projectId,omitempty"`
	ParentFolderID *string `json:"parentFolderId,omitempty"`
	Name           string  `json:"name"`
}

type CreateProjectInput struct {
	Name        string            `json:"name"`
	Description *string           `json:"description,omitempty"`
	Visibility  ProjectVisibility `json:"visibility"`
}

type CreateReportInput struct {
	ProjectID     string       `json:"projectId"`
	Title         string       `json:"title"`
	Content       string       `json:"content"`
	Format        ReportFormat `json:"format"`
	GeneratedByAi bool         `json:"generatedByAI"`
	SourceChatID  *string      `json:"sourceChatId,omitempty"`
}

type CreateUserInput struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"passwordHash"`
}

type CreateUserProfileInput struct {
	UserID    string  `json:"userId"`
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Bio       *string `json:"bio,omitempty"`
	AvatarURL *string `json:"avatarUrl,omitempty"`
}

type File struct {
	ID           string            `json:"id"`
	Folder       *Folder           `json:"folder,omitempty"`
	Name         string            `json:"name"`
	Size         int               `json:"size"`
	Storage      *FileStorage      `json:"storage,omitempty"`
	Properties   *FileProperties   `json:"properties"`
	AiMetadata   *FileAIMetadata   `json:"aiMetadata,omitempty"`
	Shares       []*FileShare      `json:"shares"`
	Preferences  []*FilePreference `json:"preferences"`
	ProjectFiles []*ProjectFile    `json:"projectFiles"`
	CreatedAt    time.Time         `json:"createdAt"`
	UpdatedAt    time.Time         `json:"updatedAt"`
}

func (File) IsFolderItem() {}

type FileAIMetadata struct {
	File            *File      `json:"file"`
	ExtractedText   *string    `json:"extractedText,omitempty"`
	EmbeddingModel  *string    `json:"embeddingModel,omitempty"`
	EmbeddingSynced bool       `json:"embeddingSynced"`
	IndexedAt       *time.Time `json:"indexedAt,omitempty"`
	CreatedAt       time.Time  `json:"createdAt"`
	UpdatedAt       time.Time  `json:"updatedAt"`
}

type FilePreference struct {
	User       *User     `json:"user"`
	File       *File     `json:"file"`
	IsFavorite bool      `json:"isFavorite"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type FileProperties struct {
	File         *File      `json:"file"`
	OriginalName *string    `json:"originalName,omitempty"`
	IsIndexed    bool       `json:"isIndexed"`
	DeletedAt    *time.Time `json:"deletedAt,omitempty"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
}

type FileShare struct {
	ID         string         `json:"id"`
	File       *File          `json:"file"`
	SharedBy   *User          `json:"sharedBy"`
	SharedWith *User          `json:"sharedWith"`
	Permission FilePermission `json:"permission"`
	CreatedAt  time.Time      `json:"createdAt"`
}

type FileStorage struct {
	File       *File     `json:"file"`
	BucketName string    `json:"bucketName"`
	ObjectKey  string    `json:"objectKey"`
	Etag       *string   `json:"etag,omitempty"`
	VersionID  *string   `json:"versionId,omitempty"`
	Checksum   *string   `json:"checksum,omitempty"`
	MimeType   string    `json:"mimeType"`
	UploadedBy *User     `json:"uploadedBy"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type Flowchart struct {
	ID            string          `json:"id"`
	Project       *Project        `json:"project"`
	Name          string          `json:"name"`
	Data          string          `json:"data"`
	GeneratedBy   *User           `json:"generatedBy,omitempty"`
	GeneratedByAi bool            `json:"generatedByAI"`
	Status        FlowchartStatus `json:"status"`
	SourceChat    *Chat           `json:"sourceChat,omitempty"`
	CreatedAt     time.Time       `json:"createdAt"`
	UpdatedAt     time.Time       `json:"updatedAt"`
}

type Folder struct {
	ID           string    `json:"id"`
	Project      *Project  `json:"project,omitempty"`
	ParentFolder *Folder   `json:"parentFolder,omitempty"`
	ChildFolders []*Folder `json:"childFolders"`
	Files        []*File   `json:"files"`
	Name         string    `json:"name"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

func (Folder) IsFolderItem() {}

type MoveFileInput struct {
	FileID    string  `json:"fileId"`
	FolderID  *string `json:"folderId,omitempty"`
	ProjectID *string `json:"projectId,omitempty"`
}

type Mutation struct {
}

type Project struct {
	ID           string            `json:"id"`
	Name         string            `json:"name"`
	Description  *string           `json:"description,omitempty"`
	Visibility   ProjectVisibility `json:"visibility"`
	Owner        *User             `json:"owner"`
	Members      []*ProjectMember  `json:"members"`
	Folders      []*Folder         `json:"folders"`
	Files        []*ProjectFile    `json:"files"`
	Chats        []*Chat           `json:"chats"`
	Reports      []*Report         `json:"reports"`
	Flowcharts   []*Flowchart      `json:"flowcharts"`
	ActivityLogs []*ActivityLog    `json:"activityLogs"`
	ArchivedAt   *time.Time        `json:"archivedAt,omitempty"`
	CreatedAt    time.Time         `json:"createdAt"`
	UpdatedAt    time.Time         `json:"updatedAt"`
}

type ProjectFile struct {
	Project   *Project  `json:"project"`
	File      *File     `json:"file"`
	Folder    *Folder   `json:"folder,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
}

type ProjectMember struct {
	ID        string      `json:"id"`
	Role      ProjectRole `json:"role"`
	User      *User       `json:"user"`
	Project   *Project    `json:"project"`
	CreatedAt time.Time   `json:"createdAt"`
	UpdatedAt time.Time   `json:"updatedAt"`
}

type Query struct {
}

type Report struct {
	ID         string            `json:"id"`
	Project    *Project          `json:"project"`
	Title      string            `json:"title"`
	Content    string            `json:"content"`
	Format     ReportFormat      `json:"format"`
	Properties *ReportProperties `json:"properties"`
	CreatedAt  time.Time         `json:"createdAt"`
	UpdatedAt  time.Time         `json:"updatedAt"`
}

type ReportProperties struct {
	Report        *Report      `json:"report"`
	GeneratedBy   *User        `json:"generatedBy"`
	GeneratedByAi bool         `json:"generatedByAI"`
	Status        ReportStatus `json:"status"`
	SourceChat    *Chat        `json:"sourceChat,omitempty"`
}

type SendMessageInput struct {
	ChatID            string      `json:"chatId"`
	Role              MessageRole `json:"role"`
	Content           string      `json:"content"`
	MentionedUserIds  []string    `json:"mentionedUserIds,omitempty"`
	ReferencedFileIds []string    `json:"referencedFileIds,omitempty"`
}

type SetFileFavoriteInput struct {
	UserID     string `json:"userId"`
	FileID     string `json:"fileId"`
	IsFavorite bool   `json:"isFavorite"`
}

type ShareFileInput struct {
	FileID     string         `json:"fileId"`
	SharedBy   string         `json:"sharedBy"`
	SharedWith string         `json:"sharedWith"`
	Permission FilePermission `json:"permission"`
}

type UpdateFlowchartInput struct {
	FlowchartID   string  `json:"flowchartId"`
	Name          string  `json:"name"`
	Data          string  `json:"data"`
	GeneratedByAi bool    `json:"generatedByAI"`
	SourceChatID  *string `json:"sourceChatId,omitempty"`
}

type UpdateProjectInput struct {
	ProjectID   string            `json:"projectId"`
	Name        string            `json:"name"`
	Description *string           `json:"description,omitempty"`
	Visibility  ProjectVisibility `json:"visibility"`
}

type UpdateProjectMemberRoleInput struct {
	ProjectID string      `json:"projectId"`
	UserID    string      `json:"userId"`
	Role      ProjectRole `json:"role"`
}

type UpdateReportInput struct {
	ReportID string       `json:"reportId"`
	Title    string       `json:"title"`
	Content  string       `json:"content"`
	Format   ReportFormat `json:"format"`
}

type UpdateUserInput struct {
	UserID   string `json:"userId"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type UpdateUserPasswordInput struct {
	UserID       string `json:"userId"`
	PasswordHash string `json:"passwordHash"`
}

type UpdateUserProfileInput struct {
	UserID    string  `json:"userId"`
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Bio       *string `json:"bio,omitempty"`
	AvatarURL *string `json:"avatarUrl,omitempty"`
}

type User struct {
	ID                 string           `json:"id"`
	Username           string           `json:"username"`
	Email              string           `json:"email"`
	Profile            *UserProfile     `json:"profile,omitempty"`
	OwnedProjects      []*Project       `json:"ownedProjects"`
	ProjectMemberships []*ProjectMember `json:"projectMemberships"`
	UploadedFiles      []*File          `json:"uploadedFiles"`
	SharedFiles        []*FileShare     `json:"sharedFiles"`
	CreatedAt          time.Time        `json:"createdAt"`
	UpdatedAt          time.Time        `json:"updatedAt"`
}

type UserProfile struct {
	User      *User     `json:"user"`
	FirstName string    `json:"firstName"`
	LastName  string    `json:"lastName"`
	Bio       *string   `json:"bio,omitempty"`
	AvatarURL *string   `json:"avatarUrl,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type ChatStatus string

const (
	ChatStatusActive     ChatStatus = "ACTIVE"
	ChatStatusGenerating ChatStatus = "GENERATING"
	ChatStatusArchived   ChatStatus = "ARCHIVED"
)

var AllChatStatus = []ChatStatus{
	ChatStatusActive,
	ChatStatusGenerating,
	ChatStatusArchived,
}

func (e ChatStatus) IsValid() bool {
	switch e {
	case ChatStatusActive, ChatStatusGenerating, ChatStatusArchived:
		return true
	}
	return false
}

func (e ChatStatus) String() string {
	return string(e)
}

func (e *ChatStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ChatStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ChatStatus", str)
	}
	return nil
}

func (e ChatStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ChatStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ChatStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ChatType string

const (
	ChatTypeGeneral     ChatType = "GENERAL"
	ChatTypeAiAssistant ChatType = "AI_ASSISTANT"
)

var AllChatType = []ChatType{
	ChatTypeGeneral,
	ChatTypeAiAssistant,
}

func (e ChatType) IsValid() bool {
	switch e {
	case ChatTypeGeneral, ChatTypeAiAssistant:
		return true
	}
	return false
}

func (e ChatType) String() string {
	return string(e)
}

func (e *ChatType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ChatType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ChatType", str)
	}
	return nil
}

func (e ChatType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ChatType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ChatType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FilePermission string

const (
	FilePermissionRead  FilePermission = "READ"
	FilePermissionWrite FilePermission = "WRITE"
)

var AllFilePermission = []FilePermission{
	FilePermissionRead,
	FilePermissionWrite,
}

func (e FilePermission) IsValid() bool {
	switch e {
	case FilePermissionRead, FilePermissionWrite:
		return true
	}
	return false
}

func (e FilePermission) String() string {
	return string(e)
}

func (e *FilePermission) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FilePermission(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FilePermission", str)
	}
	return nil
}

func (e FilePermission) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FilePermission) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FilePermission) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FlowchartStatus string

const (
	FlowchartStatusDraft      FlowchartStatus = "DRAFT"
	FlowchartStatusGenerating FlowchartStatus = "GENERATING"
	FlowchartStatusReady      FlowchartStatus = "READY"
	FlowchartStatusFailed     FlowchartStatus = "FAILED"
)

var AllFlowchartStatus = []FlowchartStatus{
	FlowchartStatusDraft,
	FlowchartStatusGenerating,
	FlowchartStatusReady,
	FlowchartStatusFailed,
}

func (e FlowchartStatus) IsValid() bool {
	switch e {
	case FlowchartStatusDraft, FlowchartStatusGenerating, FlowchartStatusReady, FlowchartStatusFailed:
		return true
	}
	return false
}

func (e FlowchartStatus) String() string {
	return string(e)
}

func (e *FlowchartStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FlowchartStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FlowchartStatus", str)
	}
	return nil
}

func (e FlowchartStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FlowchartStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FlowchartStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MessageRole string

const (
	MessageRoleUser   MessageRole = "USER"
	MessageRoleAi     MessageRole = "AI"
	MessageRoleSystem MessageRole = "SYSTEM"
)

var AllMessageRole = []MessageRole{
	MessageRoleUser,
	MessageRoleAi,
	MessageRoleSystem,
}

func (e MessageRole) IsValid() bool {
	switch e {
	case MessageRoleUser, MessageRoleAi, MessageRoleSystem:
		return true
	}
	return false
}

func (e MessageRole) String() string {
	return string(e)
}

func (e *MessageRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MessageRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MessageRole", str)
	}
	return nil
}

func (e MessageRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MessageRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MessageRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProjectRole string

const (
	ProjectRoleOwner  ProjectRole = "OWNER"
	ProjectRoleAdmin  ProjectRole = "ADMIN"
	ProjectRoleEditor ProjectRole = "EDITOR"
	ProjectRoleViewer ProjectRole = "VIEWER"
)

var AllProjectRole = []ProjectRole{
	ProjectRoleOwner,
	ProjectRoleAdmin,
	ProjectRoleEditor,
	ProjectRoleViewer,
}

func (e ProjectRole) IsValid() bool {
	switch e {
	case ProjectRoleOwner, ProjectRoleAdmin, ProjectRoleEditor, ProjectRoleViewer:
		return true
	}
	return false
}

func (e ProjectRole) String() string {
	return string(e)
}

func (e *ProjectRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProjectRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProjectRole", str)
	}
	return nil
}

func (e ProjectRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProjectRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProjectRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProjectVisibility string

const (
	ProjectVisibilityPrivate ProjectVisibility = "PRIVATE"
	ProjectVisibilityTeam    ProjectVisibility = "TEAM"
)

var AllProjectVisibility = []ProjectVisibility{
	ProjectVisibilityPrivate,
	ProjectVisibilityTeam,
}

func (e ProjectVisibility) IsValid() bool {
	switch e {
	case ProjectVisibilityPrivate, ProjectVisibilityTeam:
		return true
	}
	return false
}

func (e ProjectVisibility) String() string {
	return string(e)
}

func (e *ProjectVisibility) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProjectVisibility(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProjectVisibility", str)
	}
	return nil
}

func (e ProjectVisibility) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProjectVisibility) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProjectVisibility) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ReportFormat string

const (
	ReportFormatMarkdown ReportFormat = "MARKDOWN"
	ReportFormatPDF      ReportFormat = "PDF"
	ReportFormatDocx     ReportFormat = "DOCX"
)

var AllReportFormat = []ReportFormat{
	ReportFormatMarkdown,
	ReportFormatPDF,
	ReportFormatDocx,
}

func (e ReportFormat) IsValid() bool {
	switch e {
	case ReportFormatMarkdown, ReportFormatPDF, ReportFormatDocx:
		return true
	}
	return false
}

func (e ReportFormat) String() string {
	return string(e)
}

func (e *ReportFormat) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReportFormat(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReportFormat", str)
	}
	return nil
}

func (e ReportFormat) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReportFormat) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReportFormat) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ReportStatus string

const (
	ReportStatusDraft      ReportStatus = "DRAFT"
	ReportStatusGenerating ReportStatus = "GENERATING"
	ReportStatusReady      ReportStatus = "READY"
	ReportStatusFailed     ReportStatus = "FAILED"
)

var AllReportStatus = []ReportStatus{
	ReportStatusDraft,
	ReportStatusGenerating,
	ReportStatusReady,
	ReportStatusFailed,
}

func (e ReportStatus) IsValid() bool {
	switch e {
	case ReportStatusDraft, ReportStatusGenerating, ReportStatusReady, ReportStatusFailed:
		return true
	}
	return false
}

func (e ReportStatus) String() string {
	return string(e)
}

func (e *ReportStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReportStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReportStatus", str)
	}
	return nil
}

func (e ReportStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReportStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReportStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
