package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"example/hello/graph/model"
	"fmt"
)

// CreateActivityLog is the resolver for the createActivityLog field.
func (r *mutationResolver) CreateActivityLog(ctx context.Context, input model.CreateActivityLogInput) (*model.ActivityLog, error) {
	panic(fmt.Errorf("not implemented: CreateActivityLog - createActivityLog"))
}

// DeleteActivityLogByID is the resolver for the deleteActivityLogByID field.
func (r *mutationResolver) DeleteActivityLogByID(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteActivityLogByID - deleteActivityLogByID"))
}

// ActivityLogs is the resolver for the activityLogs field.
func (r *queryResolver) ActivityLogs(ctx context.Context, projectID *string, userID *string) ([]*model.ActivityLog, error) {
	panic(fmt.Errorf("not implemented: ActivityLogs - activityLogs"))
}
