package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"example/hello/graph/model"
	"fmt"
)

// ActivityLogs is the resolver for the activityLogs field.
func (r *queryResolver) ActivityLogs(ctx context.Context, projectID *string, userID *string) ([]*model.ActivityLog, error) {
	panic(fmt.Errorf("not implemented: ActivityLogs - activityLogs"))
}
