package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"example/hello/graph/model"
	"fmt"
)

// CreateChat is the resolver for the createChat field.
func (r *mutationResolver) CreateChat(ctx context.Context, input model.CreateChatInput) (*model.Chat, error) {
	panic(fmt.Errorf("not implemented: CreateChat - createChat"))
}

// RenameChat is the resolver for the renameChat field.
func (r *mutationResolver) RenameChat(ctx context.Context, chatID string, title string) (*model.Chat, error) {
	panic(fmt.Errorf("not implemented: RenameChat - renameChat"))
}

// UpdateChatType is the resolver for the updateChatType field.
func (r *mutationResolver) UpdateChatType(ctx context.Context, chatID string, typeArg model.ChatType) (*model.Chat, error) {
	panic(fmt.Errorf("not implemented: UpdateChatType - updateChatType"))
}

// DeleteChat is the resolver for the deleteChat field.
func (r *mutationResolver) DeleteChat(ctx context.Context, chatID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteChat - deleteChat"))
}

// AddChatParticipant is the resolver for the addChatParticipant field.
func (r *mutationResolver) AddChatParticipant(ctx context.Context, input model.AddChatParticipantInput) (*model.ChatParticipant, error) {
	panic(fmt.Errorf("not implemented: AddChatParticipant - addChatParticipant"))
}

// RemoveChatParticipant is the resolver for the removeChatParticipant field.
func (r *mutationResolver) RemoveChatParticipant(ctx context.Context, chatID string, userID string) (bool, error) {
	panic(fmt.Errorf("not implemented: RemoveChatParticipant - removeChatParticipant"))
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, input model.SendMessageInput) (*model.ChatMessage, error) {
	panic(fmt.Errorf("not implemented: SendMessage - sendMessage"))
}

// UpdateChatMessage is the resolver for the updateChatMessage field.
func (r *mutationResolver) UpdateChatMessage(ctx context.Context, messageID string, content string) (*model.ChatMessage, error) {
	panic(fmt.Errorf("not implemented: UpdateChatMessage - updateChatMessage"))
}

// DeleteChatMessage is the resolver for the deleteChatMessage field.
func (r *mutationResolver) DeleteChatMessage(ctx context.Context, messageID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteChatMessage - deleteChatMessage"))
}

// UpdateChatStatus is the resolver for the updateChatStatus field.
func (r *mutationResolver) UpdateChatStatus(ctx context.Context, chatID string, status model.ChatStatus) (*model.Chat, error) {
	panic(fmt.Errorf("not implemented: UpdateChatStatus - updateChatStatus"))
}

// Chat is the resolver for the chat field.
func (r *queryResolver) Chat(ctx context.Context, id string) (*model.Chat, error) {
	panic(fmt.Errorf("not implemented: Chat - chat"))
}

// Chats is the resolver for the chats field.
func (r *queryResolver) Chats(ctx context.Context, projectID string) ([]*model.Chat, error) {
	panic(fmt.Errorf("not implemented: Chats - chats"))
}

// MyChats is the resolver for the myChats field.
func (r *queryResolver) MyChats(ctx context.Context, projectID *string) ([]*model.Chat, error) {
	panic(fmt.Errorf("not implemented: MyChats - myChats"))
}

// ChatMessages is the resolver for the chatMessages field.
func (r *queryResolver) ChatMessages(ctx context.Context, chatID string) ([]*model.ChatMessage, error) {
	panic(fmt.Errorf("not implemented: ChatMessages - chatMessages"))
}
