package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"example/hello/graph"
	"example/hello/graph/helpers"
	"example/hello/graph/loaders"
	"example/hello/graph/model"
	"example/hello/internal/apperrors"
	"example/hello/internal/database"

	"github.com/jackc/pgx/v5/pgtype"
)

// Participants is the resolver for the participants field.
func (r *chatResolver) Participants(ctx context.Context, obj *model.Chat) ([]*model.ChatParticipant, error) {
	chatID, err := parseUUID(obj.ID)
	if err != nil {
		return nil, err
	}

	var participants []database.ChatParticipant
	if l := loaders.From(ctx); l != nil {
		participants, err = l.ParticipantsByChat.Load(ctx, chatID)
	} else {
		participants, err = r.App.Services.Chat.GetChatParticipants(ctx, chatID)
	}
	if err != nil {
		return nil, err
	}

	result := make([]*model.ChatParticipant, 0, len(participants))
	for _, participant := range participants {
		result = append(result, &model.ChatParticipant{
			User:     &model.User{ID: participant.UserID.String()},
			JoinedAt: participant.JoinedAt.Time,
		})
	}
	return result, nil
}

// Messages is the resolver for the messages field.
func (r *chatResolver) Messages(ctx context.Context, obj *model.Chat) ([]*model.ChatMessage, error) {
	chatID, err := parseUUID(obj.ID)
	if err != nil {
		return nil, err
	}

	// Batched across every chat in the operation (see graph/loaders); falls
	// back to a direct query when no loaders are on the context.
	var messages []database.ChatMessage
	if l := loaders.From(ctx); l != nil {
		messages, err = l.MessagesByChat.Load(ctx, chatID)
	} else {
		messages, err = r.App.Services.Chat.GetChatMessagesByChatID(ctx, chatID)
	}
	if err != nil {
		return nil, err
	}

	result := make([]*model.ChatMessage, 0, len(messages))
	for _, message := range messages {
		result = append(result, helpers.ChatMessageToModel(message))
	}
	return result, nil
}

// MentionedUsers is the resolver for the mentionedUsers field.
func (r *chatMessageResolver) MentionedUsers(ctx context.Context, obj *model.ChatMessage) ([]*model.User, error) {
	messageID, err := parseUUID(obj.ID)
	if err != nil {
		return nil, err
	}

	// Batched across every message in the operation (see graph/loaders);
	// falls back to a direct per-message query when no loaders are on the
	// context.
	var mentions []database.GetMentionsForMessagesRow
	if l := loaders.From(ctx); l != nil {
		mentions, err = l.MentionsByMessage.Load(ctx, messageID)
	} else {
		var rows []database.GetMessageMentionsRow
		rows, err = r.App.Services.Chat.GetMessageMentions(ctx, messageID)
		for _, row := range rows {
			mentions = append(mentions, database.GetMentionsForMessagesRow{
				MessageID:       row.MessageID,
				MentionedUserID: row.MentionedUserID,
			})
		}
	}
	if err != nil {
		return nil, err
	}

	// Stubs, same as Sender/Participants above - only the ID is known
	// here, the rest of User resolves lazily through its own field
	// resolvers (backed by UserByID) if the query actually selects them.
	result := make([]*model.User, 0, len(mentions))
	for _, mention := range mentions {
		result = append(result, &model.User{ID: mention.MentionedUserID.String()})
	}
	return result, nil
}

// ReferencedFiles is the resolver for the referencedFiles field.
func (r *chatMessageResolver) ReferencedFiles(ctx context.Context, obj *model.ChatMessage) ([]*model.File, error) {
	messageID, err := parseUUID(obj.ID)
	if err != nil {
		return nil, err
	}

	var files []database.File
	if l := loaders.From(ctx); l != nil {
		files, err = l.FileReferencesByMessage.Load(ctx, messageID)
	} else {
		files, err = r.App.Services.File.GetFileReferencesByMessage(ctx, messageID)
	}
	if err != nil {
		return nil, err
	}

	return helpers.MapFilesToModel(files), nil
}

// CreateChat is the resolver for the createChat field.
func (r *mutationResolver) CreateChat(ctx context.Context, input model.CreateChatInput) (*model.Chat, error) {
	projectID, err := parseUUID(input.ProjectID)
	if err != nil {
		return nil, err
	}

	if err := r.requireProjectMember(ctx, projectID); err != nil {
		return nil, err
	}

	chat, err := r.App.Services.Chat.CreateChat(
		ctx,
		database.CreateChatParams{
			ProjectID: projectID,
			Title: pgtype.Text{
				String: input.Title,
				Valid:  true,
			},
			Type: database.ChatType(input.Type),
		},
	)
	if err != nil {
		return nil, err
	}

	return helpers.ChatToModel(chat), nil
}

// UpdateChat is the resolver for the updateChat field.
func (r *mutationResolver) UpdateChat(ctx context.Context, id string, input model.UpdateChatInput) (*model.Chat, error) {
	chatID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	existing, err := r.App.Services.Chat.GetChatByID(ctx, chatID)
	if err != nil {
		return nil, err
	}
	if err := r.requireProjectMember(ctx, existing.ProjectID); err != nil {
		return nil, err
	}

	// Update title if supplied.
	if input.Title != nil {
		_, err = r.App.Services.Chat.RenameChat(
			ctx,
			database.RenameChatParams{
				ID: chatID,
				Title: pgtype.Text{
					String: *input.Title,
					Valid:  true,
				},
			},
		)
		if err != nil {
			return nil, err
		}
	}

	// Update type if supplied.
	if input.Type != nil {
		_, err = r.App.Services.Chat.UpdateChatType(
			ctx,
			database.UpdateChatTypeParams{
				ID:   chatID,
				Type: database.ChatType(*input.Type),
			},
		)
		if err != nil {
			return nil, err
		}
	}

	// Update status if supplied.
	if input.Status != nil {
		_, err = r.App.Services.Chat.UpdateChatStatus(
			ctx,
			database.UpdateChatStatusParams{
				ID:     chatID,
				Status: database.ChatStatus(*input.Status),
			},
		)
		if err != nil {
			return nil, err
		}
	}

	// Return the final state after all requested updates.
	chat, err := r.App.Services.Chat.GetChatByID(ctx, chatID)
	if err != nil {
		return nil, err
	}

	return helpers.ChatToModel(chat), nil
}

// DeleteChat is the resolver for the deleteChat field.
func (r *mutationResolver) DeleteChat(ctx context.Context, id string) (bool, error) {
	chatID, err := parseUUID(id)
	if err != nil {
		return false, err
	}

	existing, err := r.App.Services.Chat.GetChatByID(ctx, chatID)
	if err != nil {
		return false, err
	}
	if err := r.requireProjectMember(ctx, existing.ProjectID); err != nil {
		return false, err
	}

	if err := r.App.Services.Chat.DeleteChat(ctx, chatID); err != nil {
		return false, err
	}

	return true, nil
}

// CreateChatParticipant is the resolver for the createChatParticipant field.
func (r *mutationResolver) CreateChatParticipant(ctx context.Context, input model.CreateChatParticipantInput) (*model.ChatParticipant, error) {
	chatID, err := parseUUID(input.ChatID)
	if err != nil {
		return nil, err
	}

	userID, err := parseUUID(input.UserID)
	if err != nil {
		return nil, err
	}

	chat, err := r.App.Services.Chat.GetChatByID(ctx, chatID)
	if err != nil {
		return nil, err
	}
	if err := r.requireProjectMember(ctx, chat.ProjectID); err != nil {
		return nil, err
	}

	participant, err := r.App.Services.Chat.CreateChatParticipant(
		ctx,
		database.CreateChatParticipantParams{
			ChatID: chatID,
			UserID: userID,
		},
	)
	if err != nil {
		return nil, err
	}

	return &model.ChatParticipant{
		User: &model.User{
			ID: participant.UserID.String(),
		},
		JoinedAt: participant.JoinedAt.Time,
	}, nil
}

// RemoveChatParticipant is the resolver for the removeChatParticipant field.
func (r *mutationResolver) RemoveChatParticipant(ctx context.Context, chatID string, userID string) (bool, error) {
	cID, err := parseUUID(chatID)
	if err != nil {
		return false, err
	}

	uID, err := parseUUID(userID)
	if err != nil {
		return false, err
	}

	chat, err := r.App.Services.Chat.GetChatByID(ctx, cID)
	if err != nil {
		return false, err
	}
	if err := r.requireProjectMember(ctx, chat.ProjectID); err != nil {
		return false, err
	}

	if err := r.App.Services.Chat.RemoveChatParticipant(
		ctx,
		database.RemoveChatParticipantParams{
			ChatID: cID,
			UserID: uID,
		},
	); err != nil {
		return false, err
	}

	return true, nil
}

// CreateChatMessage is the resolver for the createChatMessage field.
func (r *mutationResolver) CreateChatMessage(ctx context.Context, input model.CreateChatMessageInput) (*model.ChatMessage, error) {
	chatID, err := parseUUID(input.ChatID)
	if err != nil {
		return nil, err
	}

	// Get the authenticated user's ID from the context.
	userID, err := currentUserID(ctx)
	if err != nil {
		return nil, err
	}

	chat, err := r.App.Services.Chat.GetChatByID(ctx, chatID)
	if err != nil {
		return nil, err
	}
	if err := r.requireProjectMember(ctx, chat.ProjectID); err != nil {
		return nil, err
	}

	// Mentions/references are resolved to IDs by the client (an @/# picker)
	// and validated here, never parsed server-side from input.Content - see
	// docs/chat-mentions-and-file-references.pdf for why. Validate all of
	// them before creating the message, so a bad ID fails the whole
	// request instead of leaving a message with a partially-attached set.
	mentionedUserIDs := make([]pgtype.UUID, 0, len(input.MentionedUserIds))
	for _, idStr := range input.MentionedUserIds {
		mentionedID, err := parseUUID(idStr)
		if err != nil {
			return nil, err
		}
		if err := r.App.Services.Project.EnsureMemberAccess(ctx, chat.ProjectID, mentionedID); err != nil {
			return nil, apperrors.ForbiddenError("mentioned user is not a project member")
		}
		mentionedUserIDs = append(mentionedUserIDs, mentionedID)
	}

	referencedFileIDs := make([]pgtype.UUID, 0, len(input.ReferencedFileIds))
	for _, idStr := range input.ReferencedFileIds {
		fileID, err := parseUUID(idStr)
		if err != nil {
			return nil, err
		}
		file, err := r.App.Services.File.GetFileByID(ctx, fileID)
		if err != nil {
			return nil, err
		}
		if file.ProjectID != chat.ProjectID {
			return nil, apperrors.ForbiddenError("referenced file is not visible in this chat")
		}
		referencedFileIDs = append(referencedFileIDs, fileID)
	}

	message, err := r.App.Services.Chat.CreateChatMessage(
		ctx,
		database.CreateChatMessageParams{
			ChatID: chatID,
			SenderID: pgtype.UUID{
				Bytes: userID.Bytes,
				Valid: true,
			},
			Role:    database.MessageRole(input.Role),
			Content: input.Content,
		},
	)
	if err != nil {
		return nil, err
	}

	for _, mentionedID := range mentionedUserIDs {
		if _, err := r.App.Services.Chat.CreateMessageMention(ctx, database.CreateMessageMentionParams{
			MessageID:       message.ID,
			MentionedUserID: mentionedID,
		}); err != nil {
			return nil, err
		}
	}
	for _, fileID := range referencedFileIDs {
		if _, err := r.App.Services.File.CreateMessageFileReference(ctx, database.CreateMessageFileReferenceParams{
			MessageID: message.ID,
			FileID:    fileID,
		}); err != nil {
			return nil, err
		}
	}

	return helpers.ChatMessageToModel(message), nil
}

// UpdateChatMessage is the resolver for the updateChatMessage field.
func (r *mutationResolver) UpdateChatMessage(ctx context.Context, input model.UpdateChatMessageInput) (*model.ChatMessage, error) {
	messageID, err := parseUUID(input.ID)
	if err != nil {
		return nil, err
	}

	existing, err := r.App.Services.Chat.GetChatMessageByID(ctx, messageID)
	if err != nil {
		return nil, err
	}
	chat, err := r.App.Services.Chat.GetChatByID(ctx, existing.ChatID)
	if err != nil {
		return nil, err
	}
	if err := r.requireProjectMember(ctx, chat.ProjectID); err != nil {
		return nil, err
	}

	message, err := r.App.Services.Chat.UpdateChatMessage(
		ctx,
		database.UpdateChatMessageParams{
			ID:      messageID,
			Content: input.Content,
		},
	)
	if err != nil {
		return nil, err
	}

	return helpers.ChatMessageToModel(message), nil
}

// DeleteChatMessage is the resolver for the deleteChatMessage field.
func (r *mutationResolver) DeleteChatMessage(ctx context.Context, id string) (bool, error) {
	messageID, err := parseUUID(id)
	if err != nil {
		return false, err
	}

	existing, err := r.App.Services.Chat.GetChatMessageByID(ctx, messageID)
	if err != nil {
		return false, err
	}
	chat, err := r.App.Services.Chat.GetChatByID(ctx, existing.ChatID)
	if err != nil {
		return false, err
	}
	if err := r.requireProjectMember(ctx, chat.ProjectID); err != nil {
		return false, err
	}

	if err := r.App.Services.Chat.DeleteChatMessage(
		ctx,
		messageID,
	); err != nil {
		return false, err
	}

	return true, nil
}

// Chat is the resolver for the chat field.
func (r *queryResolver) Chat(ctx context.Context, id string) (*model.Chat, error) {
	chatID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	chat, err := r.App.Services.Chat.GetChatByID(ctx, chatID)
	if err != nil {
		return nil, err
	}
	if err := r.requireProjectMember(ctx, chat.ProjectID); err != nil {
		return nil, err
	}

	return helpers.ChatToModel(chat), nil
}

// Chats is the resolver for the chats field.
func (r *queryResolver) Chats(ctx context.Context, projectID string) ([]*model.Chat, error) {
	pID, err := parseUUID(projectID)
	if err != nil {
		return nil, err
	}
	if err := r.requireProjectMember(ctx, pID); err != nil {
		return nil, err
	}

	chats, err := r.App.Services.Chat.GetChatsByProjectID(
		ctx,
		pID,
	)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Chat, 0, len(chats))

	for _, chat := range chats {
		result = append(result, helpers.ChatToModel(chat))
	}

	return result, nil
}

// MyChats is the resolver for the myChats field.
func (r *queryResolver) MyChats(ctx context.Context, projectID *string) ([]*model.Chat, error) {
	userUUID, err := currentUserID(ctx)
	if err != nil {
		return nil, err
	}

	var chats []database.Chat

	if projectID != nil {
		projectUUID, err := parseUUID(*projectID)
		if err != nil {
			return nil, err
		}

		chats, err = r.App.Services.Chat.GetChatsByProjectAndUser(
			ctx,
			database.GetChatsByProjectAndUserParams{
				ProjectID: projectUUID,
				UserID:    userUUID,
			},
		)
		if err != nil {
			return nil, err
		}
	} else {
		chats, err = r.App.Services.Chat.GetChatsByUserID(
			ctx,
			userUUID,
		)
		if err != nil {
			return nil, err
		}
	}

	result := make([]*model.Chat, 0, len(chats))

	for _, chat := range chats {
		result = append(result, helpers.ChatToModel(chat))
	}

	return result, nil
}

// ChatMessages is the resolver for the chatMessages field.
func (r *queryResolver) ChatMessages(ctx context.Context, chatID string) ([]*model.ChatMessage, error) {
	cID, err := parseUUID(chatID)
	if err != nil {
		return nil, err
	}

	chat, err := r.App.Services.Chat.GetChatByID(ctx, cID)
	if err != nil {
		return nil, err
	}
	if err := r.requireProjectMember(ctx, chat.ProjectID); err != nil {
		return nil, err
	}

	messages, err := r.App.Services.Chat.GetChatMessagesByChatID(
		ctx,
		cID,
	)
	if err != nil {
		return nil, err
	}

	result := make([]*model.ChatMessage, 0, len(messages))

	for _, message := range messages {
		result = append(result, helpers.ChatMessageToModel(message))
	}

	return result, nil
}

// ArchivedChats is the resolver for the archivedChats field.
func (r *queryResolver) ArchivedChats(ctx context.Context, projectID string) ([]*model.Chat, error) {
	pID, err := parseUUID(projectID)
	if err != nil {
		return nil, err
	}
	if err := r.requireProjectMember(ctx, pID); err != nil {
		return nil, err
	}

	chats, err := r.App.Services.Chat.GetArchivedChats(
		ctx,
		pID,
	)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Chat, 0, len(chats))

	for _, chat := range chats {
		result = append(result, helpers.ChatToModel(chat))
	}

	return result, nil
}

// ActiveChats is the resolver for the activeChats field.
func (r *queryResolver) ActiveChats(ctx context.Context, projectID string) ([]*model.Chat, error) {
	pID, err := parseUUID(projectID)
	if err != nil {
		return nil, err
	}
	if err := r.requireProjectMember(ctx, pID); err != nil {
		return nil, err
	}

	chats, err := r.App.Services.Chat.GetActiveChats(
		ctx,
		pID,
	)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Chat, 0, len(chats))

	for _, chat := range chats {
		result = append(result, helpers.ChatToModel(chat))
	}

	return result, nil
}

// ChatMessageAdded is the resolver for the chatMessageAdded field. It
// authorizes exactly like every other chat resolver (must be the chat's
// project owner or a member), then bridges the in-process ChatBroker's raw
// database.ChatMessage channel into a channel of *model.ChatMessage, which
// is the shape gqlgen's websocket transport expects: it reads from the
// returned channel for as long as the client stays subscribed and pushes
// each value down as a "next" message, stopping when the channel closes.
func (r *subscriptionResolver) ChatMessageAdded(ctx context.Context, chatID string) (<-chan *model.ChatMessage, error) {
	cID, err := parseUUID(chatID)
	if err != nil {
		return nil, err
	}

	chat, err := r.App.Services.Chat.GetChatByID(ctx, cID)
	if err != nil {
		return nil, err
	}
	if err := r.requireProjectMember(ctx, chat.ProjectID); err != nil {
		return nil, err
	}

	source, unsubscribe, err := r.App.Services.Chat.SubscribeToMessages(ctx, cID)
	if err != nil {
		return nil, err
	}

	out := make(chan *model.ChatMessage, 1)

	go func() {
		defer close(out)
		defer unsubscribe()

		for {
			select {
			case <-ctx.Done():
				return
			case message, ok := <-source:
				if !ok {
					return
				}
				select {
				case out <- helpers.ChatMessageToModel(message):
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// Chat returns graph.ChatResolver implementation.
func (r *Resolver) Chat() graph.ChatResolver { return &chatResolver{r} }

// ChatMessage returns graph.ChatMessageResolver implementation.
func (r *Resolver) ChatMessage() graph.ChatMessageResolver { return &chatMessageResolver{r} }

type (
	chatResolver        struct{ *Resolver }
	chatMessageResolver struct{ *Resolver }
)
