package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations will be copied through when generating and any unknown code
// will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"

	"example/hello/graph/helpers"
	"example/hello/graph/model"
	"example/hello/internal/database"

	"github.com/jackc/pgx/v5/pgtype"
)

// ============================================================
// FOLDER MUTATIONS
// ============================================================

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(
	ctx context.Context,
	input model.CreateFolderInput,
) (*model.Folder, error) {

	projectID, err := parseUUID(input.ProjectID)
	if err != nil {
		return nil, err
	}

	var parentFolderID pgtype.UUID

	// nil = root folder
	// non-nil = child folder
	if input.ParentFolderID != nil {
		parentFolderID, err = parseUUID(*input.ParentFolderID)
		if err != nil {
			return nil, err
		}
	}

	folder, err := r.App.Services.File.CreateFolder(
		ctx,
		database.CreateFolderParams{
			ProjectID:      projectID,
			ParentFolderID: parentFolderID,
			Name:           input.Name,
		},
	)
	if err != nil {
		return nil, err
	}

	return &model.Folder{
		ID:   folder.ID.String(),
		Name: folder.Name,
		Project: &model.Project{
			ID: folder.ProjectID.String(),
		},
	}, nil
}

// RenameFolder is the resolver for the renameFolder field.
func (r *mutationResolver) RenameFolder(
	ctx context.Context,
	folderID string,
	name string,
) (*model.Folder, error) {

	id, err := parseUUID(folderID)
	if err != nil {
		return nil, err
	}

	folder, err := r.App.Services.File.RenameFolder(
		ctx,
		database.RenameFolderParams{
			ID:   id,
			Name: name,
		},
	)
	if err != nil {
		return nil, err
	}

	return &model.Folder{
		ID:   folder.ID.String(),
		Name: folder.Name,
		Project: &model.Project{
			ID: folder.ProjectID.String(),
		},
	}, nil
}

// MoveFolder is the resolver for the moveFolder field.
func (r *mutationResolver) MoveFolder(
	ctx context.Context,
	folderID string,
	parentFolderID *string,
) (*model.Folder, error) {

	id, err := parseUUID(folderID)
	if err != nil {
		return nil, err
	}

	var parentID pgtype.UUID

	// nil = move folder to project root
	// non-nil = move folder inside another folder
	if parentFolderID != nil {
		parentID, err = parseUUID(*parentFolderID)
		if err != nil {
			return nil, err
		}
	}

	folder, err := r.App.Services.File.MoveFolder(
		ctx,
		database.MoveFolderParams{
			ID:             id,
			ParentFolderID: parentID,
		},
	)
	if err != nil {
		return nil, err
	}

	return &model.Folder{
		ID:   folder.ID.String(),
		Name: folder.Name,
		Project: &model.Project{
			ID: folder.ProjectID.String(),
		},
	}, nil
}

// DeleteFolder is the resolver for the deleteFolder field.
func (r *mutationResolver) DeleteFolder(
	ctx context.Context,
	folderID string,
) (bool, error) {

	id, err := parseUUID(folderID)
	if err != nil {
		return false, err
	}

	if err := r.App.Services.File.DeleteFolder(ctx, id); err != nil {
		return false, err
	}

	return true, nil
}

// ============================================================
// FILE MUTATIONS
// ============================================================

// CreateFile is the resolver for the createFile field.
func (r *mutationResolver) CreateFile(
	ctx context.Context,
	input model.CreateFileInput,
) (*model.File, error) {

	var folderID pgtype.UUID
	var err error

	// nil = root file
	// non-nil = file inside a folder
	if input.FolderID != nil {
		folderID, err = parseUUID(*input.FolderID)
		if err != nil {
			return nil, err
		}
	}

	file, err := r.App.Services.File.CreateFile(
		ctx,
		database.CreateFileParams{
			FolderID: folderID,
			Name:     input.Name,
			Size:     int64(input.Size),
		},
	)
	if err != nil {
		return nil, err
	}

	var folder *model.Folder

	if file.FolderID.Valid {
		folder = &model.Folder{
			ID: file.FolderID.String(),
		}
	}

	return &model.File{
		ID:     file.ID.String(),
		Name:   file.Name,
		Size:   int(file.Size),
		Folder: folder,
	}, nil
}

// RenameFile is the resolver for the renameFile field.
func (r *mutationResolver) RenameFile(
	ctx context.Context,
	fileID string,
	name string,
) (*model.File, error) {

	id, err := parseUUID(fileID)
	if err != nil {
		return nil, err
	}

	file, err := r.App.Services.File.RenameFile(
		ctx,
		database.RenameFileParams{
			ID:   id,
			Name: name,
		},
	)
	if err != nil {
		return nil, err
	}

	var folder *model.Folder

	if file.FolderID.Valid {
		folder = &model.Folder{
			ID: file.FolderID.String(),
		}
	}

	return &model.File{
		ID:     file.ID.String(),
		Name:   file.Name,
		Size:   int(file.Size),
		Folder: folder,
	}, nil
}

// MoveFile is the resolver for the moveFile field.
func (r *mutationResolver) MoveFile(
	ctx context.Context,
	input model.MoveFileInput,
) (*model.File, error) {

	fileID, err := parseUUID(input.FileID)
	if err != nil {
		return nil, err
	}

	folderID, err := parseUUID(*input.FolderID)
	if err != nil {
		return nil, err
	}

	file, err := r.App.Services.File.MoveFile(
		ctx,
		database.MoveFileParams{
			ID:       fileID,
			FolderID: folderID,
		},
	)
	if err != nil {
		return nil, err
	}

	var folder *model.Folder

	if file.FolderID.Valid {
		folder = &model.Folder{
			ID: file.FolderID.String(),
		}
	}

	return &model.File{
		ID:     file.ID.String(),
		Name:   file.Name,
		Size:   int(file.Size),
		Folder: folder,
	}, nil
}

// DeleteFile is the resolver for the deleteFile field.
func (r *mutationResolver) DeleteFile(
	ctx context.Context,
	fileID string,
) (bool, error) {

	id, err := parseUUID(fileID)
	if err != nil {
		return false, err
	}

	if err := r.App.Services.File.DeleteFile(ctx, id); err != nil {
		return false, err
	}

	return true, nil
}

// ============================================================
// FAVORITES
// ============================================================

// SetFileFavorite is the resolver for the setFileFavorite field.
func (r *mutationResolver) SetFileFavorite(
	ctx context.Context,
	input model.SetFileFavoriteInput,
) (*model.FilePreference, error) {

	fileID, err := parseUUID(input.FileID)
	if err != nil {
		return nil, err
	}

	userID, err := parseUUID(input.UserID)
	if err != nil {
		return nil, err
	}

	preference, err := r.App.Services.File.SetFavorite(
		ctx,
		database.SetFavoriteParams{
			FileID: fileID,
			UserID: userID,
		},
	)
	if err != nil {
		return nil, err
	}

	return &model.FilePreference{
		File: &model.File{
			ID: preference.FileID.String(),
		},
		User: &model.User{
			ID: preference.UserID.String(),
		},
		IsFavorite: preference.IsFavorite,
	}, nil
}

// ============================================================
// FOLDER QUERIES
// ============================================================

// Folder is the resolver for the folder field.
func (r *queryResolver) Folder(
	ctx context.Context,
	id string,
) (*model.Folder, error) {

	folderID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	folder, err := r.App.Services.File.GetFolderByID(
		ctx,
		folderID,
	)
	if err != nil {
		return nil, err
	}

	return &model.Folder{
		ID:   folder.ID.String(),
		Name: folder.Name,
		Project: &model.Project{
			ID: folder.ProjectID.String(),
		},
	}, nil
}

// Folders is the resolver for the folders field.
func (r *queryResolver) Folders(
	ctx context.Context,
	projectID *string,
) ([]*model.Folder, error) {

	if projectID == nil {
		return []*model.Folder{}, nil
	}

	id, err := parseUUID(*projectID)
	if err != nil {
		return nil, err
	}

	folders, err := r.App.Services.File.GetFoldersByProjectID(
		ctx,
		id,
	)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Folder, 0, len(folders))

	for _, folder := range folders {
		result = append(result, &model.Folder{
			ID:   folder.ID.String(),
			Name: folder.Name,
			Project: &model.Project{
				ID: folder.ProjectID.String(),
			},
		})
	}

	return result, nil
}

// RootFolders is the resolver for the rootFolders field.
func (r *queryResolver) RootFolders(
	ctx context.Context,
	projectID string,
) ([]*model.Folder, error) {

	id, err := parseUUID(projectID)
	if err != nil {
		return nil, err
	}

	folders, err := r.App.Services.File.GetRootFolders(
		ctx,
		id,
	)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Folder, 0, len(folders))

	for _, folder := range folders {
		result = append(result, &model.Folder{
			ID:   folder.ID.String(),
			Name: folder.Name,
			Project: &model.Project{
				ID: folder.ProjectID.String(),
			},
		})
	}

	return result, nil
}

// FolderPath is the resolver for the folderPath field.
func (r *queryResolver) FolderPath(
	ctx context.Context,
	folderID string,
) ([]*model.Folder, error) {

	id, err := parseUUID(folderID)
	if err != nil {
		return nil, err
	}

	folders, err := r.App.Services.File.GetFolderPath(
		ctx,
		id,
	)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Folder, 0, len(folders))

	for _, folder := range folders {
		result = append(result, &model.Folder{
			ID:   folder.ID.String(),
			Name: folder.Name,
			Project: &model.Project{
				ID: folder.ProjectID.String(),
			},
		})
	}

	return result, nil
}

// ============================================================
// FILE QUERIES
// ============================================================

// File is the resolver for the file field.
func (r *queryResolver) File(
	ctx context.Context,
	id string,
) (*model.File, error) {

	fileID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	file, err := r.App.Services.File.GetFileByID(
		ctx,
		fileID,
	)
	if err != nil {
		return nil, err
	}

	var folder *model.Folder

	if file.FolderID.Valid {
		folder = &model.Folder{
			ID: file.FolderID.String(),
		}
	}

	return &model.File{
		ID:     file.ID.String(),
		Name:   file.Name,
		Size:   int(file.Size),
		Folder: folder,
	}, nil
}

// Files is the resolver for the files field.
func (r *queryResolver) Files(
	ctx context.Context,
	projectID *string,
	folderID *string,
) ([]*model.File, error) {

	if folderID != nil {

		id, err := parseUUID(*folderID)
		if err != nil {
			return nil, err
		}

		files, err := r.App.Services.File.GetFilesByFolderID(
			ctx,
			id,
		)
		if err != nil {
			return nil, err
		}

		return helpers.MapFilesToModel(files), nil
	}

	if projectID != nil {

		id, err := parseUUID(*projectID)
		if err != nil {
			return nil, err
		}

		files, err := r.App.Services.File.GetFilesByProjectID(
			ctx,
			id,
		)
		if err != nil {
			return nil, err
		}

		return helpers.MapFilesToModel(files), nil
	}

	return []*model.File{}, nil
}

// RootFiles is the resolver for the rootFiles field.
func (r *queryResolver) RootFiles(
	ctx context.Context,
	projectID string,
) ([]*model.File, error) {

	id, err := parseUUID(projectID)
	if err != nil {
		return nil, err
	}

	files, err := r.App.Services.File.GetRootFiles(
		ctx,
		id,
	)
	if err != nil {
		return nil, err
	}

	return helpers.MapFilesToModel(files), nil
}

// FavoriteFiles is the resolver for the favoriteFiles field.
func (r *queryResolver) FavoriteFiles(
	ctx context.Context,
	userID string,
	projectID *string,
) ([]*model.File, error) {

	// Your current FileService does not expose a method
	// that returns a list of favorite files.
	return nil, fmt.Errorf(
		"favoriteFiles is not implemented by FileService",
	)
}

// ============================================================
// FOLDER CONTENTS
// ============================================================

// FolderContents is the resolver for the folderContents field.
func (r *queryResolver) FolderContents(
	ctx context.Context,
	folderID *string,
	projectID *string,
) ([]model.FolderItem, error) {

	return nil, fmt.Errorf(
		"folderContents is not implemented by FileService",
	)
}

// ============================================================
// FILE SHARING
// ============================================================

// ShareFile is the resolver for the shareFile field.
func (r *mutationResolver) ShareFile(
	ctx context.Context,
	input model.ShareFileInput,
) (*model.FileShare, error) {

	return nil, fmt.Errorf(
		"shareFile is not implemented by FileService",
	)
}

// UpdateFileSharePermission is the resolver for the updateFileSharePermission field.
func (r *mutationResolver) UpdateFileSharePermission(
	ctx context.Context,
	fileShareID string,
	permission model.FilePermission,
) (*model.FileShare, error) {

	return nil, fmt.Errorf(
		"updateFileSharePermission is not implemented by FileService",
	)
}

// DeleteFileShare is the resolver for the deleteFileShare field.
func (r *mutationResolver) DeleteFileShare(
	ctx context.Context,
	fileShareID string,
) (bool, error) {

	return false, fmt.Errorf(
		"deleteFileShare is not implemented by FileService",
	)
}

// FileShare is the resolver for the fileShare field.
func (r *queryResolver) FileShare(
	ctx context.Context,
	id string,
) (*model.FileShare, error) {

	return nil, fmt.Errorf(
		"fileShare is not implemented by FileService",
	)
}

// FileShares is the resolver for the fileShares field.
func (r *queryResolver) FileShares(
	ctx context.Context,
	fileID string,
) ([]*model.FileShare, error) {

	return nil, fmt.Errorf(
		"fileShares is not implemented by FileService",
	)
}

// SharedWithMe is the resolver for the sharedWithMe field.
func (r *queryResolver) SharedWithMe(
	ctx context.Context,
	userID string,
) ([]*model.FileShare, error) {

	return nil, fmt.Errorf(
		"sharedWithMe is not implemented by FileService",
	)
}
