package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"example/hello/graph/model"
	"fmt"
)

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, input model.CreateFolderInput) (*model.Folder, error) {
	panic(fmt.Errorf("not implemented: CreateFolder - createFolder"))
}

// RenameFolder is the resolver for the renameFolder field.
func (r *mutationResolver) RenameFolder(ctx context.Context, folderID string, name string) (*model.Folder, error) {
	panic(fmt.Errorf("not implemented: RenameFolder - renameFolder"))
}

// MoveFolder is the resolver for the moveFolder field.
func (r *mutationResolver) MoveFolder(ctx context.Context, folderID string, parentFolderID *string) (*model.Folder, error) {
	panic(fmt.Errorf("not implemented: MoveFolder - moveFolder"))
}

// DeleteFolder is the resolver for the deleteFolder field.
func (r *mutationResolver) DeleteFolder(ctx context.Context, folderID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteFolder - deleteFolder"))
}

// CreateFile is the resolver for the createFile field.
func (r *mutationResolver) CreateFile(ctx context.Context, input model.CreateFileInput) (*model.File, error) {
	panic(fmt.Errorf("not implemented: CreateFile - createFile"))
}

// RenameFile is the resolver for the renameFile field.
func (r *mutationResolver) RenameFile(ctx context.Context, fileID string, name string) (*model.File, error) {
	panic(fmt.Errorf("not implemented: RenameFile - renameFile"))
}

// MoveFile is the resolver for the moveFile field.
func (r *mutationResolver) MoveFile(ctx context.Context, input model.MoveFileInput) (*model.File, error) {
	panic(fmt.Errorf("not implemented: MoveFile - moveFile"))
}

// DeleteFile is the resolver for the deleteFile field.
func (r *mutationResolver) DeleteFile(ctx context.Context, fileID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteFile - deleteFile"))
}

// ShareFile is the resolver for the shareFile field.
func (r *mutationResolver) ShareFile(ctx context.Context, input model.ShareFileInput) (*model.FileShare, error) {
	panic(fmt.Errorf("not implemented: ShareFile - shareFile"))
}

// UpdateFileSharePermission is the resolver for the updateFileSharePermission field.
func (r *mutationResolver) UpdateFileSharePermission(ctx context.Context, fileShareID string, permission model.FilePermission) (*model.FileShare, error) {
	panic(fmt.Errorf("not implemented: UpdateFileSharePermission - updateFileSharePermission"))
}

// DeleteFileShare is the resolver for the deleteFileShare field.
func (r *mutationResolver) DeleteFileShare(ctx context.Context, fileShareID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteFileShare - deleteFileShare"))
}

// SetFileFavorite is the resolver for the setFileFavorite field.
func (r *mutationResolver) SetFileFavorite(ctx context.Context, input model.SetFileFavoriteInput) (*model.FilePreference, error) {
	panic(fmt.Errorf("not implemented: SetFileFavorite - setFileFavorite"))
}

// Folder is the resolver for the folder field.
func (r *queryResolver) Folder(ctx context.Context, id string) (*model.Folder, error) {
	panic(fmt.Errorf("not implemented: Folder - folder"))
}

// Folders is the resolver for the folders field.
func (r *queryResolver) Folders(ctx context.Context, projectID *string) ([]*model.Folder, error) {
	panic(fmt.Errorf("not implemented: Folders - folders"))
}

// FolderContents is the resolver for the folderContents field.
func (r *queryResolver) FolderContents(ctx context.Context, folderID *string, projectID *string) ([]model.FolderItem, error) {
	panic(fmt.Errorf("not implemented: FolderContents - folderContents"))
}

// FolderPath is the resolver for the folderPath field.
func (r *queryResolver) FolderPath(ctx context.Context, folderID string) ([]*model.Folder, error) {
	panic(fmt.Errorf("not implemented: FolderPath - folderPath"))
}

// RootFolders is the resolver for the rootFolders field.
func (r *queryResolver) RootFolders(ctx context.Context, projectID string) ([]*model.Folder, error) {
	panic(fmt.Errorf("not implemented: RootFolders - rootFolders"))
}

// File is the resolver for the file field.
func (r *queryResolver) File(ctx context.Context, id string) (*model.File, error) {
	panic(fmt.Errorf("not implemented: File - file"))
}

// Files is the resolver for the files field.
func (r *queryResolver) Files(ctx context.Context, projectID *string, folderID *string) ([]*model.File, error) {
	panic(fmt.Errorf("not implemented: Files - files"))
}

// RootFiles is the resolver for the rootFiles field.
func (r *queryResolver) RootFiles(ctx context.Context, projectID string) ([]*model.File, error) {
	panic(fmt.Errorf("not implemented: RootFiles - rootFiles"))
}

// FavoriteFiles is the resolver for the favoriteFiles field.
func (r *queryResolver) FavoriteFiles(ctx context.Context, userID string, projectID *string) ([]*model.File, error) {
	panic(fmt.Errorf("not implemented: FavoriteFiles - favoriteFiles"))
}

// FileShare is the resolver for the fileShare field.
func (r *queryResolver) FileShare(ctx context.Context, id string) (*model.FileShare, error) {
	panic(fmt.Errorf("not implemented: FileShare - fileShare"))
}

// FileShares is the resolver for the fileShares field.
func (r *queryResolver) FileShares(ctx context.Context, fileID string) ([]*model.FileShare, error) {
	panic(fmt.Errorf("not implemented: FileShares - fileShares"))
}

// SharedWithMe is the resolver for the sharedWithMe field.
func (r *queryResolver) SharedWithMe(ctx context.Context, userID string) ([]*model.FileShare, error) {
	panic(fmt.Errorf("not implemented: SharedWithMe - sharedWithMe"))
}
