package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"example/hello/graph/helpers"
	"example/hello/graph/model"
	"example/hello/internal/database"

	"github.com/jackc/pgx/v5/pgtype"
)

// CreateFlowchart is the resolver for the createFlowchart field.
func (r *mutationResolver) CreateFlowchart(ctx context.Context, input model.CreateFlowchartInput) (*model.Flowchart, error) {
	userID, err := currentUserID(ctx)
	if err != nil {
		return nil, err
	}

	projectID, err := parseUUID(input.ProjectID)
	if err != nil {
		return nil, err
	}

	if err := r.requireProjectMember(ctx, projectID); err != nil {
		return nil, err
	}

	generatedBy := pgtype.UUID{Bytes: userID.Bytes, Valid: true}
	if input.GeneratedByID != nil {
		generatedBy, err = parseUUID(*input.GeneratedByID)
		if err != nil {
			return nil, err
		}
	}

	var sourceChatID pgtype.UUID
	if input.SourceChatID != nil {
		sourceChatID, err = parseUUID(*input.SourceChatID)
		if err != nil {
			return nil, err
		}
	}

	generatedByAI := false
	if input.GeneratedByAi != nil {
		generatedByAI = *input.GeneratedByAi
	}

	status := database.FlowchartStatusDRAFT
	if input.Status != nil {
		status = database.FlowchartStatus(*input.Status)
	}

	flowchart, err := r.App.Services.Flowchart.CreateFlowchart(
		ctx,
		database.CreateFlowchartParams{
			ProjectID:     projectID,
			Name:          input.Name,
			Data:          []byte(input.Data),
			GeneratedBy:   generatedBy,
			GeneratedByAi: pgtype.Bool{Bool: generatedByAI, Valid: true},
			Status:        status,
			SourceChatID:  sourceChatID,
		},
	)
	if err != nil {
		return nil, err
	}

	return helpers.FlowchartToModel(flowchart), nil
}

// UpdateFlowchart is the resolver for the updateFlowchart field.
func (r *mutationResolver) UpdateFlowchart(ctx context.Context, id string, input model.UpdateFlowchartInput) (*model.Flowchart, error) {
	if _, err := currentUserID(ctx); err != nil {
		return nil, err
	}

	flowchartID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	existing, err := r.App.Services.Flowchart.GetFlowchartByID(ctx, flowchartID)
	if err != nil {
		return nil, err
	}
	if err := r.requireProjectMember(ctx, existing.ProjectID); err != nil {
		return nil, err
	}

	name := existing.Name
	if input.Name != nil {
		name = *input.Name
	}

	data := existing.Data
	if input.Data != nil {
		data = []byte(*input.Data)
	}

	generatedBy := existing.GeneratedBy
	if input.GeneratedBy != nil {
		generatedBy, err = parseUUID(*input.GeneratedBy)
		if err != nil {
			return nil, err
		}
	}

	generatedByAI := existing.GeneratedByAi
	if input.GeneratedByAi != nil {
		generatedByAI = pgtype.Bool{Bool: *input.GeneratedByAi, Valid: true}
	}

	status := existing.Status
	if input.Status != nil {
		status = database.FlowchartStatus(*input.Status)
	}

	sourceChatID := existing.SourceChatID
	if input.SourceChatID != nil {
		sourceChatID, err = parseUUID(*input.SourceChatID)
		if err != nil {
			return nil, err
		}
	}

	flowchart, err := r.App.Services.Flowchart.UpdateFlowchart(
		ctx,
		database.UpdateFlowchartParams{
			ID:            flowchartID,
			Name:          name,
			Data:          data,
			GeneratedBy:   generatedBy,
			GeneratedByAi: generatedByAI,
			Status:        status,
			SourceChatID:  sourceChatID,
		},
	)
	if err != nil {
		return nil, err
	}

	return helpers.FlowchartToModel(flowchart), nil
}

// DeleteFlowchart is the resolver for the deleteFlowchart field.
func (r *mutationResolver) DeleteFlowchart(ctx context.Context, id string) (bool, error) {
	if _, err := currentUserID(ctx); err != nil {
		return false, err
	}

	flowchartID, err := parseUUID(id)
	if err != nil {
		return false, err
	}

	existing, err := r.App.Services.Flowchart.GetFlowchartByID(ctx, flowchartID)
	if err != nil {
		return false, err
	}
	if err := r.requireProjectMember(ctx, existing.ProjectID); err != nil {
		return false, err
	}

	err = r.App.Services.Flowchart.DeleteFlowchart(
		ctx,
		flowchartID,
	)
	if err != nil {
		return false, err
	}

	return true, nil
}

// Flowchart is the resolver for the flowchart field.
func (r *queryResolver) Flowchart(ctx context.Context, id string) (*model.Flowchart, error) {
	flowchartID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	flowchart, err := r.App.Services.Flowchart.GetFlowchartByID(
		ctx,
		flowchartID,
	)
	if err != nil {
		return nil, err
	}
	if err := r.requireProjectMember(ctx, flowchart.ProjectID); err != nil {
		return nil, err
	}

	project, err := r.App.Services.Project.GetProjectByID(
		ctx,
		flowchart.ProjectID,
	)
	if err != nil {
		return nil, err
	}

	result := helpers.FlowchartToModel(flowchart)
	result.Project = helpers.ProjectToModel(project)

	return result, nil
}

// Flowcharts is the resolver for the flowcharts field.
func (r *queryResolver) Flowcharts(ctx context.Context, projectID string) ([]*model.Flowchart, error) {
	projId, err := parseUUID(projectID)
	if err != nil {
		return nil, err
	}
	if err := r.requireProjectMember(ctx, projId); err != nil {
		return nil, err
	}

	flowcharts, err := r.App.Services.Flowchart.GetFlowchartsByProjectID(ctx, projId)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Flowchart, len(flowcharts))
	for i, fc := range flowcharts {
		result[i] = helpers.FlowchartToModel(fc)
	}
	return result, nil
}
