package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"example/hello/graph/model"
	"example/hello/internal/database"
)

// CreateFlowchart is the resolver for the createFlowchart field.
func (r *mutationResolver) CreateFlowchart(ctx context.Context, input model.CreateFlowchartInput) (*model.Flowchart, error) {
	projectID, err := parseUUID(input.ProjectID)
	if err != nil {
		return nil, err
	}

	flowchart, err := r.App.Services.Flowchart.CreateFlowchart(
		ctx,
		database.CreateFlowchartParams{
			ProjectID: projectID,
			Name:      input.Name,
			Data:      []byte(input.Data),
		},
	)
	if err != nil {
		return nil, err
	}

	return &model.Flowchart{
		ID:     flowchart.ID.String(),
		Name:   flowchart.Name,
		Data:   string(flowchart.Data),
		Status: model.FlowchartStatus(flowchart.Status),
	}, nil
}

// UpdateFlowchart is the resolver for the updateFlowchart field.
func (r *mutationResolver) UpdateFlowchart(ctx context.Context, id string, input model.UpdateFlowchartInput) (*model.Flowchart, error) {
	flowchartID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	flowchart, err := r.App.Services.Flowchart.UpdateFlowchart(
		ctx,
		database.UpdateFlowchartParams{
			ID:   flowchartID,
			Name: *input.Name,
			Data: []byte(*input.Data),
		},
	)
	if err != nil {
		return nil, err
	}

	return &model.Flowchart{
		ID:     flowchart.ID.String(),
		Name:   flowchart.Name,
		Data:   string(flowchart.Data),
		Status: model.FlowchartStatus(flowchart.Status),
	}, nil
}

// DeleteFlowchart is the resolver for the deleteFlowchart field.
func (r *mutationResolver) DeleteFlowchart(ctx context.Context, id string) (bool, error) {
	flowchartID, err := parseUUID(id)
	if err != nil {
		return false, err
	}

	err = r.App.Services.Flowchart.DeleteFlowchart(
		ctx,
		flowchartID,
	)
	if err != nil {
		return false, err
	}

	return true, nil
}

// Flowchart is the resolver for the flowchart field.
func (r *queryResolver) Flowchart(ctx context.Context, id string) (*model.Flowchart, error) {
	flowchartID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	flowchart, err := r.App.Services.Flowchart.GetFlowchartByID(
		ctx,
		flowchartID,
	)
	if err != nil {
		return nil, err
	}

	project, err := r.App.Services.Project.GetProjectByID(
		ctx,
		flowchart.ProjectID,
	)
	if err != nil {
		return nil, err
	}

	var description *string

	if project.Description.Valid {
		description = &project.Description.String
	}

	return &model.Flowchart{
		ID:   flowchart.ID.String(),
		Name: flowchart.Name,
		Data: string(flowchart.Data),

		Status: model.FlowchartStatus(flowchart.Status),

		Project: &model.Project{
			ID:          project.ID.String(),
			Name:        project.Name,
			Description: description,
		},
	}, nil
}

// Flowcharts is the resolver for the flowcharts field.
func (r *queryResolver) Flowcharts(ctx context.Context, projectID string) ([]*model.Flowchart, error) {
	projId, err := parseUUID(projectID)
	if err != nil {
		return nil, err
	}
	flowcharts, err := r.App.Services.Flowchart.GetFlowchartsByProjectID(ctx, projId)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Flowchart, len(flowcharts))
	for i, fc := range flowcharts {
		result[i] = &model.Flowchart{
			ID:     fc.ID.String(),
			Name:   fc.Name,
			Data:   string(fc.Data),
			Status: model.FlowchartStatus(fc.Status),
		}
	}
	return result, nil
}
