package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"example/hello/graph/model"
	"fmt"
)

// CreateFlowchart is the resolver for the createFlowchart field.
func (r *mutationResolver) CreateFlowchart(ctx context.Context, input model.CreateFlowchartInput) (*model.Flowchart, error) {
	panic(fmt.Errorf("not implemented: CreateFlowchart - createFlowchart"))
}

// UpdateFlowchart is the resolver for the updateFlowchart field.
func (r *mutationResolver) UpdateFlowchart(ctx context.Context, id string, input model.UpdateFlowchartInput) (*model.Flowchart, error) {
	panic(fmt.Errorf("not implemented: UpdateFlowchart - updateFlowchart"))
}

// DeleteFlowchart is the resolver for the deleteFlowchart field.
func (r *mutationResolver) DeleteFlowchart(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteFlowchart - deleteFlowchart"))
}

// Flowchart is the resolver for the flowchart field.
func (r *queryResolver) Flowchart(ctx context.Context, id string) (*model.Flowchart, error) {
	panic(fmt.Errorf("not implemented: Flowchart - flowchart"))
}

// Flowcharts is the resolver for the flowcharts field.
func (r *queryResolver) Flowcharts(ctx context.Context, projectID string) ([]*model.Flowchart, error) {
	panic(fmt.Errorf("not implemented: Flowcharts - flowcharts"))
}
