package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"example/hello/graph/model"
	"fmt"
)

// CreateOAuthAccount is the resolver for the createOAuthAccount field.
func (r *mutationResolver) CreateOAuthAccount(ctx context.Context, input model.CreateOAuthAccountInput) (*model.OAuthAccount, error) {
	panic(fmt.Errorf("not implemented: CreateOAuthAccount - createOAuthAccount"))
}

// DeleteOAuthAccount is the resolver for the deleteOAuthAccount field.
func (r *mutationResolver) DeleteOAuthAccount(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteOAuthAccount - deleteOAuthAccount"))
}
