package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"example/hello/graph"
	"example/hello/graph/helpers"
	"example/hello/graph/model"
	"example/hello/internal/apperrors"
	"example/hello/internal/database"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (*model.Project, error) {
	userId, err := currentUserID(ctx)
	if err != nil {
		return nil, err
	}
	var description pgtype.Text

	if input.Description != nil {
		description = pgtype.Text{
			String: *input.Description,
			Valid:  true,
		}
	}

	project, err := r.App.Services.Project.CreateProject(
		ctx,
		database.CreateProjectParams{
			OwnerID:     userId,
			Name:        input.Name,
			Description: description,
			Visibility:  database.ProjectVisibility(input.Visibility),
		},
	)
	if err != nil {
		return nil, err
	}

	result := helpers.ProjectToModel(project)

	// Load owner because Project.Owner is required by GraphQL.
	user, err := r.App.Services.User.GetUserByID(ctx, userId)
	if err != nil {
		return nil, err
	}

	result.Owner = &model.User{
		ID:       user.ID.String(),
		Username: user.Username,
		Email:    user.Email,
	}

	return result, nil
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, id string, input model.UpdateProjectInput) (*model.Project, error) {
	projectID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	if err := r.requireProjectMember(ctx, projectID); err != nil {
		return nil, err
	}

	// If your GraphQL schema makes Name optional.
	// If Name is actually required, you can use input.Name directly.
	if input.Name == nil {
		return nil, fmt.Errorf("project name is required")
	}

	var description pgtype.Text

	if input.Description != nil {
		description = pgtype.Text{
			String: *input.Description,
			Valid:  true,
		}
	}

	project, err := r.App.Services.Project.UpdateProject(
		ctx,
		database.UpdateProjectParams{
			ID:          projectID,
			Name:        *input.Name,
			Description: description,
		},
	)
	if err != nil {
		return nil, err
	}

	result := helpers.ProjectToModel(project)

	// Project.Owner is required in GraphQL.
	user, err := r.App.Services.User.GetUserByID(ctx, project.OwnerID)
	if err != nil {
		return nil, err
	}

	result.Owner = &model.User{
		ID:       user.ID.String(),
		Username: user.Username,
		Email:    user.Email,
	}

	return result, nil
}

// ArchiveProject is the resolver for the archiveProject field.
func (r *mutationResolver) ArchiveProject(ctx context.Context, projectID string) (bool, error) {
	id, err := parseUUID(projectID)
	if err != nil {
		return false, err
	}

	if err := r.requireProjectOwner(ctx, id); err != nil {
		return false, err
	}

	if err := r.App.Services.Project.ArchiveProject(ctx, id); err != nil {
		return false, err
	}

	return true, nil
}

// RestoreProject is the resolver for the restoreProject field.
func (r *mutationResolver) RestoreProject(ctx context.Context, projectID string) (bool, error) {
	id, err := parseUUID(projectID)
	if err != nil {
		return false, err
	}

	if err := r.requireProjectOwner(ctx, id); err != nil {
		return false, err
	}

	if err := r.App.Services.Project.RestoreProject(ctx, id); err != nil {
		return false, err
	}

	return true, nil
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, id string) (bool, error) {
	projectID, err := parseUUID(id)
	if err != nil {
		return false, err
	}

	if err := r.requireProjectOwner(ctx, projectID); err != nil {
		return false, err
	}

	if err := r.App.Services.Project.DeleteProject(ctx, projectID); err != nil {
		return false, err
	}

	return true, nil
}

// TransferProjectOwnership is the resolver for the transferProjectOwnership field.
func (r *mutationResolver) TransferProjectOwnership(ctx context.Context, input model.TransferProjectOwnershipInput) (*model.Project, error) {
	projectID, err := parseUUID(input.ProjectID)
	if err != nil {
		return nil, err
	}

	if err := r.requireProjectOwner(ctx, projectID); err != nil {
		return nil, err
	}

	ownerID, err := parseUUID(input.OwnerID)
	if err != nil {
		return nil, err
	}

	project, err := r.App.Services.Project.TransferOwnership(
		ctx,
		database.TransferOwnershipParams{
			ID:      projectID,
			OwnerID: ownerID,
		},
	)
	if err != nil {
		return nil, err
	}

	result := helpers.ProjectToModel(project)

	user, err := r.App.Services.User.GetUserByID(ctx, ownerID)
	if err != nil {
		return nil, err
	}

	result.Owner = &model.User{
		ID:       user.ID.String(),
		Username: user.Username,
		Email:    user.Email,
	}

	return result, nil
}

// AddProjectMember is the resolver for the addProjectMember field.
func (r *mutationResolver) AddProjectMember(ctx context.Context, input model.AddProjectMemberInput) (*model.ProjectMember, error) {
	projectID, err := parseUUID(input.ProjectID)
	if err != nil {
		return nil, err
	}

	if err := r.requireProjectOwner(ctx, projectID); err != nil {
		return nil, err
	}

	userID, err := parseUUID(input.UserID)
	if err != nil {
		return nil, err
	}

	member, err := r.App.Services.Project.AddProjectMember(
		ctx,
		database.AddProjectMemberParams{
			ProjectID: projectID,
			UserID:    userID,
			Role:      helpers.ProjectMemberRoleToDB(input.Role),
		},
	)
	if err != nil {
		return nil, err
	}

	return helpers.ProjectMemberToModel(member), nil
}

// UpdateProjectMemberRole is the resolver for the updateProjectMemberRole field.
func (r *mutationResolver) UpdateProjectMemberRole(ctx context.Context, input model.UpdateProjectMemberRoleInput) (*model.ProjectMember, error) {
	projectID, err := parseUUID(input.ProjectID)
	if err != nil {
		return nil, err
	}

	if err := r.requireProjectOwner(ctx, projectID); err != nil {
		return nil, err
	}

	userID, err := parseUUID(input.UserID)
	if err != nil {
		return nil, err
	}

	member, err := r.App.Services.Project.UpdateProjectMemberRole(
		ctx,
		database.UpdateProjectMemberRoleParams{
			ProjectID: projectID,
			UserID:    userID,
			Role:      helpers.ProjectMemberRoleToDB(input.Role),
		},
	)
	if err != nil {
		return nil, err
	}

	return helpers.ProjectMemberToModel(member), nil
}

// RemoveProjectMember is the resolver for the removeProjectMember field.
func (r *mutationResolver) RemoveProjectMember(ctx context.Context, projectID string, userID string) (bool, error) {
	pID, err := parseUUID(projectID)
	if err != nil {
		return false, err
	}

	if err := r.requireProjectOwner(ctx, pID); err != nil {
		return false, err
	}

	uID, err := parseUUID(userID)
	if err != nil {
		return false, err
	}

	err = r.App.Services.Project.RemoveProjectMember(
		ctx,
		database.RemoveProjectMemberParams{
			ProjectID: pID,
			UserID:    uID,
		},
	)
	if err != nil {
		return false, err
	}

	return true, nil
}

// Members is the resolver for the members field.
func (r *projectResolver) Members(ctx context.Context, obj *model.Project) ([]*model.ProjectMember, error) {
	projectID, err := parseUUID(obj.ID)
	if err != nil {
		return nil, err
	}

	members, err := r.App.Services.Project.GetProjectMembers(ctx, projectID)
	if err != nil {
		return nil, err
	}

	result := make([]*model.ProjectMember, 0, len(members))
	for _, member := range members {
		result = append(result, helpers.ProjectMemberToModel(member))
	}
	return result, nil
}

// Folders is the resolver for the folders field.
func (r *projectResolver) Folders(ctx context.Context, obj *model.Project) ([]*model.Folder, error) {
	projectID, err := parseUUID(obj.ID)
	if err != nil {
		return nil, err
	}

	folders, err := r.App.Services.File.GetFoldersByProjectID(ctx, projectID)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Folder, 0, len(folders))
	for _, folder := range folders {
		result = append(result, helpers.FolderToModel(folder))
	}
	return result, nil
}

// Files is the resolver for the files field.
func (r *projectResolver) Files(ctx context.Context, obj *model.Project) ([]*model.ProjectFile, error) {
	projectID, err := parseUUID(obj.ID)
	if err != nil {
		return nil, err
	}

	files, err := r.App.Services.File.GetFilesByProjectID(ctx, projectID)
	if err != nil {
		return nil, err
	}

	result := make([]*model.ProjectFile, 0, len(files))
	for _, file := range files {
		result = append(result, &model.ProjectFile{
			Project: &model.Project{ID: obj.ID},
			File:    helpers.FileToModel(file),
		})
	}
	return result, nil
}

// Chats is the resolver for the chats field.
func (r *projectResolver) Chats(ctx context.Context, obj *model.Project) ([]*model.Chat, error) {
	projectID, err := parseUUID(obj.ID)
	if err != nil {
		return nil, err
	}

	chats, err := r.App.Services.Chat.GetChatsByProjectID(ctx, projectID)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Chat, 0, len(chats))
	for _, chat := range chats {
		result = append(result, helpers.ChatToModel(chat))
	}
	return result, nil
}

// Reports is the resolver for the reports field.
func (r *projectResolver) Reports(ctx context.Context, obj *model.Project) ([]*model.Report, error) {
	projectID, err := parseUUID(obj.ID)
	if err != nil {
		return nil, err
	}

	reports, err := r.App.Services.Report.GetReportsByProjectID(ctx, projectID)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Report, 0, len(reports))
	for _, report := range reports {
		result = append(result, helpers.ReportToModel(helpers.ReportRow(report)))
	}
	return result, nil
}

// Flowcharts is the resolver for the flowcharts field.
func (r *projectResolver) Flowcharts(ctx context.Context, obj *model.Project) ([]*model.Flowchart, error) {
	projectID, err := parseUUID(obj.ID)
	if err != nil {
		return nil, err
	}

	flowcharts, err := r.App.Services.Flowchart.GetFlowchartsByProjectID(ctx, projectID)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Flowchart, 0, len(flowcharts))
	for _, flowchart := range flowcharts {
		result = append(result, helpers.FlowchartToModel(flowchart))
	}
	return result, nil
}

// ActivityLogs is the resolver for the activityLogs field.
func (r *projectResolver) ActivityLogs(ctx context.Context, obj *model.Project) ([]*model.ActivityLog, error) {
	projectID, err := parseUUID(obj.ID)
	if err != nil {
		return nil, err
	}

	activities, err := r.App.Services.Activity.GetActivityLogsByProjectID(ctx, projectID)
	if err != nil {
		return nil, err
	}

	result := make([]*model.ActivityLog, 0, len(activities))
	for _, activity := range activities {
		result = append(result, helpers.ActivityLogToModel(activity))
	}
	return result, nil
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*model.Project, error) {
	projectID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}

	if err := r.requireProjectMember(ctx, projectID); err != nil {
		return nil, err
	}

	project, err := r.App.Services.Project.GetProjectByID(ctx, projectID)
	if err != nil {
		return nil, err
	}

	result := helpers.ProjectToModel(project)

	// Project.Owner is required.
	user, err := r.App.Services.User.GetUserByID(ctx, project.OwnerID)
	if err != nil {
		return nil, err
	}

	result.Owner = &model.User{
		ID:       user.ID.String(),
		Username: user.Username,
		Email:    user.Email,
	}

	return result, nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context) ([]*model.Project, error) {
	userId, err := currentUserID(ctx)
	if err != nil {
		return nil, err
	}
	projects, err := r.App.Services.Project.GetProjectsForUser(ctx, userId)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Project, 0, len(projects))

	for _, project := range projects {
		result = append(result, helpers.ProjectToModel(project))
	}

	return result, nil
}

// ProjectsByOwner is the resolver for the projectsByOwner field.
func (r *queryResolver) ProjectsByOwner(ctx context.Context, ownerID string) ([]*model.Project, error) {
	callerID, err := currentUserID(ctx)
	if err != nil {
		return nil, err
	}

	id, err := parseUUID(ownerID)
	if err != nil {
		return nil, err
	}

	// Without this, any authenticated user could enumerate any other
	// user's owned projects by guessing their ID.
	if id != callerID {
		return nil, apperrors.ForbiddenError("cannot list another user's owned projects")
	}

	projects, err := r.App.Services.Project.GetProjectsByOwnerID(ctx, id)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Project, 0, len(projects))

	for _, project := range projects {
		result = append(result, helpers.ProjectToModel(project))
	}

	return result, nil
}

// ProjectsForUser is the resolver for the projectsForUser field.
func (r *queryResolver) ProjectsForUser(ctx context.Context, userID string) ([]*model.Project, error) {
	callerID, err := currentUserID(ctx)
	if err != nil {
		return nil, err
	}

	id, err := parseUUID(userID)
	if err != nil {
		return nil, err
	}

	if id != callerID {
		return nil, apperrors.ForbiddenError("cannot list another user's projects")
	}

	projects, err := r.App.Services.Project.GetProjectsForUser(ctx, id)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Project, 0, len(projects))

	for _, project := range projects {
		result = append(result, helpers.ProjectToModel(project))
	}

	return result, nil
}

// ArchivedProjectsByOwner is the resolver for the archivedProjectsByOwner field.
func (r *queryResolver) ArchivedProjectsByOwner(ctx context.Context, ownerID string) ([]*model.Project, error) {
	callerID, err := currentUserID(ctx)
	if err != nil {
		return nil, err
	}

	id, err := parseUUID(ownerID)
	if err != nil {
		return nil, err
	}

	if id != callerID {
		return nil, apperrors.ForbiddenError("cannot list another user's owned projects")
	}

	projects, err := r.App.Services.Project.GetArchivedProjectsByOwner(ctx, id)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Project, 0, len(projects))

	for _, project := range projects {
		result = append(result, helpers.ProjectToModel(project))
	}

	return result, nil
}

// ArchivedProjectsForUser is the resolver for the archivedProjectsForUser field.
func (r *queryResolver) ArchivedProjectsForUser(ctx context.Context, userID string) ([]*model.Project, error) {
	callerID, err := currentUserID(ctx)
	if err != nil {
		return nil, err
	}

	id, err := parseUUID(userID)
	if err != nil {
		return nil, err
	}

	if id != callerID {
		return nil, apperrors.ForbiddenError("cannot list another user's projects")
	}

	projects, err := r.App.Services.Project.GetArchivedProjectsForUser(ctx, id)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Project, 0, len(projects))

	for _, project := range projects {
		result = append(result, helpers.ProjectToModel(project))
	}

	return result, nil
}

// ProjectMembers is the resolver for the projectMembers field.
func (r *queryResolver) ProjectMembers(ctx context.Context, projectID string) ([]*model.ProjectMember, error) {
	id, err := parseUUID(projectID)
	if err != nil {
		return nil, err
	}

	if err := r.requireProjectMember(ctx, id); err != nil {
		return nil, err
	}

	members, err := r.App.Services.Project.GetProjectMembers(ctx, id)
	if err != nil {
		return nil, err
	}

	result := make([]*model.ProjectMember, 0, len(members))

	for _, member := range members {
		result = append(result, helpers.ProjectMemberToModel(member))
	}

	return result, nil
}

// Project returns graph.ProjectResolver implementation.
func (r *Resolver) Project() graph.ProjectResolver { return &projectResolver{r} }

type projectResolver struct{ *Resolver }
