package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"example/hello/graph/model"
	"fmt"
)

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (*model.Project, error) {
	panic(fmt.Errorf("not implemented: CreateProject - createProject"))
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, input model.UpdateProjectInput) (*model.Project, error) {
	panic(fmt.Errorf("not implemented: UpdateProject - updateProject"))
}

// ArchiveProject is the resolver for the archiveProject field.
func (r *mutationResolver) ArchiveProject(ctx context.Context, projectID string) (bool, error) {
	panic(fmt.Errorf("not implemented: ArchiveProject - archiveProject"))
}

// RestoreProject is the resolver for the restoreProject field.
func (r *mutationResolver) RestoreProject(ctx context.Context, projectID string) (bool, error) {
	panic(fmt.Errorf("not implemented: RestoreProject - restoreProject"))
}

// AddProjectMember is the resolver for the addProjectMember field.
func (r *mutationResolver) AddProjectMember(ctx context.Context, input model.AddProjectMemberInput) (*model.ProjectMember, error) {
	panic(fmt.Errorf("not implemented: AddProjectMember - addProjectMember"))
}

// UpdateProjectMemberRole is the resolver for the updateProjectMemberRole field.
func (r *mutationResolver) UpdateProjectMemberRole(ctx context.Context, input model.UpdateProjectMemberRoleInput) (*model.ProjectMember, error) {
	panic(fmt.Errorf("not implemented: UpdateProjectMemberRole - updateProjectMemberRole"))
}

// RemoveProjectMember is the resolver for the removeProjectMember field.
func (r *mutationResolver) RemoveProjectMember(ctx context.Context, projectID string, userID string) (bool, error) {
	panic(fmt.Errorf("not implemented: RemoveProjectMember - removeProjectMember"))
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*model.Project, error) {
	panic(fmt.Errorf("not implemented: Project - project"))
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context) ([]*model.Project, error) {
	panic(fmt.Errorf("not implemented: Projects - projects"))
}

// ArchivedProjects is the resolver for the archivedProjects field.
func (r *queryResolver) ArchivedProjects(ctx context.Context) ([]*model.Project, error) {
	panic(fmt.Errorf("not implemented: ArchivedProjects - archivedProjects"))
}

// ProjectMembers is the resolver for the projectMembers field.
func (r *queryResolver) ProjectMembers(ctx context.Context, projectID string) ([]*model.ProjectMember, error) {
	panic(fmt.Errorf("not implemented: ProjectMembers - projectMembers"))
}
