package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"example/hello/graph/model"
	"fmt"
)

// CreateReport is the resolver for the createReport field.
func (r *mutationResolver) CreateReport(ctx context.Context, input model.CreateReportInput) (*model.Report, error) {
	panic(fmt.Errorf("not implemented: CreateReport - createReport"))
}

// UpdateReport is the resolver for the updateReport field.
func (r *mutationResolver) UpdateReport(ctx context.Context, id string, input model.UpdateReportInput) (*model.Report, error) {
	panic(fmt.Errorf("not implemented: UpdateReport - updateReport"))
}

// DeleteReport is the resolver for the deleteReport field.
func (r *mutationResolver) DeleteReport(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteReport - deleteReport"))
}

// Report is the resolver for the report field.
func (r *queryResolver) Report(ctx context.Context, id string) (*model.Report, error) {
	panic(fmt.Errorf("not implemented: Report - report"))
}

// Reports is the resolver for the reports field.
func (r *queryResolver) Reports(ctx context.Context, projectID string) ([]*model.Report, error) {
	panic(fmt.Errorf("not implemented: Reports - reports"))
}

// ReportsByChat is the resolver for the reportsByChat field.
func (r *queryResolver) ReportsByChat(ctx context.Context, sourceChatID string) ([]*model.Report, error) {
	panic(fmt.Errorf("not implemented: ReportsByChat - reportsByChat"))
}

// ReportsByGenerator is the resolver for the reportsByGenerator field.
func (r *queryResolver) ReportsByGenerator(ctx context.Context, generatedByID string) ([]*model.Report, error) {
	panic(fmt.Errorf("not implemented: ReportsByGenerator - reportsByGenerator"))
}

// ReportsByFormat is the resolver for the reportsByFormat field.
func (r *queryResolver) ReportsByFormat(ctx context.Context, format model.ReportFormat) ([]*model.Report, error) {
	panic(fmt.Errorf("not implemented: ReportsByFormat - reportsByFormat"))
}

// ReportsByStatus is the resolver for the reportsByStatus field.
func (r *queryResolver) ReportsByStatus(ctx context.Context, status model.ReportStatus) ([]*model.Report, error) {
	panic(fmt.Errorf("not implemented: ReportsByStatus - reportsByStatus"))
}

// AiReports is the resolver for the aiReports field.
func (r *queryResolver) AiReports(ctx context.Context, projectID string) ([]*model.Report, error) {
	panic(fmt.Errorf("not implemented: AiReports - aiReports"))
}
