package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"example/hello/graph/helpers"
	"example/hello/graph/model"
	"example/hello/internal/apperrors"
	"example/hello/internal/auth"
	"example/hello/internal/database"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

// CreateReport is the resolver for the createReport field.
func (r *mutationResolver) CreateReport(ctx context.Context, input model.CreateReportInput) (*model.Report, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return nil, apperrors.UnauthorizedError("authentication required")
	}

	projectID, err := parseUUID(input.ProjectID)
	if err != nil {
		return nil, fmt.Errorf("invalid project ID: %w", err)
	}

	generatedBy := pgtype.UUID{Bytes: userID.Bytes, Valid: true}
	if input.GeneratedBy != nil {
		generatedBy, err = parseUUID(*input.GeneratedBy)
		if err != nil {
			return nil, fmt.Errorf("invalid generated-by ID: %w", err)
		}
	}

	var sourceChatID pgtype.UUID
	if input.SourceChatID != nil {
		sourceChatID, err = parseUUID(*input.SourceChatID)
		if err != nil {
			return nil, fmt.Errorf("invalid source chat ID: %w", err)
		}
	}

	generatedByAI := false
	if input.GeneratedByAi != nil {
		generatedByAI = *input.GeneratedByAi
	}

	status := database.ReportStatusDRAFT
	if input.Status != nil {
		status = database.ReportStatus(*input.Status)
	}

	report, err := r.App.Services.Report.CreateReport(
		ctx,
		database.CreateReportParams{
			ProjectID:     projectID,
			Title:         input.Title,
			Content:       input.Content,
			Format:        database.ReportFormat(input.Format),
			GeneratedBy:   generatedBy,
			GeneratedByAi: pgtype.Bool{Bool: generatedByAI, Valid: true},
			Status:        status,
			SourceChatID:  sourceChatID,
		},
	)

	if err != nil {
		return nil, fmt.Errorf(
			"failed to create report: %w",
			err,
		)
	}

	return helpers.ReportToModel(helpers.ReportRow(report)), nil
}

// UpdateReport is the resolver for the updateReport field.
func (r *mutationResolver) UpdateReport(ctx context.Context, id string, input model.UpdateReportInput) (*model.Report, error) {
	if _, ok := auth.UserIDFromContext(ctx); !ok {
		return nil, apperrors.UnauthorizedError("authentication required")
	}

	reportID, err := parseUUID(id)
	if err != nil {
		return nil, fmt.Errorf(
			"invalid report ID: %w",
			err,
		)
	}

	existing, err := r.App.Services.Report.GetReportByID(ctx, reportID)
	if err != nil {
		return nil, fmt.Errorf(
			"failed to fetch report: %w",
			err,
		)
	}

	title := existing.Title
	if input.Title != nil {
		title = *input.Title
	}

	content := existing.Content
	if input.Content != nil {
		content = *input.Content
	}

	format := existing.Format
	if input.Format != nil {
		format = database.ReportFormat(*input.Format)
	}

	report, err := r.App.Services.Report.UpdateReport(
		ctx,
		database.UpdateReportParams{
			ID:      reportID,
			Title:   title,
			Content: content,
			Format:  format,
		},
	)

	if err != nil {
		return nil, fmt.Errorf(
			"failed to update report: %w",
			err,
		)
	}

	return helpers.ReportToModel(helpers.ReportRow(report)), nil
}

// DeleteReport is the resolver for the deleteReport field.
func (r *mutationResolver) DeleteReport(ctx context.Context, id string) (bool, error) {
	if _, ok := auth.UserIDFromContext(ctx); !ok {
		return false, apperrors.UnauthorizedError("authentication required")
	}

	reportID, err := parseUUID(id)
	if err != nil {
		return false, fmt.Errorf(
			"invalid report ID: %w",
			err,
		)
	}

	if err := r.App.Services.Report.DeleteReport(
		ctx,
		reportID,
	); err != nil {
		return false, fmt.Errorf(
			"failed to delete report: %w",
			err,
		)
	}

	return true, nil
}

// Report is the resolver for the report field.
func (r *queryResolver) Report(ctx context.Context, id string) (*model.Report, error) {
	reportID, err := parseUUID(id)
	if err != nil {
		return nil, fmt.Errorf(
			"invalid report ID: %w",
			err,
		)
	}

	report, err := r.App.Services.Report.GetReportByID(
		ctx,
		reportID,
	)
	if err != nil {
		return nil, fmt.Errorf(
			"failed to fetch report: %w",
			err,
		)
	}

	return helpers.ReportToModel(helpers.ReportRow(report)), nil
}

// Reports is the resolver for the reports field.
func (r *queryResolver) Reports(ctx context.Context, projectID string) ([]*model.Report, error) {
	id, err := parseUUID(projectID)
	if err != nil {
		return nil, fmt.Errorf(
			"invalid project ID: %w",
			err,
		)
	}

	reports, err := r.App.Services.Report.GetReportsByProjectID(
		ctx,
		id,
	)
	if err != nil {
		return nil, fmt.Errorf(
			"failed to fetch project reports: %w",
			err,
		)
	}

	result := make([]*model.Report, 0, len(reports))

	for _, report := range reports {
		result = append(result, helpers.ReportToModel(helpers.ReportRow(report)))
	}

	return result, nil
}

// ReportsByChat is the resolver for the reportsByChat field.
func (r *queryResolver) ReportsByChat(ctx context.Context, sourceChatID string) ([]*model.Report, error) {
	chatID, err := parseUUID(sourceChatID)
	if err != nil {
		return nil, fmt.Errorf(
			"invalid source chat ID: %w",
			err,
		)
	}

	reports, err := r.App.Services.Report.GetReportsByChatID(
		ctx,
		chatID,
	)
	if err != nil {
		return nil, fmt.Errorf(
			"failed to fetch reports by chat: %w",
			err,
		)
	}

	result := make([]*model.Report, 0, len(reports))

	for _, report := range reports {
		result = append(result, helpers.ReportToModel(helpers.ReportRow(report)))
	}

	return result, nil
}

// ReportsByGenerator is the resolver for the reportsByGenerator field.
func (r *queryResolver) ReportsByGenerator(ctx context.Context, generatedByID string) ([]*model.Report, error) {
	generatorID, err := parseUUID(generatedByID)
	if err != nil {
		return nil, fmt.Errorf(
			"invalid generated-by ID: %w",
			err,
		)
	}

	reports, err := r.App.Services.Report.GetReportsByGenerator(
		ctx,
		generatorID,
	)
	if err != nil {
		return nil, fmt.Errorf(
			"failed to fetch reports by generator: %w",
			err,
		)
	}

	result := make([]*model.Report, 0, len(reports))

	for _, report := range reports {
		result = append(result, helpers.ReportToModel(helpers.ReportRow(report)))
	}

	return result, nil
}

// ReportsByFormat is the resolver for the reportsByFormat field.
func (r *queryResolver) ReportsByFormat(ctx context.Context, format model.ReportFormat) ([]*model.Report, error) {
	reports, err := r.App.Services.Report.GetReportsByFormat(
		ctx,
		database.GetReportsByFormatParams{
			Format: database.ReportFormat(format),
		},
	)
	if err != nil {
		return nil, fmt.Errorf(
			"failed to fetch reports by format: %w",
			err,
		)
	}

	result := make([]*model.Report, 0, len(reports))

	for _, report := range reports {
		result = append(result, helpers.ReportToModel(helpers.ReportRow(report)))
	}

	return result, nil
}

// ReportsByStatus is the resolver for the reportsByStatus field.
func (r *queryResolver) ReportsByStatus(ctx context.Context, status model.ReportStatus) ([]*model.Report, error) {
	reports, err := r.App.Services.Report.GetReportsByStatus(
		ctx,
		database.GetReportsByStatusParams{
			Status: database.ReportStatus(status),
		},
	)
	if err != nil {
		return nil, fmt.Errorf(
			"failed to fetch reports by status: %w",
			err,
		)
	}

	result := make([]*model.Report, 0, len(reports))

	for _, report := range reports {
		result = append(result, helpers.ReportToModel(helpers.ReportRow(report)))
	}

	return result, nil
}

// AiReports is the resolver for the aiReports field.
func (r *queryResolver) AiReports(ctx context.Context, projectID string) ([]*model.Report, error) {
	id, err := parseUUID(projectID)
	if err != nil {
		return nil, fmt.Errorf(
			"invalid project ID: %w",
			err,
		)
	}

	reports, err := r.App.Services.Report.GetAIReports(
		ctx,
		id,
	)
	if err != nil {
		return nil, fmt.Errorf(
			"failed to fetch AI reports: %w",
			err,
		)
	}

	result := make([]*model.Report, 0, len(reports))

	for _, report := range reports {
		result = append(result, helpers.ReportToModel(helpers.ReportRow(report)))
	}

	return result, nil
}
