package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"example/hello/graph/model"
	"fmt"
)

// CreateReport is the resolver for the createReport field.
func (r *mutationResolver) CreateReport(ctx context.Context, input model.CreateReportInput) (*model.Report, error) {
	panic(fmt.Errorf("not implemented: CreateReport - createReport"))
}

// UpdateReport is the resolver for the updateReport field.
func (r *mutationResolver) UpdateReport(ctx context.Context, input model.UpdateReportInput) (*model.Report, error) {
	panic(fmt.Errorf("not implemented: UpdateReport - updateReport"))
}

// UpdateReportStatus is the resolver for the updateReportStatus field.
func (r *mutationResolver) UpdateReportStatus(ctx context.Context, reportID string, status model.ReportStatus) (*model.Report, error) {
	panic(fmt.Errorf("not implemented: UpdateReportStatus - updateReportStatus"))
}

// DeleteReport is the resolver for the deleteReport field.
func (r *mutationResolver) DeleteReport(ctx context.Context, reportID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteReport - deleteReport"))
}

// Report is the resolver for the report field.
func (r *queryResolver) Report(ctx context.Context, id string) (*model.Report, error) {
	panic(fmt.Errorf("not implemented: Report - report"))
}

// Reports is the resolver for the reports field.
func (r *queryResolver) Reports(ctx context.Context, projectID string) ([]*model.Report, error) {
	panic(fmt.Errorf("not implemented: Reports - reports"))
}
