package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"example/hello/graph"
	"fmt"
)

func (r *mutationResolver) Empty(ctx context.Context) (*bool, error) {
	panic(fmt.Errorf("not implemented: Empty - _empty"))
}

func (r *queryResolver) Empty(ctx context.Context) (*bool, error) {
	panic(fmt.Errorf("not implemented: Empty - _empty"))
}

func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
