package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"example/hello/graph"
	"example/hello/graph/helpers"
	"example/hello/graph/model"
	"example/hello/internal/apperrors"
	"example/hello/internal/auth"
	"example/hello/internal/database"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	dbUser, err := r.App.Services.User.CreateUser(ctx, database.CreateUserParams{
		Username: input.Username,
		Email:    input.Email,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create user: %w", err)
	}
	return helpers.UserToModel(dbUser), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*model.User, error) {
	userId, err := parseUUID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}
	dbUser, err := r.App.Services.User.UpdateUser(ctx, database.UpdateUserParams{
		ID:       userId,
		Username: input.Username,
		Email:    input.Email,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to update user: %w", err)
	}
	return helpers.UserToModel(dbUser), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	userId, err := parseUUID(id)
	if err != nil {
		return false, fmt.Errorf("invalid user ID: %w", err)
	}

	err = r.App.Services.User.DeleteUser(ctx, userId)
	if err != nil {
		return false, fmt.Errorf("failed to delete user: %w", err)
	}
	return true, nil
}

// UpdateUserProfile is the resolver for the updateUserProfile field.
func (r *mutationResolver) UpdateUserProfile(ctx context.Context, id string, input model.UpdateUserProfileInput) (*model.UserProfile, error) {
	userId, err := parseUUID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	// convert nullable GraphQL fields to pgtype.Text
	bio := pgtype.Text{}
	if input.Bio != nil {
		bio.String = *input.Bio
		bio.Valid = true
	}

	avatarUrl := pgtype.Text{}
	if input.AvatarURL != nil {
		avatarUrl.String = *input.AvatarURL
		avatarUrl.Valid = true
	}

	dbProfile, err := r.App.Services.User.UpdateUserProfile(ctx, database.UpdateUserProfileParams{
		UserID:    userId,
		FirstName: input.FirstName,
		LastName:  input.LastName,
		Bio:       bio,
		AvatarUrl: avatarUrl,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to update user profile: %w", err)
	}
	return helpers.UserProfileToModel(dbProfile), nil
}

// UpdateUserAvatar is the resolver for the updateUserAvatar field.
func (r *mutationResolver) UpdateUserAvatar(ctx context.Context, id string, input model.UpdateUserAvatarInput) (*model.UserProfile, error) {
	userId, err := parseUUID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	avatar := pgtype.Text{}
	if input.AvatarURL != "" {
		avatar.String = input.AvatarURL
		avatar.Valid = true
	}

	dbProfile, err := r.App.Services.User.UpdateUserAvatar(ctx, database.UpdateUserAvatarParams{
		UserID:    userId,
		AvatarUrl: avatar,
	})

	if err != nil {
		return nil, fmt.Errorf("failed to update user avatar: %w", err)
	}
	return helpers.UserProfileToModel(dbProfile), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user, ok := auth.UserFromContext(ctx)
	if !ok {
		return nil, nil
	}

	return helpers.UserToModel(user), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	userId, err := parseUUID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}
	user, err := r.App.Services.User.GetUserByID(ctx, userId)
	if err != nil {
		return nil, fmt.Errorf("failed to get user: %w", err)
	}
	return helpers.UserToModel(user), nil
}

// UserByEmail is the resolver for the userByEmail field.
func (r *queryResolver) UserByEmail(ctx context.Context, email string) (*model.User, error) {
	user, err := r.App.Services.User.GetUserByEmail(ctx, email)
	if err != nil {
		return nil, fmt.Errorf("failed to get user by email: %w", err)
	}
	return helpers.UserToModel(user), nil
}

// UserByUsername is the resolver for the userByUsername field.
func (r *queryResolver) UserByUsername(ctx context.Context, username string) (*model.User, error) {
	user, err := r.App.Services.User.GetUserByUsername(ctx, username)
	if err != nil {
		return nil, fmt.Errorf("failed to get user by username: %w", err)
	}
	return helpers.UserToModel(user), nil
}

// UserProfile is the resolver for the userProfile field.
func (r *queryResolver) UserProfile(ctx context.Context, userID string) (*model.UserProfile, error) {
	userId, err := parseUUID(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	profile, err := r.App.Services.User.GetUserProfile(ctx, userId)
	if err != nil {
		return nil, fmt.Errorf("failed to get user profile: %w", err)
	}
	return helpers.UserProfileToModel(profile), nil
}

// AllUsers is the resolver for the allUsers field.
func (r *queryResolver) AllUsers(ctx context.Context) ([]*model.User, error) {
	users, err := r.App.Services.User.GetAllUsers(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get all users: %w", err)
	}

	result := make([]*model.User, 0, len(users))
	for _, user := range users {
		result = append(result, helpers.UserToModel(user))
	}
	return result, nil
}

// Users is the resolver for the users field
func (r *queryResolver) Users(ctx context.Context, ids []string) ([]*model.User, error) {
	userIDs := make([]pgtype.UUID, 0, len(ids))

	for _, id := range ids {
		userID, err := parseUUID(id)
		if err != nil {
			return nil, fmt.Errorf("invalid user ID: %w", err)
		}
		userIDs = append(userIDs, userID)
	}

	users, err := r.App.Services.User.GetUsersByIDs(ctx, userIDs)
	if err != nil {
		return nil, fmt.Errorf("failed to get users: %w", err)
	}

	result := make([]*model.User, 0, len(users))
	for _, user := range users {
		result = append(result, helpers.UserToModel(user))
	}
	return result, nil
}

// Username is the resolver for the username field.
func (r *userResolver) Username(ctx context.Context, obj *model.User) (string, error) {
	// Already populated (a full user from UserToModel) - no lookup needed.
	if obj.Username != "" {
		return obj.Username, nil
	}

	user, err := r.loadUser(ctx, obj)
	if err != nil {
		return "", err
	}
	return user.Username, nil
}

// Email is the resolver for the email field.
func (r *userResolver) Email(ctx context.Context, obj *model.User) (string, error) {
	if obj.Email != "" {
		return obj.Email, nil
	}

	user, err := r.loadUser(ctx, obj)
	if err != nil {
		return "", err
	}
	return user.Email, nil
}

// Profile is the resolver for the profile field.
func (r *userResolver) Profile(ctx context.Context, obj *model.User) (*model.UserProfile, error) {
	userID, err := parseUUID(obj.ID)
	if err != nil {
		return nil, err
	}

	profile, err := r.App.Services.User.GetUserProfile(ctx, userID)
	if err != nil {
		if apperrors.IsCode(err, apperrors.NotFound) {
			return nil, nil
		}
		return nil, err
	}

	return helpers.UserProfileToModel(profile), nil
}

// OwnedProjects is the resolver for the ownedProjects field.
func (r *userResolver) OwnedProjects(ctx context.Context, obj *model.User) ([]*model.Project, error) {
	userID, err := parseUUID(obj.ID)
	if err != nil {
		return nil, err
	}

	projects, err := r.App.Services.Project.GetProjectsByOwnerID(ctx, userID)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Project, 0, len(projects))
	for _, project := range projects {
		result = append(result, helpers.ProjectToModel(project))
	}
	return result, nil
}

// ProjectMemberships is the resolver for the projectMemberships field.
func (r *userResolver) ProjectMemberships(ctx context.Context, obj *model.User) ([]*model.ProjectMember, error) {
	userID, err := parseUUID(obj.ID)
	if err != nil {
		return nil, err
	}

	// A membership record only exists for users explicitly added to a
	// project; an owner who was never separately added has none, so
	// each project the user can see is checked individually.
	projects, err := r.App.Services.Project.GetProjectsForUser(ctx, userID)
	if err != nil {
		return nil, err
	}

	result := make([]*model.ProjectMember, 0, len(projects))
	for _, project := range projects {
		member, err := r.App.Services.Project.GetProjectMember(ctx, project.ID, userID)
		if err != nil {
			if apperrors.IsCode(err, apperrors.Forbidden) {
				continue
			}
			return nil, err
		}
		result = append(result, helpers.ProjectMemberToModel(member))
	}
	return result, nil
}

// UploadedFiles is the resolver for the uploadedFiles field.
func (r *userResolver) UploadedFiles(ctx context.Context, obj *model.User) ([]*model.File, error) {
	// No query currently traces file_storage.uploaded_by back to a list
	// of files for a user; this needs a new repository query to back it.
	return []*model.File{}, nil
}

// SharedFiles is the resolver for the sharedFiles field.
func (r *userResolver) SharedFiles(ctx context.Context, obj *model.User) ([]*model.FileShare, error) {
	userID, err := parseUUID(obj.ID)
	if err != nil {
		return nil, err
	}

	shares, err := r.App.Services.File.GetFileSharesBySharedWith(ctx, userID)
	if err != nil {
		return nil, err
	}

	result := make([]*model.FileShare, 0, len(shares))
	for _, share := range shares {
		result = append(result, helpers.FileShareToModel(share))
	}
	return result, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *model.User) (*time.Time, error) {
	if !obj.CreatedAt.IsZero() {
		return &obj.CreatedAt, nil
	}

	user, err := r.loadUser(ctx, obj)
	if err != nil {
		return nil, err
	}
	createdAt := user.CreatedAt.Time
	return &createdAt, nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *model.User) (*time.Time, error) {
	if !obj.UpdatedAt.IsZero() {
		return &obj.UpdatedAt, nil
	}

	user, err := r.loadUser(ctx, obj)
	if err != nil {
		return nil, err
	}
	updatedAt := user.UpdatedAt.Time
	return &updatedAt, nil
}

// User returns graph.UserResolver implementation.
func (r *Resolver) User() graph.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
